### ISSUE TITLE
dice coefficent very small

### ISSUE THREAD

**Issue by cmlyldz** [milesial/Pytorch-UNet#100]
Hello milesial
Followong are my dice coefficent;
- 6.049226798489195e-09
- 6.049226798489195e-09
- 6.049226798489195e-09
- 6.049226798489195e-09
- 6.049226798489195e-09
- 6.049226798489195e-09
- 6.049226798489195e-09
- 6.049226798489195e-09
- 6.049226798489195e-09
- 6.049226798489195e-09
- 6.049226798489195e-09
- 6.049226798489195e-09
- 6.049226798489195e-09
- 6.049226798489195e-09
- 6.049226798489195e-09
- 6.049226798489195e-09
- 1.7126591595035328e-05
- 6.049226798489195e-09
- 0.2620634555092288
- 9.068408052703703e-06
- 6.049226798489195e-09
- 6.049226798489195e-09
- 6.049226798489195e-09
- 6.049226798489195e-09
- 6.049226798489195e-09
- 6.049226798489195e-09

those are last 26 epoch of 180 epoch. My dice coefficent always very small, what could it be wrong do you have any idea for me?

**Comment by milesial** [comment]
It is entirely dependant on your dataset. Make sure it is correctly labelled and loaded. Debug your losses with tensorboard.
I can't help you debug your particuliar training, debug as you would debug any training process.
