### ISSUE TITLE
What does this mean?

### ISSUE THREAD

**Issue by joehoeller** [milesial/Pytorch-UNet#102]
f'Either no mask or multiple masks found for the ID {idx}: {mask_file}'
AssertionError: Either no mask or multiple masks found for the ID frame_66319_0_lvl1_q95: []

**Comment by milesial** [comment]
It means that the image with this ID found either no mask or multiple masks with the same ID ...

**Comment by joehoeller** [comment]
How do I fix this?

**Comment by milesial** [comment]
You obviously have to match the IDs of the masks to the IDs of the corresponding image

**Comment by joehoeller** [comment]
I guess there’s some disconnect there on my part, where do I enter in IDs?
I didn’t see that in docs.

**Comment by milesial** [comment]
The ID of an image or mask is the unique part of the filename before the extension

**Comment by joehoeller** [comment]
File name, as in img name? Must be int only?
Please explain concept of ID and what it does and how I’m supposed to
implement.

**Comment by milesial** [comment]
It is very simple : the image name and the mask name on your file system have to match, so the program can link the two. The ID is the part of the filename before the extension. It does not have to be an integer.

If you have an image `frame_66319_0_lvl1_q95.jpg`, then for example you would have to have the mask `frame_66319_0_lvl1_q95_mask.gif`, with a common prefix, which is the ID

**Comment by joehoeller** [comment]
Thank you sir, please close this out now.
