### ISSUE TITLE
predict.py中第49行return mask > out_threshold返回的是True/False，怎么能生成图片呢？

### ISSUE THREAD

**Issue by yangj2133** [milesial/Pytorch-UNet#104]
predict.py中第49行return mask > out_threshold返回的是True/False，怎么能生成图片呢？

**Comment by liaojiacai** [comment]
> 
> 
> predict.py中第49行return mask > out_threshold返回的是True/False，怎么能生成图片呢？

我也有这个问题，你是怎么解决的呢？
