### ISSUE TITLE
 loss is about 0.5~~ and predict picture is onliy white

### ISSUE THREAD

**Issue by dongshenhan** [milesial/Pytorch-UNet#110]
i have a problem that loss is already bigger than 0.5.My picture is 8bit.My train data is form https://github.com/zhixuhao/unet,8bit png gray picture about 29 pictures.but the predict picture already white.i already change the channels form 3 to 1.please  help me

**Comment by milesial** [comment]
What do you mean 'already' ? you need to train longer. Also 29 picture isn't very much without data augmentation

**Comment by qiuyuan666** [comment]
> i have a problem that loss is already bigger than 0.5.My picture is 8bit.My train data is form https://github.com/zhixuhao/unet,8bit png gray picture about 29 pictures.but the predict picture already white.i already change the channels form 3 to 1.please  hel

> i have a problem that loss is already bigger than 0.5.My picture is 8bit.My train data is form https://github.com/zhixuhao/unet,8bit png gray picture about 29 pictures.but the predict picture already white.i already change the channels form 3 to 1.please  help me

我也有这样的问题，题主解决了吗？
