### ISSUE TITLE
No such file or directory: 'MODEL.pth'

### ISSUE THREAD

**Issue by hyysky** [milesial/Pytorch-UNet#112]
While trying to predict a single image:
  File "predict.py", line 112, in <module>
    net.load_state_dict(torch.load(args.model, map_location=device))
  File "/home/wangy/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 419, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'MODEL.pth'
 What should i do?

**Comment by milesial** [comment]
Please read the README for prediction instruction. You have to provide your trained model to the predict script
