### ISSUE TITLE
ValueError: Target size must be the same as input size

### ISSUE THREAD

**Issue by jayhung97724** [milesial/Pytorch-UNet#113]
Hi, Thanks for your great work!

I'm trying to train this model my own dataset, which is a grayscale image(X-ray), and the mask is the segmentation of spine, also grayscale. However, I encountered this error:

```
Traceback (most recent call last):
  File "train.py", line 174, in <module>
    val_percent=args.val / 100)
  File "train.py", line 80, in train_net
    loss = criterion(masks_pred, true_masks)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\loss.py", line 601, in forward
    reduction=self.reduction)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\functional.py", line 2112, in binary_cross_entropy_with_logits
    raise ValueError("Target size ({}) must be the same as input size ({})".format(target.size(), input.size()))
ValueError: Target size (torch.Size([1, 3, 600, 250])) must be the same as input size (torch.Size([1, 1, 600, 250]))
``` 

I've checked the `masks_pred.shape` and `true_masks.shape` are all `torch.Size([1, 1, 600, 250])`, do you have any idea why this happened?

**Comment by Branikas** [comment]
In predict.py somewhere there is a line of code like this: (line 166 for me)
net = UNet(n_channels=3, n_classes=1)
Probably if you set n_channels=1 will solve the problem for you.

**Comment by milesial** [comment]
yes that is it, also in train.py

**Comment by Branikas** [comment]
Sorry, I meant predict.py :P

**Comment by jayhung97724** [comment]
Thanks for the reply, I've also set n_channels in predict.py to 1, but the error still pops up *randomly*, I mean at different batch in the several tries to execute train.py.
 
![image](https://user-images.githubusercontent.com/14779848/71666643-c0bd4900-2d9c-11ea-824e-b6854e7f55d2.png)

**Comment by jayhung97724** [comment]
I somehow found the reason, it's because several images in the dataset I got are not grayscale, I'll try figure that out! Sorry for bothering.

**Comment by Mr-W-Bin** [comment]
@jayhung97724 Hello，how you get this problem solved?Could you tell me
