### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by Cassie0207** [milesial/Pytorch-UNet#115]
AssertionError:'Either no mask or multiple masks found for the ID LIDC-IDRI-XXXXXXXX_high:[].
Here are my pictures and masks, they are one to one.
Image name:LIDC-IDRI-0001_1.3.6.1.4.1.14519.5.2.1.6279.6001.179049373636438705059720603192_42_high.jpg
Mask name:LIDC-IDRI-0001_1.3.6.1.4.1.14519.5.2.1.6279.6001.179049373636438705059720603192_42_high_mask.gif

Can you help me? Thx

**Comment by milesial** [comment]
It may be that the dots "." in the filenames are problematic, try removing them.

**Comment by Cassie0207** [comment]
I tried to remove the dots'.' in the filenames, but it still reports the same error. Do you have other ideas?
Thanks advanced.

**Comment by milesial** [comment]
Mmh... So this line normally finds the associated mask https://github.com/milesial/Pytorch-UNet/blob/060bdcd69886a3082a6f8fb7746e12d5fca3e360/utils/dataset.py#L46

The common ID seems to be `LIDC-IDRI-0001_1.3.6.1.4.1.14519.5.2.1.6279.6001.179049373636438705059720603192_42_high` (or without the dots), so the mask should be found if it start with that.

Are your masks in the correct masks directory ?
And if you remove this specific image, does it work with the other images/masks ?

**Comment by Cassie0207** [comment]
My masks are in correct directory...
In fact, it seems     mask_file = glob(self.masks_dir + idx + '*')     couldnot found  mask file , I printed them, and they were[].

**Comment by milesial** [comment]
Can you print `self.masks_dir + idx ` ? maybe the idx is wrong or a '/' is missing

**Comment by Cassie0207** [comment]
They were still  [].
Or  can you provide your data folder style  for me.

**Comment by milesial** [comment]
I put all my masks into data/masks, and those are found with the line https://github.com/milesial/Pytorch-UNet/blob/060bdcd69886a3082a6f8fb7746e12d5fca3e360/train.py#L20
Maybe you could try putting an absolute path there.

What OS are you on ?

**Comment by Cassie0207** [comment]
Windows.   

dir_img = r'\\2018\LIDC-v3\demo_jpg'
dir_mask = r'\\2018\LIDC-v3\demo_mask'

Maybe, because my path was  a network path?
Thanks a lot.

**Comment by Cassie0207** [comment]
Mmh....I remove all my images and masks to local path, then they worked well.
Thanks a lot.

**Comment by milesial** [comment]
yep, seems to be that in windows you need `\` and in unix you need `/`
