### ISSUE TITLE
two  kinds of classes make predict picture all black  

### ISSUE THREAD

**Issue by dongshenhan** [milesial/Pytorch-UNet#119]
when i get two classes picture which is  Pseudo color png  has two color of label to train ,i found that my predict picture is black,but loss is normal. if i should change the code of train.py about (  net = UNet(n_channels=3, n_classes=2))?but  i see the notes that if classes is two ,classes is only 1 .

**Comment by dongshenhan** [comment]
my loss is 0.07

**Comment by milesial** [comment]
if you have two classes and a background, put n_classes=3, else if you have 2 classes that cover all the image (like my example with cars), you can set n_classes=1.

**Comment by milesial** [comment]
You may try to visualize the predictions before the thresholding if all you see is black pixels

**Comment by dongshenhan** [comment]
thanks,thanks，
when i make n_classes to 3,the code have a error reporting about (RuntimeError: 1only batches of spatial targets supported (non-empty 3D tensors) but got targets of size: : [1, 1, 104, 497]).
If i use n_classes=1 on the picture which has one label ,the result is correct ,but when i use two kind of class label picture,the predict picture  only  black.
when i use some of the one class picure and some of the two class,i find that my result usually is black, 
so i think maybe the problem is  two kinds of label picture>?

**Comment by dongshenhan** [comment]
thanks your replly,
my error is "  File "/home/hds/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1872, in nll_loss
ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index) RuntimeError: 1only batches of spatial targets supported (non-empty 3D tensors) but got targets of size: : [1, 1, 80, 479]" 
i will work hard to sovle this problem

**Comment by milesial** [comment]
I think that you are loading your masks wrong, go read the documentation for the crossentropy loss

**Comment by dongshenhan** [comment]
whether mask picture only have the pixel 1 or 0?if i have two clasees,second classes area pixel of  mask picture  can't be 2?my means that a mask picture have three pixel about 0,1,2.

**Comment by milesial** [comment]
the output of the net is probabilities, so between 0 and 1 for each class, and either 0 or 1 after thresholding, I don't know what you mean.

**Comment by dongshenhan** [comment]
thanks thanks thanks for your help
 There are three classes's areas in one of my pictures ，background,dog and cat.so i use labelme to mark them 。I observe the gray value of the  mask picture find that they have three kinds of the gray value about 0,1,2 not olny 0 and 1  .

**Comment by milesial** [comment]
If you used the predict.py script the softmax is already included https://github.com/milesial/Pytorch-UNet/blob/060bdcd69886a3082a6f8fb7746e12d5fca3e360/predict.py#L32 so you should have indeed: 0, 1 or 2.

**Comment by dongshenhan** [comment]
thanks  thanks thanks your reply ,thanks for your help
so first i can only mark cat on the one Image to get a mask picture,and mark dog on that image to get another mask picture. oh,i could have to relabel it.thank you thank you

**Comment by hwh-hit** [comment]
@dongshenhan Hi,I have the same confusion with you. I have 3 classes(bg, dog, cat) in my  dataset made by labelme, should we make the mask target as (batch, width, heigth) format? And 0,1,2 in the mask target not only 0,1?Looking forward to your reply
