### ISSUE TITLE
why your deepest layer only have 512?

### ISSUE THREAD

**Issue by W-void** [milesial/Pytorch-UNet#120]
you define 'self.down4 = Down(512, 512)', but from the u-net picture, we can see test deepest layer have 1024 maps.

**Comment by milesial** [comment]
you can read more in #90 and #69

**Comment by W-void** [comment]
> you can read more in #90 and #69

thx，but this will reduce the number of parameters，I wonder if this will change performance

**Comment by milesial** [comment]
I think the performance is a little bit impacted indeed, you can always deactivate the bilinear upsampling in my net https://github.com/milesial/Pytorch-UNet/blob/060bdcd69886a3082a6f8fb7746e12d5fca3e360/unet/unet_model.py#L9
