### ISSUE TITLE
BasicDataset loads mask images but CaVana data give rle_mask

### ISSUE THREAD

**Issue by jpainam** [milesial/Pytorch-UNet#121]
Hi. i'm using the `train_masks.csv` from CAVANA dataset but the class `BasicDataset` loads the masks as images. Where and how can I convert my segmentation  values into mask images?

![image](https://user-images.githubusercontent.com/1701705/72323835-9779b280-36e4-11ea-811a-080c58a5185b.png)

Thank you

**Comment by milesial** [comment]
The masks are in the file train_masks.zip, no need to read the csv

**Comment by jpainam** [comment]
I actually created my own segmentation mask (not image mask). Do you know how I can convert these values to image masks and use it?
Her is my dataset
![image](https://user-images.githubusercontent.com/1701705/72335135-75d6f600-36f9-11ea-9f07-f7ecddc37467.png)

Thank you

**Comment by milesial** [comment]
how did you create the mask ? what format is the mask in ? RLE ? You would have to convert from RLE to pixels

**Comment by jpainam** [comment]
I created the mask using VGG Annotator http://www.robots.ox.ac.uk/~vgg/software/via/ and exported the annotations in COCO format.
Do you know any tools that can convert these masks into image masks? Or i should first convert them into RLE; then RLE to pixels?
![image](https://user-images.githubusercontent.com/1701705/72407716-72944680-379b-11ea-986b-702752150cca.png)
Thank you

**Comment by milesial** [comment]
What if you choose "Download as image" ? Otherwise, I don't know of any tools. But if you can convert coco -> RLE, it is very easy to convert RLE to images with a simple script.

**Comment by jpainam** [comment]
`Download as Image` only download the annotated image. Like below. I will convert coco to RLE and then from RLE to image. Thank you
![adutta_swan](https://user-images.githubusercontent.com/1701705/72423603-86ea3a80-37bf-11ea-9449-373494533663.jpg)
