### ISSUE TITLE
Problem with dataset.py in detecting masks and images

### ISSUE THREAD

**Issue by lucyd42** [milesial/Pytorch-UNet#122]
Hey,

I wanted to train my network on UNet, but I kept getting the error

` AssertionError: Either no mask or multiple masks found for the ID `

It turned out that the problem could be solved by naming the image and masks the same filename, but I had the same names for my images and masks. 

Seems like the problem is with the line 46 in dataset.py

` mask_file = glob(self.masks_dir + idx + '*')`

If the images are named 0.png,1.png,2.png...11.png,12.png and so on...the system will see the mask_file variable as (path/1*) for the img 1.png but the variable will get assigned 1.png, 11.png and 12.png, 13.png and so on because all match the condition "1*.png".

Solution was to change my  filenames as 1image.png , 2image.png etc.. so that the * wouldnt capture any other images but the true mask.

If someone can add a fix for this, it will be great.

Regards
Aditya

**Comment by milesial** [comment]
Hi!
Oh yes that's a problem. I assumed each identifier was a unique prefix of the mask name. This could also be fixed by renaming images and masks as 00001.png, 00002.png, ...

I'll leave this open for others to see and if someone has a nice fix for this (that still works with the original format), feel free to open a PR

**Comment by JakeCowton** [comment]
For anyone who finds themself here, `string.zfill()` will help
https://docs.python.org/3.8/library/stdtypes.html?highlight=zfill#str.zfill

**Comment by qiuyuan666** [comment]
> Hi!
> Oh yes that's a problem. I assumed each identifier was a unique prefix of the mask name. This could also be fixed by renaming images and masks as 00001.png, 00002.png, ...
> I'll leave this open for others to see and if someone has a nice fix for this (that still works with the original format), feel free to open a PR

Hello,milesial!    I had the same problem.
Even though I changed the image names to 1img,2img,3img,.... , it still reported the following error:
**AssertionError: Either no mask or multiple masks found for the ID**
How can I solve this problem?
