### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by hbuck1996** [milesial/Pytorch-UNet#124]
python predict.py -i test1.jpg --viz --no-save
Segmentation fault (core dumped)

**Comment by hbuck1996** [comment]
训练好模型后，预测图像时出现Segmentation fault (core dumped)错误，求解决办法~

**Comment by milesial** [comment]
What version of python and pytorch are you running ?

**Comment by hbuck1996** [comment]
> What version of python and pytorch are you running ?
 python 3.6.10 and pytorch 1.4.0
What is the correct version of python and pytorch?

**Comment by milesial** [comment]
These versions should work. I recommend you debug the script to find the problematic statement

**Comment by hbuck1996** [comment]
> These versions should work. I recommend you debug the script to find the problematic statement

OK，Thank you！

**Comment by qiuyuan666** [comment]
> 训练好模型后，预测图像时出现Segmentation fault (core dumped)错误，求解决办法~

我预测图片没有反应，请问题主解决问题了吗？我是研一小白，求指点

**Comment by hbuck1996** [comment]
> > 训练好模型后，预测图像时出现Segmentation fault (core dumped)错误，求解决办法~
> 
> 我预测图片没有反应，请问题主解决问题了吗？我是研一小白，求指点

加我QQ吧，一起交流，394539781
