### ISSUE TITLE
failed to  run predict.py

### ISSUE THREAD

**Issue by leijue222** [milesial/Pytorch-UNet#130]
My requirements are

> python 3.6.9
> matplotlib 3.1.1
> numpy 1.16.5
> Pillow 6.2.2
> torch 1.1.0
> torchvision 0.3.0
> tensorboard 2.1.0

I download your MODEL.pth form [here](https://github.com/milesial/Pytorch-UNet/blob/e2e46ce509382a45b1db4e1f639aeed568f6cb3e/MODEL.pth)

Then I try to run predict.py, but failed.It return error message

> Traceback (most recent call last):
>   File "predict.py", line 112, in <module>
>     net.load_state_dict(torch.load(args.model, map_location=device))
>   File "E:\Anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 777, in load_state_dict
>     self.__class__.__name__, "\n\t".join(error_msgs)))
> RuntimeError: Error(s) in loading state_dict for UNet:
>         Missing key(s) in state_dict: "inc.double_conv.0.weight", "inc.double_conv.0.bias", "inc.double_conv.1.weight", "inc.double_conv.1.bias", "inc.double_conv.1.running_mean", "inc.double_conv.1.running_var", "inc.double_conv.3.weight", "inc.double_conv.3.bias", "inc.double_conv.4.weight", "inc.double_conv.4.bias", "inc.double_conv.4.running_mean", "inc.double_conv.4.running_var", "down1.maxpool_conv.1.double_conv.0.weight", "down1.maxpool_conv.1.double_conv.0.bias", "down1.maxpool_conv.1.double_conv.1.weight", "down1.maxpool_conv.1.double_conv.1.bias", "down1.maxpool_conv.1.double_conv.1.running_mean", "down1.maxpool_conv.1.double_conv.1.running_var", "down1.maxpool_conv.1.double_conv.3.weight", "down1.maxpool_conv.1.double_conv.3.bias", "down1.maxpool_conv.1.double_conv.4.weight", "down1.maxpool_conv.1.double_conv.4.bias", "down1.maxpool_conv.1.double_conv.4.running_mean", "down1.maxpool_conv.1.double_conv.4.running_var", "down2.maxpool_conv.1.double_conv.0.weight", "down2.maxpool_conv.1.double_conv.0.bias", "down2.maxpool_conv.1.double_conv.1.weight", "down2.maxpool_conv.1.double_conv.1.bias", "down2.maxpool_conv.1.double_conv.1.running_mean", "down2.maxpool_conv.1.double_conv.1.running_var", "down2.maxpool_conv.1.double_conv.3.weight", "down2.maxpool_conv.1.double_conv.3.bias", "down2.maxpool_conv.1.double_conv.4.weight", "down2.maxpool_conv.1.double_conv.4.bias", "down2.maxpool_conv.1.double_conv.4.running_mean", "down2.maxpool_conv.1.double_conv.4.running_var", "down3.maxpool_conv.1.double_conv.0.weight", "down3.maxpool_conv.1.double_conv.0.bias", "down3.maxpool_conv.1.double_conv.1.weight", "down3.maxpool_conv.1.double_conv.1.bias", "down3.maxpool_conv.1.double_conv.1.running_mean", "down3.maxpool_conv.1.double_conv.1.running_var", "down3.maxpool_conv.1.double_conv.3.weight", "down3.maxpool_conv.1.double_conv.3.bias", "down3.maxpool_conv.1.double_conv.4.weight", "down3.maxpool_conv.1.double_conv.4.bias", "down3.maxpool_conv.1.double_conv.4.running_mean", "down3.maxpool_conv.1.double_conv.4.running_var", "down4.maxpool_conv.1.double_conv.0.weight", "down4.maxpool_conv.1.double_conv.0.bias", "down4.maxpool_conv.1.double_conv.1.weight", "down4.maxpool_conv.1.double_conv.1.bias", "down4.maxpool_conv.1.double_conv.1.running_mean", "down4.maxpool_conv.1.double_conv.1.running_var", "down4.maxpool_conv.1.double_conv.3.weight", "down4.maxpool_conv.1.double_conv.3.bias", "down4.maxpool_conv.1.double_conv.4.weight", "down4.maxpool_conv.1.double_conv.4.bias", "down4.maxpool_conv.1.double_conv.4.running_mean", "down4.maxpool_conv.1.double_conv.4.running_var", "up1.conv.double_conv.0.weight", "up1.conv.double_conv.0.bias", "up1.conv.double_conv.1.weight", "up1.conv.double_conv.1.bias", "up1.conv.double_conv.1.running_mean", "up1.conv.double_conv.1.running_var", "up1.conv.double_conv.3.weight", "up1.conv.double_conv.3.bias", "up1.conv.double_conv.4.weight", "up1.conv.double_conv.4.bias", "up1.conv.double_conv.4.running_mean", "up1.conv.double_conv.4.running_var", "up2.conv.double_conv.0.weight", "up2.conv.double_conv.0.bias", "up2.conv.double_conv.1.weight", "up2.conv.double_conv.1.bias", "up2.conv.double_conv.1.running_mean", "up2.conv.double_conv.1.running_var", "up2.conv.double_conv.3.weight", "up2.conv.double_conv.3.bias", "up2.conv.double_conv.4.weight", "up2.conv.double_conv.4.bias", "up2.conv.double_conv.4.running_mean", "up2.conv.double_conv.4.running_var", "up3.conv.double_conv.0.weight", "up3.conv.double_conv.0.bias", "up3.conv.double_conv.1.weight", "up3.conv.double_conv.1.bias", "up3.conv.double_conv.1.running_mean", "up3.conv.double_conv.1.running_var", "up3.conv.double_conv.3.weight", "up3.conv.double_conv.3.bias", "up3.conv.double_conv.4.weight", "up3.conv.double_conv.4.bias", "up3.conv.double_conv.4.running_mean", "up3.conv.double_conv.4.running_var", "up4.conv.double_conv.0.weight", "up4.conv.double_conv.0.bias", "up4.conv.double_conv.1.weight", "up4.conv.double_conv.1.bias", "up4.conv.double_conv.1.running_mean", "up4.conv.double_conv.1.running_var", "up4.conv.double_conv.3.weight", "up4.conv.double_conv.3.bias", "up4.conv.double_conv.4.weight", "up4.conv.double_conv.4.bias", "up4.conv.double_conv.4.running_mean", "up4.conv.double_conv.4.running_var".
>         Unexpected key(s) in state_dict: "inc.conv.conv.0.weight", "inc.conv.conv.0.bias", "inc.conv.conv.1.weight", "inc.conv.conv.1.bias", "inc.conv.conv.1.running_mean", "inc.conv.conv.1.running_var", "inc.conv.conv.3.weight", "inc.conv.conv.3.bias", "inc.conv.conv.4.weight", "inc.conv.conv.4.bias", "inc.conv.conv.4.running_mean", "inc.conv.conv.4.running_var", "down1.mpconv.1.conv.0.

I found a workaround on stackflow.It tell to Increase strict = False.

> `net.load_state_dict(torch.load(args.model, map_location=device), strict=False)`

Then no error is reported, but the out.jpg is all black.
output-> ![output](https://user-images.githubusercontent.com/30276789/74233374-7ddc8280-4d05-11ea-9df5-3d65a7d0fe29.jpg)
I have no any idea to solve it.
Could you give me some help?
Thanks!

**Comment by Branikas** [comment]
That's strange, it means all the attributes of your modules are not passed in the state_dict for some reason. I 've been using Milesial's model for a while and never had such a problem. Did you change anything in the code?

**Comment by leijue222** [comment]
No，I didn't change anything in the code.
I have tried many times and tried other people's fork of past code, but none worked.
If your computer can run the code and model successfully , maybe I can too.
Would mind give me your code and model to me? 
And tell me you requirements.?
I would appreciate of it.
My e-mail is leijue@jxnu.edu.cn
Thanks!

**Comment by leijue222** [comment]
> 这很奇怪，这意味着出于某种原因，未将所有模块的属性传递给state_dict。我使用Milesial的模型已有一段时间了，从来没有遇到过这样的问题。您是否更改了代码中的任何内容？

No，I didn't change anything in the code.
I have tried many times and tried other people's fork of past code, but none worked.
If your computer can run the code and model successfully , maybe I can run it too.
Would you mind give your code and model to me? 
And tell me your requirements.?
I would appreciate of it.
My e-mail is leijue@jxnu.edu.cn
Thanks!

**Comment by leijue222** [comment]
> That's strange, it means all the attributes of your modules are not passed in the state_dict for some reason. I 've been using Milesial's model for a while and never had such a problem. Did you change anything in the code?

No，I didn't change anything in the code.
I have tried many times and tried other people's fork of past code, but none worked.
If your computer can run the code and model successfully , maybe I can run it too.
Would you mind give your code and model to me?
And tell me your requirements.?
I would appreciate of it.
My e-mail is leijue@jxnu.edu.cn
Thanks!

**Comment by leijue222** [comment]
Does anyone else can help me solve this problem？
I'm desperate.

**Comment by leijue222** [comment]
I think it might be a problem with my computer.
Then I try run it in my server with ubuntu16.0.4,
But I got the same erros....
I didn't change anything in the code.
I uploaded the code and model to Google Cloud Disk:
https://drive.google.com/open?id=1fyauLBmeX-JqbHKiA2ufBENxpBCDKD5G

**Comment by leijue222** [comment]
HI,milesial
Can you give me some help?
I just configured the gpu version of pytorch again
> certifi         2016.2.28
cycler          0.10.0
kiwisolver      1.1.0
matplotlib      3.0.3
numpy           1.18.1
Pillow          6.2.0
pip             20.0.2
pyparsing       2.4.6
python-dateutil 2.8.1
setuptools      36.4.0
six             1.14.0
torch           1.2.0+cu92
torchvision     0.4.0+cu92
wheel           0.29.0
wincertstore    0.2

But I faied agein....
![image](https://user-images.githubusercontent.com/30276789/74592687-bf02c880-505e-11ea-8117-30ff1a8e6da5.png)

**Comment by leijue222** [comment]
I think maybe I have known where is the problem.
The MODEL.pth belongs to the Doka model. My couputer just have  950M with 2G.
Doka model cannot run on a single model computer.

**Comment by leijue222** [comment]
I successed by use t[his version Pytorch-UNet](https://github.com/milesial/Pytorch-UNet/tree/e2e46ce509382a45b1db4e1f639aeed568f6cb3e).Reference #18 
The problem maybe is the latest code is incompatible with the previous MODEL.pth
