### ISSUE TITLE
Predict.py process killed.

### ISSUE THREAD

**Issue by Branikas** [milesial/Pytorch-UNet#131]
Hi Milesial.

I tried to predict an image from a trained model but the terminal just kills the process (it actually says killed) and I get no output. I think this could be because at the same time I am training a model as well, so the resources could be all used (i predict at the CPU though, so that GPU is meant for the training), or because I am using a very large image for prediction and large kernels as well (conv size=5 and dilation=2).
Any ideas? 
I cannot stop the training right now to see if that is the problem, it will take some days...
Thank you.

**Comment by leijue222** [comment]
Can you use UNet to segment objects other than cars? 
Like train or portrait?
