### ISSUE TITLE
RuntimeError: Given input size: (512x4x1). Calculated output size: (512x2x0). Output size is too small

### ISSUE THREAD

**Issue by GasparPizarro** [milesial/Pytorch-UNet#134]
I am using the `train.py` script with a datasets of 1323 grayscale images (and masks) of different sizes, and I get the following error:

    RuntimeError: Given input size: (512x4x1). Calculated output size: (512x2x0). Output size is too small
    > /usr/local/lib/python3.6/dist-packages/torch/nn/functional.py(488)_max_pool2d()
        486         stride = torch.jit.annotate(List[int], [])
        487     return torch.max_pool2d(
    --> 488         input, kernel_size, stride, padding, dilation, ceil_mode)
        489 
        490 max_pool2d = boolean_dispatch(

Is there a limitation on the shape of the images to be used with the `train.py` script?

**Comment by milesial** [comment]
Yes, due to how the network is constructed, small images in width or height are not recommended
