### ISSUE TITLE
OSError: Caught OSError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by vutienhung260798** [milesial/Pytorch-UNet#135]
![image](https://user-images.githubusercontent.com/43244725/75113550-8e83e580-5681-11ea-9696-35a37bd77f0e.png)
help me !!!

**Comment by sainatarajan** [comment]
@vutienhung260798 That seems to be a path issue. Check whether that file really exists or not in that path.

**Comment by vutienhung260798** [comment]
> @vutienhung260798 That seems to be a path issue. Check whether that file really exists or not in that path.

thank you!!
