### ISSUE TITLE
RuntimeError: Expected object of scalar type Byte but got scalar type Double for sequence element 2 in sequence argument at position #1 'tensors'

### ISSUE THREAD

**Issue by zxzyzlz** [milesial/Pytorch-UNet#138]
### **Complete error message:**
Traceback (most recent call last):
  File "D:/python workspace/Pytorch-UNet/train.py", line 175, in <module>
    val_percent=args.val / 100)
  File "D:/python workspace/Pytorch-UNet/train.py", line 67, in train_net
    for batch in train_loader:
  File "E:\anaconda\envs\python36\lib\site-packages\torch\utils\data\dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "E:\anaconda\envs\python36\lib\site-packages\torch\utils\data\dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "E:\anaconda\envs\python36\lib\site-packages\torch\utils\data\_utils\worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "E:\anaconda\envs\python36\lib\site-packages\torch\utils\data\_utils\collate.py", line 63, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "E:\anaconda\envs\python36\lib\site-packages\torch\utils\data\_utils\collate.py", line 63, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "E:\anaconda\envs\python36\lib\site-packages\torch\utils\data\_utils\collate.py", line 43, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: Expected object of scalar type Byte but got scalar type Double for sequence element 2 in sequence argument at position #1 'tensors'
### **An error line**:
    for epoch in range(epochs):
        net.train()
        epoch_loss = 0
        with tqdm(total=n_train, desc=f'Epoch {epoch + 1}/{epochs}', unit='img') as pbar:
            for batch in train_loader: ##############An error line
                imgs = batch['image']
                true_masks = batch['mask']
                assert imgs.shape[1] == net.n_channels, \
                    f'Network has been defined with {net.n_channels} input channels, ' \
                    f'but loaded images have {imgs.shape[1]} channels. Please check that ' \
                    'the images are loaded correctly.'

                imgs = imgs.to(device=device, dtype=torch.float32)
                mask_type = torch.float32 if net.n_classes == 1 else torch.long
                true_masks = true_masks.to(device=device, dtype=mask_type)

I want to increase the value of batchsize. When I increase the batchsize from the default value of 1 to 8 or 16, I will report this kind of mismatching error. How to solve this problem and what is the reason?Thank you very much

**Comment by YolandaTheCoder** [comment]
Changing
img = self.preprocess(img, self.scale)
mask = self.preprocess(mask, self.scale)
to
img = self.preprocess(img, self.scale).astype(np.float)
mask = self.preprocess(mask, self.scale).astype(np.float)
in __getitem__ function of dataset.py fixed this problem

**Comment by kihararuntu** [comment]
I encountered this error before, it may caused by that some of your masks have two channels

**Comment by zxzyzlz** [comment]
> Changing
> img = self.preprocess(img, self.scale)
> mask = self.preprocess(mask, self.scale)
> to
> img = self.preprocess(img, self.scale).astype(np.float)
> mask = self.preprocess(mask, self.scale).astype(np.float)
> in **getitem** function of dataset.py fixed this problem

Thank you very much. Your answer has solved my problem for a long time

**Comment by fromWRF** [comment]
> I encountered this error before, it may caused by that some of your masks have two channels

Yes, I have also encountered this error, since the calcualted optical flow has two channels, how i can solve this problem?
