### ISSUE TITLE
learning crf parameters

### ISSUE THREAD

**Issue by xiongzhiyao** [milesial/Pytorch-UNet#14]
Dear Milesial,

I am wondering do you know where has been the crf model learned? I believe this crf python package doesn't include any training method, when I am using it on my segmentation problem it isn't improving the accuracy(instead sometimes it worse the output), could you share your experience of using this pydencrf package?

Best and thank you for your help in advance!

**Comment by milesial** [comment]
Hi !
The CRF post processing was just a test to see if it could improve the results for the challenge. I did not see huge improvements indeed. I just applied the basic usage of the package, with arbitrary parameters. I haven't spent much time tweaking them.
Feel free to change the parameters as you like, or even use another CRF library.
