### ISSUE TITLE
CUDA out of memory. Tried to allocate 150.00 MiB (GPU 0; 4.00 GiB total capacity; 2.48 GiB already allocated; 147.70 MiB free; 54.93 MiB cached)

### ISSUE THREAD

**Issue by wjk660** [milesial/Pytorch-UNet#140]
I try to run the code,but it always show this error,what show I do?

**Comment by whenyd** [comment]
use smaller batch size

**Comment by milesial** [comment]
Get more GPU memory, use a smaller batch size or reduce the scaling of the images.
