### ISSUE TITLE
A problem in dataset.py

### ISSUE THREAD

**Issue by CthLeo** [milesial/Pytorch-UNet#142]
Statement at line 39:

if img_trans.max() > 1:
     img_trans = img_trans / 255

Why  all of values of img_trans is less than 1? A Question from a novice ^_^.

**Comment by milesial** [comment]
It depends on how you load your images. If you load your masks in greyscale or black & white, most image libraries will produce a tensor with values from 0 to 1.

For RGB values, it depends, so if the values are 0-255, they need to be normalized to 0-1.

The network needs the input to be normalized.

**Comment by CthLeo** [comment]
> It depends on how you load your images. If you load your masks in greyscale or black & white, most image libraries will produce a tensor with values from 0 to 1.
> For RGB values, it depends, so if the values are 0-255, they need to be normalized to 0-1.
> The network needs the input to be normalized.

Oh, I get it. Thanks you!
