### ISSUE TITLE
help

### ISSUE THREAD

**Issue by gdut3118007086** [milesial/Pytorch-UNet#143]
Either no mask or multiple masks found for the ID 1: ['data/masks\\1.jpg', 'data/masks\\10.jpg', 'data/masks\\11.jpg', 'data/masks\\12.jpg', 'data/masks\\13.jpg', 'data/masks\\14.jpg', 'data/masks\\15.jpg', 'data/masks\\16.jpg', 'data/masks\\17.jpg', 'data/masks\\18.jpg', 'data/masks\\19.jpg']

**Comment by gdut3118007086** [comment]
Modify image name

**Comment by yyyzzzhao** [comment]
change line in dataset.py < glob(... + idx + '*')> to <glob(... + idx + '.*')>
