### ISSUE TITLE
'tqdm' object has no attribute 'set_postfix'

### ISSUE THREAD

**Issue by zs147** [milesial/Pytorch-UNet#144]
python train.py

INFO: Using device cuda
INFO: Network:
	3 input channels
	1 output channels (classes)
	Bilinear upscaling
INFO: Creating dataset with 5088 examples
INFO: Starting training:
        Epochs:          5
        Batch size:      1
        Learning rate:   0.1
        Training size:   4580
        Validation size: 508
        Checkpoints:     True
        Device:          cuda
        Images scaling:  0.5
    
Epoch 1/5:   0%|                                                                                                           | 0/4580 [00:00<?, ?img/s]
Traceback (most recent call last):
  File "train.py", line 180, in <module>
    val_percent=args.val / 100)
  File "train.py", line 83, in train_net
    pbar.set_postfix(**{'loss (batch)': loss.item()})
AttributeError: 'tqdm' object has no attribute 'set_postfix'

**Comment by milesial** [comment]
What is your version of tqdm? Please update it to the latest.

**Comment by zs147** [comment]
I have resolve thie problem through update tqdm version, thanks.
