### ISSUE TITLE
Multi-class issues and discussion

### ISSUE THREAD

**Issue by wangxinyu199306** [milesial/Pytorch-UNet#15]
Hi, thanks for your code, it works well on my own dataset.
However, It seems like this project can only support the binary classification problem.
when I try to modify as following:
train.py -124 -> n_classes = 3
this function: loss = criterion(masks_probs_flat, true_masks_flat) ---from train.py 81
goes wrong because the shape of two parameters dismatch.

My mask image is a single 8-bit image with 4 different intensities (0,1,2,3) represent 4 classes(background,class1,class2,class3)
how to modify the code so that it can support  a multi-class problem.
thanks advanced

**Comment by milesial** [comment]
Hey!
Oh, I haven't tested it with more classes, so this isn't really a surprise.
Can you check that the `img` and `true_masks` (L. 68 - 69) fetched from the batch have correct shape ? If so, check the output of the net (`masks_pred`  L. 75), it should have 4 classes.
This might be an issue related with the cropping or loading of the true masks.
Feel free to open a pull request if you fixed the problem.

**Comment by PacificHongyang** [comment]
where is the directory checkpoints?

**Comment by TonyDongLB** [comment]
I already fix this problem, you can just change the final layer from 1 channel to 4, and using  a CrossEntropyLoss for 2D, but I don't know this model wether perform well in your project.
你可以直接把最后一层变为多通道的，之后修改损失函数，用交叉熵2D或者focal loss2D均可，但是不知道在多种类预测时候模型是否表现的好。
and thank for the code again.

**Comment by TonyDongLB** [comment]
你好，我觉得应该可以呀。


| |
图图
邮箱：donglibusi@163.com
|

签名由 网易邮箱大师 定制

On 10/23/2018 15:22, wangzhe0623 wrote:

@TonyDongLB 你好啊，请教下，我在尝试用这份代码做多分类（5类），直接把最后一层变成多通道。，对应true_mask我处理成了单通道的图像，标签为0-4，这样处理对吗？

**Comment by wangzhe0623** [comment]
@TonyDongLB 已经解决了，谢谢你哦～

**Comment by wangzhe0623** [comment]
@ChaoLi977 CrossEntropyLoss worked well with my code. Have you removed Sigmoid layer? And if you want to predict 3 classes you should change 'n_classes' to '3', not 2.

**Comment by ChaoLi977** [comment]
@wangzhe0623 Thanks a lot. I removed Sigmoid layer and use CrossEntropyLoss. Now it reports:"RuntimeError: Dimension out of range (expected to be in range of [-1, 0], but got 1)".  What the format of your mask images?  I use 8-bit images with value 0,1,2 as the categorical value. But I think maybe the label should be one-hot encoding, rather than categorical value.

**Comment by wangzhe0623** [comment]
@ChaoLi977 I do not think anything wrong with your true mask, note that 'predicted mask' should not be flatten or followed by any layers.

**Comment by zhouzhubin** [comment]
@wangzhe0623 你好，请问你一下，那个数据集是怎么做的，我了lableme做了，得到了json。然后我转化成lable.png的，但是我知道怎么搞才能，跟代码里train_mask的.gif格式的，你能给我说一下吗？我是刚搞这个语义分割，谢谢了啊

**Comment by zhouzhubin** [comment]
@wangxinyu199306 你好，请问你一下，你自己的数据是怎么处理的？用什么标注工具得到跟代码里train_mask的.gif格式的，我用的是lableme来标注的，但是后续我不知道怎么处理了，麻烦能说一下吗？谢谢了啊

**Comment by wangzhe0623** [comment]
@zhouzhubin 不一定做成gif的，把mask处理成单通道，每个像素值都为对应的category值就可以了。

**Comment by zhouzhubin** [comment]
@wangzhe0623 谢谢了啊！我目前就只有一类的，我如果把mask处理成单通道，我对应的像素值0、255吗？我的背景是0，对应的类别是255，这个算一类还是两类？

**Comment by zhouzhubin** [comment]
@wangzhe0623 哦哦，谢谢了啊，我去试试看看

**Comment by louxy126** [comment]
@wangxinyu199306 @wangzhe0623 @TonyDongLB 各位老哥，我想请教个问题：
我现在也在做多分类（10类），我根据你们的对话把unet_model.py中
`         return F.sigmoid(x)
改成了
        return torch.nn.CrossEntropyLoss(x)`
将train.py里line123
`net = UNet(n_channels=3, n_classes=10)`中的n_class=1改成了n_class=10
其他地方没改，但是在训练的时候报：
`    Starting training:
        Epochs: 5
        Batch size: 10
        Learning rate: 0.1
        Training size: 698
        Validation size: 36
        Checkpoints: True
        CUDA: False
    
Starting epoch 1/5.
/home/wrc/anaconda3/envs/unet/lib/python3.5/site-packages/torch/nn/modules/upsampling.py:122: UserWarning: nn.Upsampling is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.Upsampling is deprecated. Use nn.functional.interpolate instead.")
Traceback (most recent call last):
  File "/media/wrc/新加卷/lxy/Pytorch-UNet/train.py", line 139, in <module>
    img_scale=args.scale)
  File "/media/wrc/新加卷/lxy/Pytorch-UNet/train.py", line 76, in train_net
    masks_probs_flat = masks_pred.view(-1)
  File "/home/wrc/anaconda3/envs/unet/lib/python3.5/site-packages/torch/nn/modules/module.py", line 518, in __getattr__
    type(self).__name__, name))
AttributeError: 'CrossEntropyLoss' object has no attribute 'view'

Process finished with exit code 1`
想请问这是哪里出了问题？谢谢

**Comment by yuyijie1995** [comment]
I made my customized dataset which has 2 classes and the mask's pixel number I choose is 0,1,2. And 0 is the  background .I changed the unet model's class number as 2 and the Loss function is CrossEntropyLoss().But the error happened ,Could you give me some    suggestions? @wangxinyu199306 @TonyDongLB 
/home/wrc/anaconda3/envs/pytorch0.4/lib/python3.6/site-packages/torch/nn/modules/upsampling.py:122: UserWarning: nn.Upsampling is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.Upsampling is deprecated. Use nn.functional.interpolate instead.")
/home/wrc/anaconda3/envs/pytorch0.4/lib/python3.6/site-packages/torch/nn/functional.py:1006: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
Traceback (most recent call last):
  File "/home/wrc/yuyijie/Pytorch-UNet/train.py", line 139, in <module>
    img_scale=args.scale)
  File "/home/wrc/yuyijie/Pytorch-UNet/train.py", line 80, in train_net
    loss = criterion(masks_probs_flat, true_masks_flat)
  File "/home/wrc/anaconda3/envs/pytorch0.4/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wrc/anaconda3/envs/pytorch0.4/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 862, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "/home/wrc/anaconda3/envs/pytorch0.4/lib/python3.6/site-packages/torch/nn/functional.py", line 1550, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/wrc/anaconda3/envs/pytorch0.4/lib/python3.6/site-packages/torch/nn/functional.py", line 975, in log_softmax
    return input.log_softmax(dim)
RuntimeError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

**Comment by yuyijie1995** [comment]
@ChaoLi977 I met the same problem as you mentioned ,have you solved it?

**Comment by Ji-qing** [comment]
@louxy126 
我把sigmoid改成softmax，损失函数改成torch.nn.CrossEntropyLoss().
需要对label和predict结果做一些处理，来满足crossentropyloss() 的需求。
大概是这样
```
            masks_pred = net(imgs)
            true_masks_flat = true_masks.long()
            n, c, h, w = masks_pred.size()
            masks_probs_flat = masks_pred.transpose(1, 2).transpose(2, 3).contiguous()
            masks_probs_flat = masks_probs_flat[true_masks.view(n, h, w, 1).repeat(1, 1, 1, c) >= 0]
            masks_probs_flat = masks_probs_flat.view(-1, c)
            # target: (n*h*w,)
            mask = true_masks_flat >= 0
            true_masks_flat = true_masks_flat[mask]
            # true_masks_flat = true_masks#.view(-1)
            print(masks_probs_flat.size(), true_masks_flat.size())
            loss = criterion(masks_probs_flat, true_masks_flat)
```
用的数据集是cityscapes

**Comment by milesial** [comment]
@Ji-qing If you have 35 categories, your true masks should have 35 values for each pixel (one-hot encoded), and the prediction should output 35 values between 0 and 1 for each pixel. You wouldn't have a single 'image' but 35 layers of masks.

**Comment by Ji-qing** [comment]
@milesial  Thank you for you reply.
I am a newer in semantic segmentation. I do not know how to prepare my datasets, such as voc2012. The label in folder _SegmentationClass_ of voc2012 is colorful, and I want to convert the pixel value of the image to 0-20. But I do not know how to do.
And as you say, how to merge 35 layers of mask? Oo...

**Comment by milesial** [comment]
@Ji-qing if the label has multiple colors, then you can just iterate over the pixels and check each color. If it is RED convert the value to [1, 0, 0, 0, ..], if it's BLUE to [0, 1, 0, 0, 0 ... ], and so on. You should be able to convert a W\*H (if it has only 1 channel like voc2012 I believe) into a W\*H\*35 matrix. This preprocessing can be done in any way you like, but check out the OpenCV and Pillow libraries.
You can also do it the other way, and convert the 35 output masks into one, it only matters that the model output and the labels are the same shape so you can apply a loss to them. If the 35 layers are mutually exclusive, it's pretty simple to merge them ([1, 0, 0, 0, ...] to RED, ... ). Then your 'colors' would be your classes.

**Comment by yuyijie1995** [comment]
> @wangxinyu199306 @TonyDongLB 我有一个问题，通过网络预测得到的图片像素值在0和1之间。假设我的数据有35类，那么我应该怎么得到最终的图像呢？直接乘以35吗?

你好 能加个微信交流一下么 我也刚接触语义分割

**Comment by wangxinyu199306** [comment]
如果是35类的话，最后的输出应该是35维的feature map

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: yuyijie1995 <notifications@github.com>
发送时间: Friday, December 21, 2018 8:49:58 PM
收件人: milesial/Pytorch-UNet
抄送: Brandon; Mention
主题: Re: [milesial/Pytorch-UNet] ［for your support］multi-class problem (#15)


@wangxinyu199306<https://github.com/wangxinyu199306> @TonyDongLB<https://github.com/TonyDongLB> 我有一个问题，通过网络预测得到的图片像素值在0和1之间。假设我的数据有35类，那么我应该怎么得到最终的图像呢？直接乘以35吗?

你好 能加个微信交流一下么 我也刚接触语义分割

―

**Comment by ChaoLi977** [comment]
@yuyijie1995 

I think the mask should be one-hot encoded, just as the author said 

> @Ji-qing If you have 35 categories, your true masks should have 35 values for each pixel (one-hot encoded), and the prediction should output 35 values between 0 and 1 for each pixel. You wouldn't have a single 'image' but 35 layers of masks.

So if you have three classes, the mask value of the three classes should be (1,0,0), (0,1,0), (0,0,1). Though I haven't tried this modification, I think it is the crux of the matter.

**Comment by ThomasLiu1021** [comment]
> @wangzhe0623 Thanks a lot. I removed Sigmoid layer and use CrossEntropyLoss. Now it reports:"RuntimeError: Dimension out of range (expected to be in range of [-1, 0], but got 1)". What the format of your mask images? I use 8-bit images with value 0,1,2 as the categorical value. But I think maybe the label should be one-hot encoding, rather than categorical value.

Hi Have you solved this issues? Or Do you know what cause this? Thanks

**Comment by greatgeekgrace** [comment]
@louxy126  请问您解决了么，我遇到同样的问题

**Comment by ZengXinyi** [comment]
Hello, I have a question. My prediction is two types. The program runs through, but the prediction result is all black. Why is this?

**Comment by WangJie8682** [comment]
> Hello, I have a question. My prediction is two types. The program runs through, but the prediction result is all black. Why is this?

i have same problem,do you solve the preblem?

**Comment by jlevy44** [comment]
I'm also getting a similar problem. I'm getting vertical lines of my predicted class across the photo. One column would be completely 1s, and another 2s. Makes the loss difficult to compute well.

**Comment by XiaoAHeng** [comment]
> @TonyDongLB 你好啊，请教下，我在尝试用这份代码做多分类（5类），直接把最后一层变成多通道。，对应true_mask我处理成了uint8单通道的图像，标签为0-4，这样处理对吗？我用了nn.CrossEntropyLoss 损失，前面还是用sigmoid层可以吗？

你好，请问如何将对应的 true_mask处理成uint8单通道的图像，标签为0-4？

**Comment by XiaoAHeng** [comment]
> Hi, thanks for your code, it works well on my own dataset.
> However, It seems like this project can only support the binary classification problem.
> when I try to modify as following:
> train.py -124 -> n_classes = 3
> this function: loss = criterion(masks_probs_flat, true_masks_flat) ---from train.py 81
> goes wrong because the shape of two parameters dismatch.
> 
> My mask image is a single 8-bit image with 4 different intensities (0,1,2,3) represent 4 classes(background,class1,class2,class3)
> how to modify the code so that it can support a multi-class problem.
> thanks advanced

Can you share the method how to modify the code so that it can support a multi-class problem?
thanks advanced

**Comment by cheng321284** [comment]
> @Ji-qing If you have 35 categories, your true masks should have 35 values for each pixel (one-hot encoded), and the prediction should output 35 values between 0 and 1 for each pixel. You wouldn't have a single 'image' but 35 layers of masks.

how can I compute the dice coefficient between the 35 laysers feature map  and the mask,the true mask is a image with pixel's gray from 0~34

**Comment by shixiaotong1101** [comment]
> @TonyDongLB 已经解决了，谢谢你哦～

你好，我想请教一下，具体多类别分割要怎么处理

**Comment by XUYUNYUN666** [comment]
> > @TonyDongLB 你好啊，请教下，我在尝试用这份代码做多分类（5类），直接把最后一层变成多通道。，对应true_mask我处理成了uint8单通道的图像，标签为0-4，这样处理对吗？我用了nn.CrossEntropyLoss 损失，前面还是用sigmoid层可以吗？
> 
> 你好，请问如何将对应的 true_mask处理成uint8单通道的图像，标签为0-4？

你好 能加个联系方式请教一下问题吗

**Comment by XiaoAHeng** [comment]
> > > @TonyDongLB 你好啊，请教下，我在尝试用这份代码做多分类（5类），直接把最后一层变成多通道。，对应true_mask我处理成了uint8单通道的图像，标签为0-4，这样处理对吗？我用了nn.CrossEntropyLoss 损失，前面还是用sigmoid层可以吗？
> > 
> > 
> > 你好，请问如何将对应的 true_mask处理成uint8单通道的图像，标签为0-4？
> 
> 你好 能加个联系方式请教一下问题

**Comment by XiaoAHeng** [comment]
> > > @TonyDongLB 你好啊，请教下，我在尝试用这份代码做多分类（5类），直接把最后一层变成多通道。，对应true_mask我处理成了uint8单通道的图像，标签为0-4，这样处理对吗？我用了nn.CrossEntropyLoss 损失，前面还是用sigmoid层可以吗？
> > 
> > 
> > 你好，请问如何将对应的 true_mask处理成uint8单通道的图像，标签为0-4？
> 
> 你好 能加个联系方式请教一下问题吗

你有什么问题

**Comment by XUYUNYUN666** [comment]
> > > > @TonyDongLB 你好啊，请教下，我在尝试用这份代码做多分类（5类），直接把最后一层变成多通道。，对应true_mask我处理成了uint8单通道的图像，标签为0-4，这样处理对吗？我用了nn.CrossEntropyLoss 损失，前面还是用sigmoid层可以吗？
> > > 
> > > 
> > > 你好，请问如何将对应的 true_mask处理成uint8单通道的图像，标签为0-4？
> > 
> > 
> > 你好 能加个联系方式请教一下问题吗
> 
> 你有什么问题

就是我的标签是灰度单通道 如何安按照他的代码  传入交叉熵函数  很多维度是有问题的 我稍微改了下  跑通了 他代码应该有几个多余的unsqueeze（）操作吧？  还有就是我测试的时候  他的测试结果可视化是直接在输出的灰度图上直接乘255吗？？？ 我测试时候报错呢 ？ 能否加您联系方式请教一下 谢谢

**Comment by BianChang** [comment]
Hi, thanks for your code, I've noticed that the current commit has taken 'multi-class' cases into consideration. 
However I have a few questions about the mask format, suppose my class number is 2(background, object1, object2), should I make my mask into a 2 layer file and each layer depicts one class and is one-hot encoded(background=0 and object=1)?

**Comment by milesial** [comment]
Hello everyone. Indeed, multiclass was made much easier with the last commits.
The loss used for multiclass is the [Cross Entropy Loss](https://pytorch.org/docs/stable/nn.html?highlight=crossentropyloss#torch.nn.CrossEntropyLoss).

https://github.com/milesial/Pytorch-UNet/blob/ebe3bbb3ca67502db407eaa8273071a871d4b744/train.py#L55-L56


So contrary to one-class, where the true mask has to be a layer of probabilities, in multiclass, the values in the true mask should be integers representing the class index.

As the PyTorch documentation describes: 

![image](https://user-images.githubusercontent.com/30204471/70714119-c5d03080-1ce7-11ea-94fe-905240e0e3af.png)

**Comment by BianChang** [comment]
Thank you~ I still have a question that if my image has class1, class2 and background,should I set n_classes to 2 or 3? I am a little confused, thank you

**Comment by milesial** [comment]
Good question. The output are fed through softmax https://github.com/milesial/Pytorch-UNet/blob/ebe3bbb3ca67502db407eaa8273071a871d4b744/predict.py#L33-L34

so if you wish to predict when there is only background, you need 3 classes.

**Comment by BianChang** [comment]
Thanks a lot! I  followed the instruction of PyTorch documentation and set the mask to be one layer and use values: 0,1,2 to represent each location's class type, but when running the code, AssertionError occurred: Network has been defined with 3 output classes, but loaded masks have 1 channels. Please check that the masks are loaded correctly.
Is this because I organized my masks incorrectly? I used matlab and each mask is a uint8 jpg

**Comment by milesial** [comment]
can you try with the last commit ? The assert shouldn't be here

**Comment by BianChang** [comment]
Yes, I tried the latest commit, and first I  got an error:
''Traceback (most recent call last):
  File "train.py", line 175, in <module>
    val_percent=args.val / 100)
  File "train.py", line 81, in train_net
    loss = criterion(masks_pred, true_masks)
  File "/home/du/anaconda3/envs/python36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/du/anaconda3/envs/python36/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 916, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "/home/du/anaconda3/envs/python36/lib/python3.6/site-packages/torch/nn/functional.py", line 2009, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/du/anaconda3/envs/python36/lib/python3.6/site-packages/torch/nn/functional.py", line 1840, in nll_loss
    ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: Expected object of scalar type Long but got scalar type Float for argument #2 'target' in call to _thnn_nll_loss2d_forward''

After I changed mask from float32 to long in train.py line 74, I got an error:
''Traceback (most recent call last):
  File "train.py", line 175, in <module>
    val_percent=args.val / 100)
  File "train.py", line 81, in train_net
    loss = criterion(masks_pred, true_masks)
  File "/home/du/anaconda3/envs/python36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/du/anaconda3/envs/python36/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 916, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "/home/du/anaconda3/envs/python36/lib/python3.6/site-packages/torch/nn/functional.py", line 2009, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/du/anaconda3/envs/python36/lib/python3.6/site-packages/torch/nn/functional.py", line 1840, in nll_loss
    ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: 1only batches of spatial targets supported (non-empty 3D tensors) but got targets of size: : [1, 1, 512, 512]''

Can you guide me through this? Thanks a lot

**Comment by BianChang** [comment]
Oh I see..if the targets contain the class indices already, we should remove the channel dimension:
which means after change 'float32' to 'long , then'add 'true_masks = true_masks.squeeze(1)' after line 74 in train.py, and then make the same adjustment in eval.py and then there will be no errors.
but when I am training my data,the loss always shows '0I' and the validation stays the same and did not change while training.....I don't know why....

**Comment by milesial** [comment]
@BianChang thank you for the feedback, I will update the code.
Regarding your issue, you may want to try to run tensorboard and observe the predictions in the 'images' tab

**Comment by XUYUNYUN666** [comment]
> @ChaoLi977 CrossEntropyLoss worked well with my code. Have you removed Sigmoid layer? And if you want to predict 3 classes you should change 'n_classes' to '3', not 2.

您好 我也是多分类 能请教你点问题吗  可以留个qq吗 非常感谢

**Comment by XUYUNYUN666** [comment]
> Thanks a lot! I followed the instruction of PyTorch documentation and set the mask to be one layer and use values: 0,1,2 to represent each location's class type, but when running the code, AssertionError occurred: Network has been defined with 3 output classes, but loaded masks have 1 channels. Please check that the masks are loaded correctly.
> Is this because I organized my masks incorrectly? I used matlab and each mask is a uint8 jpg

I have face the same error  when i change the n_classes= 2. 
如果可以 可以留个qq  一起交流一下代码  谢谢

**Comment by XUYUNYUN666** [comment]
> Hi, thanks for your code, it works well on my own dataset.
> However, It seems like this project can only support the binary classification problem.
> when I try to modify as following:
> train.py -124 -> n_classes = 3
> this function: loss = criterion(masks_probs_flat, true_masks_flat) ---from train.py 81
> goes wrong because the shape of two parameters dismatch.
> 
> My mask image is a single 8-bit image with 4 different intensities (0,1,2,3) represent 4 classes(background,class1,class2,class3)
> how to modify the code so that it can support a multi-class problem.
> thanks advanced

Can I have your qq number , I want to ask for some questions, thanks so much,

**Comment by BianChang** [comment]
> > Thanks a lot! I followed the instruction of PyTorch documentation and set the mask to be one layer and use values: 0,1,2 to represent each location's class type, but when running the code, AssertionError occurred: Network has been defined with 3 output classes, but loaded masks have 1 channels. Please check that the masks are loaded correctly.
> > Is this because I organized my masks incorrectly? I used matlab and each mask is a uint8 jpg
> 
> I have face the same error when i change the n_classes= 2.
> 如果可以 可以留个qq 一起交流一下代码 谢谢

最近一版的更新中应该已经修复了这个问题啦，您可以试一下，我的q是519388527，如果有需要可以一起讨论下代码

**Comment by ykeivn** [comment]
> @TonyDongLB 已经解决了，谢谢你哦～
您好，请问怎么处理标签数据呢，可以发给我参考下吗，多谢，邮箱ykevinhfut@163.com

**Comment by demonsan** [comment]
Should I change my true_mask from 1 channel to 4 channels( 4 classes) one-hot mask ? Since the output of the model is 4 channels, I think the true_mask should be four channels too so that it can calculate crossentropy on each channel each pixel.

**Comment by milesial** [comment]
@demonsan PyTorch does the work for you, don't worry https://pytorch.org/docs/stable/nn.html#crossentropyloss

**Comment by picEmily** [comment]
I have three classes. The training mask is assigned in 0,1,2 gray scale. The training image is also gray-scale image。
I got following error：
RuntimeError: 1only batches of spatial targets supported (non-empty 3D tensors) but got targets of size: : [1, 1, 576, 448]

**Comment by wjj001-dl** [comment]
> @TonyDongLB已经解决了，谢谢你哦〜

你好，我也是多分类，可否告诉我你是咋做的，我的微信是w1203600129，非常感谢

**Comment by matrixgame2018** [comment]
你好，我也是多分类，可否告诉我你是咋做的，我的微信是mz18026806328，非常感谢

**Comment by Chao86** [comment]
> 你好，我也是多分类，可否告诉我你是咋做的，我的微信是mz18026806328，非常感谢

如果有n个目标要分割，最后输出的通道图就是n+1个

**Comment by lucafei** [comment]
请问一下我是2各类分割加一个background， mask里的值是0,1,2. 那我train.py 里的num_classes是取1还是2

**Comment by wangfusheng-cqu** [comment]
> @zhouzhubin 两类的话，对饮的像素值应该是0和1，如果你用cross entropy损失的话，预测的类别数写成2，用作者代码中写的那个loss，类别数写1.

你好！能告诉我一下怎么做吗？？

**Comment by wangfusheng-cqu** [comment]
> > 你好，我也是多分类，可否告诉我你是咋做的，我的微信是mz18026806328，非常感谢
> 
> 如果有n个目标要分割，最后输出的通道图就是n+1个

你好！能分享一下修改的部分吗？？？

**Comment by wangfusheng-cqu** [comment]
> I already fix this problem, you can just change the final layer from 1 channel to 4, and using a CrossEntropyLoss for 2D, but I don't know this model wether perform well in your project.
> 你可以直接把最后一层变为多通道的，之后修改损失函数，用交叉熵2D或者focal loss2D均可，但是不知道在多种类预测时候模型是否表现的好。
> and thank for the code again.

你好！能分享一下多分类的代码吗？？

**Comment by jie666-6** [comment]
Hi, there. For this multiclass issue, I still have a question. Now I have 3 classes and the UNET predicts results are [1, 3, 128, 128]. But the true mask is [1, 1, 128, 128]. So I would like to ask where should I add one line to change the one-hot result into single channel category data, i.e. [1, 1, 128, 128]? Could some one help?

**Comment by matrixgame2018** [comment]
I think use the loss function such as FwIOU can help you&nbsp;



发自我的iPhone


------------------ Original ------------------

**Comment by wangfusheng-cqu** [comment]
> Hi, there. For this multiclass issue, I still have a question. Now I have 3 classes and the UNET predicts results are [1, 3, 128, 128]. But the true mask is [1, 1, 128, 128]. So I would like to ask where should I add one line to change the one-hot result into single channel category data, i.e. [1, 1, 128, 128]? Could some one help?
> 
> Here I change loss = criterion(masks_pred, true_masks) to loss = criterion(masks_pred, true_masks.squeeze(dim=1)) and now it works for the training part, validation part should also be modified in this way.

https://github.com/zonasw/unet-nested-multiple-classification      the code can segmentatiion for multiple-classification

**Comment by picEmily** [comment]
> > Hi, there. For this multiclass issue, I still have a question. Now I have 3 classes and the UNET predicts results are [1, 3, 128, 128]. But the true mask is [1, 1, 128, 128]. So I would like to ask where should I add one line to change the one-hot result into single channel category data, i.e. [1, 1, 128, 128]? Could some one help?
> > Here I change loss = criterion(masks_pred, true_masks) to loss = criterion(masks_pred, true_masks.squeeze(dim=1)) and now it works for the training part, validation part should also be modified in this way.
> 
> https://github.com/zonasw/unet-nested-multiple-classification the code can segmentatiion for multiple-classification

其实，最后[1, 3, 128, 128]表示的是图像中，每个像素位置上的3中类别的概率，你可以用numpy的argmax方法，得到每个像素位置对应概率最大的类别，最后就能转换为 [1, 1, 128, 128]这样的mask，mask的元素为0,1,2这样的。

**Comment by jie666-6** [comment]
> > > Hi, there. For this multiclass issue, I still have a question. Now I have 3 classes and the UNET predicts results are [1, 3, 128, 128]. But the true mask is [1, 1, 128, 128]. So I would like to ask where should I add one line to change the one-hot result into single channel category data, i.e. [1, 1, 128, 128]? Could some one help?
> > > Here I change loss = criterion(masks_pred, true_masks) to loss = criterion(masks_pred, true_masks.squeeze(dim=1)) and now it works for the training part, validation part should also be modified in this way.
> > 
> > 
> > https://github.com/zonasw/unet-nested-multiple-classification the code can segmentatiion for multiple-classification
> 
> 其实，最后[1, 3, 128, 128]表示的是图像中，每个像素位置上的3中类别的概率，你可以用numpy的argmax方法，得到每个像素位置对应概率最大的类别，最后就能转换为 [1, 1, 128, 128]这样的mask，mask的元素为0,1,2这样的。

谢谢！

**Comment by jie666-6** [comment]
> > Hi, there. For this multiclass issue, I still have a question. Now I have 3 classes and the UNET predicts results are [1, 3, 128, 128]. But the true mask is [1, 1, 128, 128]. So I would like to ask where should I add one line to change the one-hot result into single channel category data, i.e. [1, 1, 128, 128]? Could some one help?
> > Here I change loss = criterion(masks_pred, true_masks) to loss = criterion(masks_pred, true_masks.squeeze(dim=1)) and now it works for the training part, validation part should also be modified in this way.
> 
> https://github.com/zonasw/unet-nested-multiple-classification the code can segmentatiion for multiple-classification

Thanks

**Comment by milesial** [comment]
Closing, as this issue is now outdated after the recent code refactor.
