### ISSUE TITLE
failed to run predict.py (using google colab)

### ISSUE THREAD

**Issue by paras-jain** [milesial/Pytorch-UNet#152]
Hello, I have all the dependencies and the pretrained model ```MODEL.pth``` present but after repeated trials, I keep getting the same error.
Any help would be really appreciated.

```
Traceback (most recent call last):
  File "predict.py", line 112, in <module>
    net.load_state_dict(torch.load(args.model, map_location=device))
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 692, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x0a'.
```

**Comment by milesial** [comment]
The pretrained model hasn't been available for a while on the repo. Did you get it from an earlier commit? Since then, the network architecture has changed. You should checkout the commit where you got the weights from.

**Comment by paras-jain** [comment]
I downloaded it from [here](https://github.com/milesial/Pytorch-UNet/blob/e2e46ce509382a45b1db4e1f639aeed568f6cb3e/MODEL.pth).

**Comment by milesial** [comment]
Then you have to checkout commit e2e46ce. But be careful, it is old and full of bugs.
