### ISSUE TITLE
Tensorboad writer cannot write histogram

### ISSUE THREAD

**Issue by lingchen1991** [milesial/Pytorch-UNet#153]
Traceback (most recent call last):
  File "train.py", line 361, in <module>
    val_percent=args.val / 100)
  File "train.py", line 253, in train_net
    writer.add_histogram('grads/' + tag, value.grad.data.cpu().numpy(), global_step)
AttributeError: 'NoneType' object has no attribute 'data'

**Comment by milesial** [comment]
What version of PyTorch are you using ?

**Comment by lingchen1991** [comment]
> What version of PyTorch are you using ?

1.3.1.

It's my fault that I forgot to delete the layers that I dont use.

Thanks for your reply.
