### ISSUE TITLE
how to train on my database?

### ISSUE THREAD

**Issue by manvirvirk** [milesial/Pytorch-UNet#154]

**Comment by milesial** [comment]
Please detail your problem when you open an issue, else I can't help you

**Comment by manvirvirk** [comment]
@milesial  what should be the dataset dierctory? I have database of 20 rgb images and respective masks on which i want to train this model. In which folder i should place my data??? Thanks

**Comment by milesial** [comment]
https://github.com/milesial/Pytorch-UNet/tree/master/data
