### ISSUE TITLE
ValueError: The histogram is empty, please file a bug report.

### ISSUE THREAD

**Issue by manvirvirk** [milesial/Pytorch-UNet#157]
Can anyone solve this?

File "C:\Users\virkt\Anaconda3\envs\unet\lib\site-packages\torch\utils\tensorboard\summary.py", line 288, in make_histogram
    raise ValueError('The histogram is empty, please file a bug report.')
ValueError: The histogram is empty, please file a bug report.

**Comment by milesial** [comment]
Can you tell me which tensor is empty ? The weights or the gradients ?

**Comment by manvirvirk** [comment]
WEIGHTS

**Comment by manvirvirk** [comment]
File "C:\Users\virkt\Anaconda3\envs\unet\lib\site-packages\torch\utils\tensorboard\summary.py", line 288, in make_histogram
    raise ValueError('The histogram is empty, please file a bug report.')
ValueError: The histogram is empty, please file a bug report.

**Comment by milesial** [comment]
Can you tell me for what parameter tag this happens, and if you made changes to the network?

**Comment by manvirvirk** [comment]
no i did not make any changes. i m training it on my database. it contains 20 images and 20 masks

**Comment by milesial** [comment]
And what is the parameter tag that causes problem? Does it raise the exception for the first one?
https://github.com/milesial/Pytorch-UNet/blob/7afb4b25ba5be0da8177ff3f49a8262a3e5f7498/train.py#L93

**Comment by manvirvirk** [comment]
for tag, value in net.named_parameters():
                        tag = tag.replace('.', '/')
                        writer.add_histogram('weights/' + tag, value.data.cpu().numpy(), global_step)
                        writer.add_histogram('grads/' + tag, value.grad.data.cpu().numpy(), global_step)

**Comment by manvirvirk** [comment]
yes

**Comment by milesial** [comment]
Please debug this part of the code or add a print statement and tell me the value of the tag variable

**Comment by manvirvirk** [comment]
please tell how to do that as i m beginner. Thanks for helping long way

**Comment by milesial** [comment]
You do not know how to print variables in python? you might want to follow a python tutorial before jumping into DL

**Comment by manvirvirk** [comment]
i know how to print variables . But i did not get this problem

**Comment by milesial** [comment]
I'm closing this issue as I predict we won't get very far. You can comment the tensorboard logic if you don't care about it.

**Comment by feihaochen** [comment]
I saw nothing but  fighting above. So can anyone provide an answer to this question?

**Comment by Yu-zhengbo** [comment]
May the loss is nan ,then back propagation is false . I meet this question just now, and  I find out that loss is nan, so "The histogram is empty, please file a bug report."
