### ISSUE TITLE
it takes 10s to inference a 1080p image?

### ISSUE THREAD

**Issue by jack17951** [milesial/Pytorch-UNet#158]
Is it normal?I traind a model size of 51.1MB.When i use it to inference an 1080p image by gpu, it takes 1 secend,by cpu it takes 10 secends.

**Comment by milesial** [comment]
Yes it makes sense. For me it takes .3s for a 440p image so 1s for a 1080p is reasonable (GPU). I don't advise using the CPU for this

**Comment by jack17951** [comment]
> Yes it makes sense. For me it takes .3s for a 440p image so 1s for a 1080p is reasonable (GPU). I don't advise using the CPU for this

thank you
