### ISSUE TITLE
when the upsample method is bilinear, the out channels is not the passed in

### ISSUE THREAD

**Issue by somehower** [milesial/Pytorch-UNet#159]
https://github.com/milesial/Pytorch-UNet/blob/7afb4b25ba5be0da8177ff3f49a8262a3e5f7498/unet/unet_parts.py#L51

when the upsample method is bilinear, the out channels will be out_channels // 2, not the passed in parameter "out_channels".

when we print(net), we can see up1 moduels out_channels is 256, not the  512 passed in .
```
(up1): Up(
    (up): Upsample(scale_factor=2.0, mode=bilinear)
    (conv): DoubleConv(
      (double_conv): Sequential(
        (0): Conv2d(1024, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): ReLU(inplace=True)
        (3): Conv2d(512, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (4): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (5): ReLU(inplace=True)
      )
    )
  )
```
when the upsample method is ConvTranspose2d, the out_channels channel is the actual parameter passed in.

**Comment by milesial** [comment]
Yes this is expected as in the bilinear case, the double conv has to halve the channels because there is no upconv to do so.

#69 #146 #90

**Comment by somehower** [comment]
I have a suggestion
```
self.up1 = Up(1024, 512, bilinear)
self.up2 = Up(512, 256, bilinear)
self.up3 = Up(256, 128, bilinear)
```
modifyed to
```
self.up1 = Up(1024, 512 // factor, bilinear)
self.up2 = Up(512, 256 // factor, bilinear)
self.up3 = Up(256, 128 // factor, bilinear)
```
and 
```
self.conv = DoubleConv(in_channels, out_channels // 2, in_channels // 2)
```
modifed to
```
self.conv = DoubleConv(in_channels, out_channels, in_channels // 2)
```

Whether it can reduce confusion？

**Comment by milesial** [comment]
Sounds good! If the code still runs with bilinear on and off, please open a PR and I'll merge it
