### ISSUE TITLE
 No module named 'torch._C'

### ISSUE THREAD

**Issue by TARO0418** [milesial/Pytorch-UNet#162]

**Comment by milesial** [comment]
https://github.com/pytorch/pytorch/issues/574 ?

**Comment by TARO0418** [comment]
Thanks for your reply！It may be a problem with my Ptorch.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"milesial"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月19日(星期天) 凌晨2:17
收件人:&nbsp;"milesial/Pytorch-UNet"<Pytorch-UNet@noreply.github.com&gt;;
抄送:&nbsp;"郭全"<2088517585@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [milesial/Pytorch-UNet]  No module named 'torch._C' (#162)





 
pytorch/pytorch#574 ?
