### ISSUE TITLE
.PTH file missing

### ISSUE THREAD

**Issue by aayushk614** [milesial/Pytorch-UNet#163]
Could you please provide the .PTH file as well. Its a bit difficult to train the model for me as i don't have the required resources.

**Comment by milesial** [comment]
The model is quite easy to train, you could just use a free colab instance or spin up a quick AWS. Model checkpointing is built in the training script.

**Comment by Nikronic** [comment]
@aayushk614 see this issue https://github.com/milesial/Pytorch-UNet/issues/189#issuecomment-653772197
