### ISSUE TITLE
diffX and diffY is a tensor

### ISSUE THREAD

**Issue by HansBambel** [milesial/Pytorch-UNet#166]
Hey!
Thanks for the repo! It's really useful and is working straight out of the box.

I noticed that the variables `diffX` and `diffY` are cast to tensors in the forward method of `Up(nn.Module)`. 
Why not do it like this:
```
diffY = x2.size()[2] - x1.size()[2]
diffX = x2.size()[3] - x1.size()[3]
```
This way the `F.pad` method does not complain about it expecting ints, but getting tensors. Furthermore, this enables the whole UNet model to be scripted with Torchscript (which did not increase speed for me at all).

**Comment by milesial** [comment]
Hi! I think when I wrote this code the pad function wanted tensors. If all still works with your version, feel free to open a PR :)

**Comment by HansBambel** [comment]
Great, done :)
