### ISSUE TITLE
About n_classes question.

### ISSUE THREAD

**Issue by ROOKLO** [milesial/Pytorch-UNet#177]
line 154-155 of code 'train.py' both indicate that n_classes = 1.     
if I get background and one class why not 'n_classes=2', and 'n_classes =3' when I have 2 classes

**Comment by milesial** [comment]
n_classes=1 and n_classes=2 are equivalent, one uses sigmoid and the other uses softmax. If you have 2 classes+background, use n_classes=3, and if you have 2 classes and no background, use n_classes=2.
Is that clear?

**Comment by WangHeHehehehe** [comment]
![图片](https://user-images.githubusercontent.com/58463086/82778351-bf8fd400-9e83-11ea-85b2-a2150c2de778.png)
I have a question about the “mode”，why classes = 1，“mode = max” classes >1 ,"mode  = min"?
Looking forward to your reply! Thank u so much!

**Comment by milesial** [comment]
For 1 classes, the DICE loss is used for evaluation, which has to be maximized. Otherwise the evaluation loss is used, which has to be minimized

**Comment by WangHeHehehehe** [comment]
> 
> 
> For 1 class, the DICE loss is used for evaluation, which has to be maximized. Otherwise the evaluation loss is used, which has to be minimized
Ok, I got it,thank u!

**Comment by yiliu-coding** [comment]
Hi, I got problems when n_classes >= 3.  The runtime error looks like this

I0529 02:25:20.773882 140203145201472 <ipython-input-8-be17453f3d50>:9] Using device cuda
I0529 02:25:20.956177 140203145201472 <ipython-input-8-be17453f3d50>:18] Network:
	1 input channels
	8 output channels (classes)
	Bilinear upscaling
Namespace(batchsize=1, epochs=100, load='False', lr=0.05, scale=0.5, val=10.0)
I0529 02:25:20.974926 140203145201472 dataset.py:20] Creating dataset with 790 examples
I0529 02:25:20.980705 140203145201472 <ipython-input-6-287d723408b3>:29] Starting training:
        Epochs:          100
        Batch size:      1
        Learning rate:   0.05
        Training size:   711
        Validation size: 79
        Checkpoints:     True
        Device:          cuda
        Images scaling:  0.5
    
Epoch 1/100:   0%|          | 0/711 [00:00<?, ?img/s]
torch.Size([1, 8, 128, 128]) torch.Size([1, 1, 128, 128])

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-8-be17453f3d50> in <module>
     38                   device=device,
     39                   img_scale=args.scale,
---> 40                   val_percent=args.val / 100)
     41     except KeyboardInterrupt:
     42         torch.save(net.state_dict(), 'INTERRUPTED.pth')

<ipython-input-6-287d723408b3> in train_net(net, device, epochs, batch_size, lr, val_percent, save_cp, img_scale)
     75                 print(np.shape(masks_softmax),np.shape(true_masks))
     76 
---> 77                 loss = criterion(masks_softmax, true_masks)
     78 
     79                 epoch_loss += loss.item()

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    539             result = self._slow_forward(*input, **kwargs)
    540         else:
--> 541             result = self.forward(*input, **kwargs)
    542         for hook in self._forward_hooks.values():
    543             hook_result = hook(self, input, result)

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py in forward(self, input, target)
    914     def forward(self, input, target):
    915         return F.cross_entropy(input, target, weight=self.weight,
--> 916                                ignore_index=self.ignore_index, reduction=self.reduction)
    917 
    918 

/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py in cross_entropy(input, target, weight, size_average, ignore_index, reduce, reduction)
   2007     if size_average is not None or reduce is not None:
   2008         reduction = _Reduction.legacy_get_string(size_average, reduce)
-> 2009     return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
   2010 
   2011 

/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py in nll_loss(input, target, weight, size_average, ignore_index, reduce, reduction)
   1838         ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
   1839     elif dim == 4:
-> 1840         ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
   1841     else:
   1842         # dim == 3 or dim > 4

RuntimeError: 1only batches of spatial targets supported (non-empty 3D tensors) but got targets of size: : [1, 1, 128, 128]

**Comment by yiliu-coding** [comment]
> Hi, I got problems when n_classes >= 3. The runtime error looks like this
> 
> I0529 02:25:20.773882 140203145201472 :9] Using device cuda
> I0529 02:25:20.956177 140203145201472 :18] Network:
> 1 input channels
> 8 output channels (classes)
> Bilinear upscaling
> Namespace(batchsize=1, epochs=100, load='False', lr=0.05, scale=0.5, val=10.0)
> I0529 02:25:20.974926 140203145201472 dataset.py:20] Creating dataset with 790 examples
> I0529 02:25:20.980705 140203145201472 :29] Starting training:
> Epochs: 100
> Batch size: 1
> Learning rate: 0.05
> Training size: 711
> Validation size: 79
> Checkpoints: True
> Device: cuda
> Images scaling: 0.5
> 
> Epoch 1/100: 0%| | 0/711 [00:00<?, ?img/s]
> torch.Size([1, 8, 128, 128]) torch.Size([1, 1, 128, 128])
> 
> RuntimeError Traceback (most recent call last)
> in
> 38 device=device,
> 39 img_scale=args.scale,
> ---> 40 val_percent=args.val / 100)
> 41 except KeyboardInterrupt:
> 42 torch.save(net.state_dict(), 'INTERRUPTED.pth')
> 
> in train_net(net, device, epochs, batch_size, lr, val_percent, save_cp, img_scale)
> 75 print(np.shape(masks_softmax),np.shape(true_masks))
> 76
> ---> 77 loss = criterion(masks_softmax, true_masks)
> 78
> 79 epoch_loss += loss.item()
> 
> /usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in **call**(self, *input, **kwargs)
> 539 result = self._slow_forward(*input, **kwargs)
> 540 else:
> --> 541 result = self.forward(*input, **kwargs)
> 542 for hook in self._forward_hooks.values():
> 543 hook_result = hook(self, input, result)
> 
> /usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py in forward(self, input, target)
> 914 def forward(self, input, target):
> 915 return F.cross_entropy(input, target, weight=self.weight,
> --> 916 ignore_index=self.ignore_index, reduction=self.reduction)
> 917
> 918
> 
> /usr/local/lib/python3.6/dist-packages/torch/nn/functional.py in cross_entropy(input, target, weight, size_average, ignore_index, reduce, reduction)
> 2007 if size_average is not None or reduce is not None:
> 2008 reduction = _Reduction.legacy_get_string(size_average, reduce)
> -> 2009 return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
> 2010
> 2011
> 
> /usr/local/lib/python3.6/dist-packages/torch/nn/functional.py in nll_loss(input, target, weight, size_average, ignore_index, reduce, reduction)
> 1838 ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
> 1839 elif dim == 4:
> -> 1840 ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
> 1841 else:
> 1842 # dim == 3 or dim > 4
> 
> RuntimeError: 1only batches of spatial targets supported (non-empty 3D tensors) but got targets of size: : [1, 1, 128, 128]

I have got this problem as well, it proves to be the code is not perfect for multi-class tasks. Check 
https://pytorch.org/docs/master/generated/torch.nn.CrossEntropyLoss.html
https://discuss.pytorch.org/t/details-of-torch-nn-crossentropyloss/13679/6
Even though this problem is solved, this implemented unet is not converging as expected for multi-class tasks.

**Comment by Forest-Xie** [comment]
> > Hi, I got problems when n_classes >= 3. The runtime error looks like this
> > I0529 02:25:20.773882 140203145201472 :9] Using device cuda
> > I0529 02:25:20.956177 140203145201472 :18] Network:
> > 1 input channels
> > 8 output channels (classes)
> > Bilinear upscaling
> > Namespace(batchsize=1, epochs=100, load='False', lr=0.05, scale=0.5, val=10.0)
> > I0529 02:25:20.974926 140203145201472 dataset.py:20] Creating dataset with 790 examples
> > I0529 02:25:20.980705 140203145201472 :29] Starting training:
> > Epochs: 100
> > Batch size: 1
> > Learning rate: 0.05
> > Training size: 711
> > Validation size: 79
> > Checkpoints: True
> > Device: cuda
> > Images scaling: 0.5
> > Epoch 1/100: 0%| | 0/711 [00:00<?, ?img/s]
> > torch.Size([1, 8, 128, 128]) torch.Size([1, 1, 128, 128])
> > RuntimeError Traceback (most recent call last)
> > in
> > 38 device=device,
> > 39 img_scale=args.scale,
> > ---> 40 val_percent=args.val / 100)
> > 41 except KeyboardInterrupt:
> > 42 torch.save(net.state_dict(), 'INTERRUPTED.pth')
> > in train_net(net, device, epochs, batch_size, lr, val_percent, save_cp, img_scale)
> > 75 print(np.shape(masks_softmax),np.shape(true_masks))
> > 76
> > ---> 77 loss = criterion(masks_softmax, true_masks)
> > 78
> > 79 epoch_loss += loss.item()
> > /usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in **call**(self, *input, **kwargs)
> > 539 result = self._slow_forward(*input, **kwargs)
> > 540 else:
> > --> 541 result = self.forward(*input, **kwargs)
> > 542 for hook in self._forward_hooks.values():
> > 543 hook_result = hook(self, input, result)
> > /usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py in forward(self, input, target)
> > 914 def forward(self, input, target):
> > 915 return F.cross_entropy(input, target, weight=self.weight,
> > --> 916 ignore_index=self.ignore_index, reduction=self.reduction)
> > 917
> > 918
> > /usr/local/lib/python3.6/dist-packages/torch/nn/functional.py in cross_entropy(input, target, weight, size_average, ignore_index, reduce, reduction)
> > 2007 if size_average is not None or reduce is not None:
> > 2008 reduction = _Reduction.legacy_get_string(size_average, reduce)
> > -> 2009 return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
> > 2010
> > 2011
> > /usr/local/lib/python3.6/dist-packages/torch/nn/functional.py in nll_loss(input, target, weight, size_average, ignore_index, reduce, reduction)
> > 1838 ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
> > 1839 elif dim == 4:
> > -> 1840 ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
> > 1841 else:
> > 1842 # dim == 3 or dim > 4
> > RuntimeError: 1only batches of spatial targets supported (non-empty 3D tensors) but got targets of size: : [1, 1, 128, 128]
> 
> I have got this problem as well, it proves to be the code is not perfect for multi-class tasks. Check
> https://pytorch.org/docs/master/generated/torch.nn.CrossEntropyLoss.html
> https://discuss.pytorch.org/t/details-of-torch-nn-crossentropyloss/13679/6
> Even though this problem is solved, this implemented unet is not converging as expected for multi-class tasks.

Hi, I am curious about what you said about "not converging as expected for multi-class tasks", can you describe it in detail? I have some trouble with my multi-class segmentation task about not converging. Look forward to your reply. Thanks.

**Comment by yiliu-coding** [comment]
> > > Hi, I got problems when n_classes >= 3. The runtime error looks like this
> > > I0529 02:25:20.773882 140203145201472 :9] Using device cuda
> > > I0529 02:25:20.956177 140203145201472 :18] Network:
> > > 1 input channels
> > > 8 output channels (classes)
> > > Bilinear upscaling
> > > Namespace(batchsize=1, epochs=100, load='False', lr=0.05, scale=0.5, val=10.0)
> > > I0529 02:25:20.974926 140203145201472 dataset.py:20] Creating dataset with 790 examples
> > > I0529 02:25:20.980705 140203145201472 :29] Starting training:
> > > Epochs: 100
> > > Batch size: 1
> > > Learning rate: 0.05
> > > Training size: 711
> > > Validation size: 79
> > > Checkpoints: True
> > > Device: cuda
> > > Images scaling: 0.5
> > > Epoch 1/100: 0%| | 0/711 [00:00<?, ?img/s]
> > > torch.Size([1, 8, 128, 128]) torch.Size([1, 1, 128, 128])
> > > RuntimeError Traceback (most recent call last)
> > > in
> > > 38 device=device,
> > > 39 img_scale=args.scale,
> > > ---> 40 val_percent=args.val / 100)
> > > 41 except KeyboardInterrupt:
> > > 42 torch.save(net.state_dict(), 'INTERRUPTED.pth')
> > > in train_net(net, device, epochs, batch_size, lr, val_percent, save_cp, img_scale)
> > > 75 print(np.shape(masks_softmax),np.shape(true_masks))
> > > 76
> > > ---> 77 loss = criterion(masks_softmax, true_masks)
> > > 78
> > > 79 epoch_loss += loss.item()
> > > /usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in **call**(self, *input, **kwargs)
> > > 539 result = self._slow_forward(*input, **kwargs)
> > > 540 else:
> > > --> 541 result = self.forward(*input, **kwargs)
> > > 542 for hook in self._forward_hooks.values():
> > > 543 hook_result = hook(self, input, result)
> > > /usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py in forward(self, input, target)
> > > 914 def forward(self, input, target):
> > > 915 return F.cross_entropy(input, target, weight=self.weight,
> > > --> 916 ignore_index=self.ignore_index, reduction=self.reduction)
> > > 917
> > > 918
> > > /usr/local/lib/python3.6/dist-packages/torch/nn/functional.py in cross_entropy(input, target, weight, size_average, ignore_index, reduce, reduction)
> > > 2007 if size_average is not None or reduce is not None:
> > > 2008 reduction = _Reduction.legacy_get_string(size_average, reduce)
> > > -> 2009 return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
> > > 2010
> > > 2011
> > > /usr/local/lib/python3.6/dist-packages/torch/nn/functional.py in nll_loss(input, target, weight, size_average, ignore_index, reduce, reduction)
> > > 1838 ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
> > > 1839 elif dim == 4:
> > > -> 1840 ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
> > > 1841 else:
> > > 1842 # dim == 3 or dim > 4
> > > RuntimeError: 1only batches of spatial targets supported (non-empty 3D tensors) but got targets of size: : [1, 1, 128, 128]
> > 
> > 
> > I have got this problem as well, it proves to be the code is not perfect for multi-class tasks. Check
> > https://pytorch.org/docs/master/generated/torch.nn.CrossEntropyLoss.html
> > https://discuss.pytorch.org/t/details-of-torch-nn-crossentropyloss/13679/6
> > Even though this problem is solved, this implemented unet is not converging as expected for multi-class tasks.
> 
> Hi, I am curious about what you said about "not converging as expected for multi-class tasks", can you describe it in detail? I have some trouble with my multi-class segmentation task about not converging. Look forward to your reply. Thanks.

Hi, glad to hear from you. I'm now still working on the code to see how to solve this problem. In my case, it's one-band image (intensity 0-60000+) and the mask data is incomplete. I am trying different normalizing methods for the data and also replaced cross-entropy loss with focal loss. It would be great if you have any suggestions.

**Comment by Forest-Xie** [comment]
@yiliu-coding Thanks for your reply. Actually, I'm also try to sove the converge problem, while my dataset is pascal voc 2012. I am checking my gradient in training process, and I may check data-load code to confirm whther load mask correctly. Then I may check the prediction of the network to make sure the network performance. If I get some breakthrough， I will tell you.
