### ISSUE TITLE
Syntax Error 

### ISSUE THREAD

**Issue by LiquidAmmonia** [milesial/Pytorch-UNet#178]
Great work!

when I tried to run 'train.py', there is a syntax error as follows:

File "train.py", line 40
    writer = SummaryWriter(comment=f'LR_{lr}_BS_{batch_size}_SCALE_{img_scale}')
                                                                                                                                 ^
SyntaxError: invalid syntax

I didn't change anything in your code, and syntax errors occur even without compiling and running. Could you tell me what is wrong?

**Comment by milesial** [comment]
make sure you are on Python 3.6 or newer for f-strings

**Comment by LiquidAmmonia** [comment]
Got it! I was on Python 3.5, so I think that maybe it. 
Thank you for your time! It would be great if you update this info to your readme file, the current version just say python3, which maybe a bit ambiguous.
