### ISSUE TITLE
"model.pkl" is not found

### ISSUE THREAD

**Issue by Zhanghahah** [milesial/Pytorch-UNet#179]
Hi when i conduct this: python predict.py -i image.jpg -o output.jpg, there will be a mistake, "no MODEL.pth". Can you explain why?

Thanks !

**Comment by milesial** [comment]
Where and how have you saved your trained model?

**Comment by Nelson-Gon** [comment]
I see where the confusion arises. I think the order of the `README` should be changed. Currently, one might assume that `predict.py` can be used out of the box. In reality however, one ought to train and save a model first which is why this error occurs. I assume OP ran `predict.py` first.

**Comment by milesial** [comment]
You're right, the README was redacted when there was a pretrained model in the repo. Added a clarification in the README https://github.com/milesial/Pytorch-UNet/commit/02644ec8e673f54006c8cc1523610e149e84ceb5
