### ISSUE TITLE
Output mask dimension mismatch

### ISSUE THREAD

**Issue by pcicales** [milesial/Pytorch-UNet#182]
I am still debugging this issue so I will report back here but wanted to check if anyone else had this problem. It seems that the output mask is sometimes slightly larger than the original mask. When I superimpose the images, I am unsure if its to scale for this reason. Here is a sample:
![Screenshot from 2020-05-27 09-58-54](https://user-images.githubusercontent.com/9851953/83037069-f93a1980-a000-11ea-96aa-340313190a13.png)

**Comment by milesial** [comment]
Is this related to #114 ?

**Comment by pcicales** [comment]
Yes it is, thank you so much, I didn't see it.
