### ISSUE TITLE
Question about submit.py and predict.py results

### ISSUE THREAD

**Issue by WangHeHehehehe** [milesial/Pytorch-UNet#183]
I use  the same epoch10.pth to test, however the predict.py results better than submit results,Can you tell me the reason,thanks!
![图片](https://user-images.githubusercontent.com/58463086/83120820-1efc1700-a104-11ea-9c61-4771be365b5c.png) ( submit result)

![图片](https://user-images.githubusercontent.com/58463086/83121322-bbbeb480-a104-11ea-8ab3-cd8e9565582c.png) (predict result)

![图片](https://user-images.githubusercontent.com/58463086/83121221-992c9b80-a104-11ea-9ca1-959018fd0143.png) (mask)

**Comment by milesial** [comment]
What do you mean by "submit result" ?

**Comment by WangHeHehehehe** [comment]
> 
> 
> What do you mean by "submit result" ?

![图片](https://user-images.githubusercontent.com/58463086/83217484-764ec580-a19e-11ea-9887-3d664f010d46.png

**Comment by milesial** [comment]
Both predict.py and submit.py use the same function `predict` from predict.py. Make sure the parameters passed are the same (for example the threshold).
Are you showing the image before the RLE encoding?
