### ISSUE TITLE
Hello how can I train your model with just one channel image(black and white)

### ISSUE THREAD

**Issue by SWKoreaBME** [milesial/Pytorch-UNet#19]
Hello 
Thanks for your contribution for making awesome network with pytorch.
I am newbie in this and I have a problem with training this model with one channel image (black and white)
not 3 channels image(RGB)
How can I modify your network to train and test???

Thanks

**Comment by milesial** [comment]
Hello,
You do not have to modify the network, you can modify the loading to make sure the image is RGB. I use PIL to load the images, so you can convert the image to RGB after loading it.

Add the line `im = im.convert('RGB')` after this line https://github.com/milesial/Pytorch-UNet/blob/b282e761f04904697418c9e759d761004a045428/utils/load.py#L44 and all should work fine for the training.

For predicting, add `img = img.convert('RGB')` after the line https://github.com/milesial/Pytorch-UNet/blob/b282e761f04904697418c9e759d761004a045428/predict.py#L145

Reference for PIL Image module : http://effbot.org/imagingbook/image.htm

**Comment by SWKoreaBME** [comment]
Thanks!:) it really helped, before adding the line which converts image to RGB, 
predict.py shows the error but now it works fine for prediction. 

But another error occur when running train.py

Traceback (most recent call last):
  File "train.py", line 140, in <module>
    img_scale=args.scale)
  File "train.py", line 64, in train_net
    for i, b in enumerate(batch(train, batch_size)):
  File "/home/ccids-sw/sangwook/segmentation/Pytorch-UNet/utils/utils.py", line 37, in batch
    for i, t in enumerate(iterable):
  File "/home/ccids-sw/sangwook/segmentation/Pytorch-UNet/utils/utils.py", line 17, in hwc_to_chw
    return np.transpose(img, axes=[2, 0, 1])
  File "/home/ccids-sw/anaconda3/envs/testenv/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 575, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "/home/ccids-sw/anaconda3/envs/testenv/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 52, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: axes don't match array

it says "axes don't match array" how can i solve it??
Thanks a lot, hopefully this is the last question

**Comment by milesial** [comment]
The problem is at this line: 
https://github.com/milesial/Pytorch-UNet/blob/23e817310461f79888078a2a1ab4b2187a97dc88/utils/load.py#L32

`to_cropped_imgs` loads your images as B&W, but they should be RGB for the next function to succeed.
I would add a line after this to modify each image in the `imgs` array, via the `map` function. At this point, images are numpy arrays of shape H x W for you, and they need to be H x W x C. To do this, I would use a lambda function that use [np.stack](https://docs.scipy.org/doc/numpy/reference/generated/numpy.stack.html) on each image, with the right axis, because a B&W image has all three R, G and B equal.

**Comment by TonyDongLB** [comment]
hello, well I modified your code to predict in gray image too, but I just change the model like this `net = UNet(n_channels=1, n_classes=1)` and `data = Image.open(img_path); data = data.convert('L')`, and the code run as usual, but I got a bad result, I got nothing when predict, I don't know what' wrong, maybe the epochs is 5 not enough?

**Comment by karlita101** [comment]
> The problem is at this line:
> https://github.com/milesial/Pytorch-UNet/blob/23e817310461f79888078a2a1ab4b2187a97dc88/utils/load.py#L32
> 
> `to_cropped_imgs` loads your images as B&W, but they should be RGB for the next function to succeed.
> I would add a line after this to modify each image in the `imgs` array, via the `map` function. At this point, images are numpy arrays of shape H x W for you, and they need to be H x W x C. To do this, I would use a lambda function that use [np.stack](https://docs.scipy.org/doc/numpy/reference/generated/numpy.stack.html) on each image, with the right axis, because a B&W image has all three R, G and B equal.
> 
> Maybe
> `imgs = map(lambda i: np.stack([i, i, i], axis=-1), imgs)` or something like that.

Would you be able to provide some guidance on how to modify the code for RGBA? 
Whne you say that images must be RGB does that mean that a 4th channel is not supported?
