### ISSUE TITLE
I have some questions

### ISSUE THREAD

**Issue by Lee-h96** [milesial/Pytorch-UNet#191]
I had this problem running predictions
usage: predict.py [-h] [--model FILE] --input INPUT [INPUT ...]
                  [--output INPUT [INPUT ...]] [--viz] [--no-save]
                  [--mask-threshold MASK_THRESHOLD] [--scale SCALE]
predict.py: error: the following arguments are required: --input/-i
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2
I want to know why

**Comment by milesial** [comment]
You have to provide input images to the predict script ` predict.py: error: the following arguments are required: --input/-i`
