### ISSUE TITLE
Why choose not to add dropout layers?

### ISSUE THREAD

**Issue by flgau** [milesial/Pytorch-UNet#195]
Hi, I was wondering why you choose not to add dropout layers? Is it because the network is not dense enough and it would lead to worst results to add those kind of layers?

**Comment by milesial** [comment]
The network is not dense and is fully convolutionnal so I don't think dropout layers would be effective. But it can be used for implicit data augmentation according to the authors: 
> Drop-out layers at the end of the contracting path perform further implicit data augmentation

(section 3.1)

**Comment by flgau** [comment]
Okay thank you very much for your answer!
