### ISSUE TITLE
Just some minor issues,

### ISSUE THREAD

**Issue by Khalifa1997** [milesial/Pytorch-UNet#196]
First off, when I am training -on my 100 image dataset- I get a constant dice coef. does this mean anything or does it just mean that I am missing something?
Also when I try to predict, it says it needs a --model param is there any model I could be using for biomedical binary segmentation?
Thanks!

**Comment by milesial** [comment]
The constant DICE may mean that something is wrong with how you load your dataset or how the evaluation split is done.

You need to train your own model specific to your task. I'd advise getting more data, 100 images is not really enough in my opinion.

**Comment by Khalifa1997** [comment]
@milesial even if I had an already pretrained model?

**Comment by milesial** [comment]
If you already have a pretrained model that was trained on similar images, fine-tuning on your dataset should be fine. You would have to load the weights before running the training loop.
