### ISSUE TITLE
TypeError: to() received an invalid combination of arguments 

### ISSUE THREAD

**Issue by wjj001-dl** [milesial/Pytorch-UNet#198]
when i run submit.py ,i receive the follow error.
TypeError: to() received an invalid combination of arguments - got (dtype=torch.dtype, device=bool, ), but expected one of:
 * (torch.device device, torch.dtype dtype, bool non_blocking, bool copy)
 * (torch.dtype dtype, bool non_blocking, bool copy)
 * (Tensor tensor, bool non_blocking, bool copy)

thanks for your help.

**Comment by milesial** [comment]
Hi, I updated the master branch, can you try again? Thanks

**Comment by milesial** [comment]
Closing, as this issue is now outdated after the recent code refactor.

**Comment by zhongerlou** [comment]
I have met the same problem.
