### ISSUE TITLE
How to turn off all grapihcal display?

### ISSUE THREAD

**Issue by primasanjaya** [milesial/Pytorch-UNet#2]
once i run the experiment. 
i got 1st epoch accuracy and got this error

cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1518244421288/work/torch/lib/THC/generic/THCStorage.cu:58

according to your post, we should turn off all graphical display, how?
Thank you.

**Comment by primasanjaya** [comment]
i got it, because of the batch.

**Comment by sunbin1205** [comment]
Do you have your own data set training?
I trained my own data set to run train.py again, but I found that the retraining model didn't seem to be stored, and I ran main.py to make this error. Can you help me?thanks
epoch 1/5...
Traceback (most recent call last):
File "main.py", line 97, in 
train(net)
File "main.py", line 58, in train
left, right = split_into_squares(np.array(im))
NameError: global name 'split_into_squares' is not defined
