### ISSUE TITLE
Ho to use multiple gpus to train my model?

### ISSUE THREAD

**Issue by HongguLiu** [milesial/Pytorch-UNet#203]
Hello,
I want to train my model with 4 gpus via `net = torch.nn.DataParallel(net)`
But there is a error raised.

AttributeError: 'DataParallel' object has no attribute 'n_classes'

I would like to consult you how to solve this problem.

Thank

**Comment by HongguLiu** [comment]
Thanks, I have solved this problem by replacing `net.n_classes` with `net.module.n_classes`.

**Comment by milesial** [comment]
Seems you have resolved your issue. Closing this.

**Comment by ChaosPredictor** [comment]
Hi @HongguLiu , I have tried to  run with `net.module.n_classes` and getting an error:
`AttributeError: 'UNet' object has no attribute 'module'`.

Can you upload all the changes that you did to work with multiple GPUs?

Thanks ahead

**Comment by ChaosPredictor** [comment]
I add 
`net = torch.nn.DataParallel(net)`
to the code, but it's still look like it use only one GPU.
the problem that I had with `module` solved

Any help welcome

**Comment by ChaosPredictor** [comment]
The problem was that I changed `masks_pred = net(imgs)` to `masks_pred = net.module(imgs)`.
It should be stay `masks_pred = net(imgs)`

**Comment by Marneus68** [comment]
Sorry to bump this closed issue but I'm facing the same problem it seems.

@ChaosPredictor I seem to be in a similar state as you in that I don't have any explicit error when running the training however I don't see the training happening on several GPUs, only one of my GPUs seems doing the work so far.

Did you eventually manage to see your training being done on several GPUs in the end?

**Comment by Sehjbir** [comment]
@Marneus68 
I updated the code in this way and the model training is happening in parallel on multiple gpu's.
In the train.py:

if torch.cuda.device_count() > 1:
        print("Let's use", torch.cuda.device_count(), "GPUs!")
        net = torch.nn.DataParallel(net)

and replace net.n_classes with net.module.n_classes 
and n_channel with net.module.n_channels 
in both train.py and evaluate.py
