### ISSUE TITLE
Unet model  error

### ISSUE THREAD

**Issue by xc769458796** [milesial/Pytorch-UNet#204]
in the down4，i can not see conv3x3（channel512-1024）

**Comment by milesial** [comment]
https://github.com/milesial/Pytorch-UNet/blob/84f8392b619940bd542dc670761a0a7a1357001d/unet/unet_model.py#L20

https://github.com/milesial/Pytorch-UNet/blob/84f8392b619940bd542dc670761a0a7a1357001d/unet/unet_parts.py#L16

**Comment by xc769458796** [comment]
thank your reply.but i think in the down4,1024//factor=512,so it only has twice Conv3x3(512-512),not include Conv3x3(512-1024)

**Comment by milesial** [comment]
Then please detail in your issue that you are only talking about the bilinear case.
Also, please search the issues before opening a new one https://github.com/milesial/Pytorch-UNet/issues/69 https://github.com/milesial/Pytorch-UNet/issues/90 https://github.com/milesial/Pytorch-UNet/issues/146

**Comment by milesial** [comment]
Closing, as this issue is now outdated after the recent code refactor.
