### ISSUE TITLE
something wrong with the network architecture?

### ISSUE THREAD

**Issue by wangjk666** [milesial/Pytorch-UNet#207]
Hi, thanks a lot for your work in implementing the code, I have tested your code and the result is amazing. However, when I tried to adjust the model architecture, e.g. add some convtranpose layer, the result is bad, as shown below:
![4](https://user-images.githubusercontent.com/48371342/89138370-f6622480-d56d-11ea-8811-832aa8f36ec9.png)

I wonder whether it is possible for you to give me some advice or ideas on why the segmentation result will be something like this? Thanks a lot.

**Comment by milesial** [comment]
Hi, can you describe the changes you made? Did you modify the encoder jointly with the decoder?
I can also suggest you to contact the authors of the paper if you want more insight into the architecture choices.

**Comment by wangjk666** [comment]
Thanks for your reply. Concretely, I use the simple 'conv+BN+relu' architecture for encoder and 'conv+BN+relu+convtranspose+BN+relu' for decoder, I wonder whether you have encountered similar issues when tackling with segmentation tasks?

**Comment by milesial** [comment]
Most often than not you should look at your training algorithm and hyperparameters instead of trying to tweak the architecture itself. I can't really help you more than that I'm sorry, if you choose to modify the architecture you are on your own.

**Comment by wangjk666** [comment]
Ok, thanks a lot.
