### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`

### ISSUE THREAD

**Issue by weiruchenai** [milesial/Pytorch-UNet#209]
I download the carvarna dataset to train the model by myself, I only select 100 images and their masks, but in the  validation section of the code it throws the following error.
```
Traceback (most recent call last):
  File "C:/Users/DC Wang/Desktop/Direction/Pytorch-UNet-master/train.py", line 188, in <module>
    val_percent=args.val / 100)
  File "C:/Users/DC Wang/Desktop/Direction/Pytorch-UNet-master/train.py", line 102, in train_net
    val_score = eval_net(net, val_loader, device)
  File "C:\Users\DC Wang\Desktop\Direction\Pytorch-UNet-master\eval.py", line 29, in eval_net
    tot += dice_coeff(pred, true_masks).item()
  File "C:\Users\DC Wang\Desktop\Direction\Pytorch-UNet-master\dice_loss.py", line 40, in dice_coeff
    s = s + DiceCoeff().forward(c[0], c[1])
  File "C:\Users\DC Wang\Desktop\Direction\Pytorch-UNet-master\dice_loss.py", line 11, in forward
    self.inter = torch.dot(input.view(-1), target.view(-1))
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`

Process finished with exit code 1
```
Then I traced the root of the problem as the error message says, the error seems to be thrown by `self.inter = torch.dot(input.view(-1), target.view(-1))` in `diceloss.py`.
I dont know mechanism of dice coefficient well, what should I do?

**Comment by milesial** [comment]
Have you tried https://discuss.pytorch.org/t/runtimeerror-cuda-error-cublas-status-alloc-failed-when-calling-cublascreate-handle/78545/7 ?

**Comment by weiruchenai** [comment]
> Have you tried https://discuss.pytorch.org/t/runtimeerror-cuda-error-cublas-status-alloc-failed-when-calling-cublascreate-handle/78545/7 ?

Thank you for your reply. I have already seen this website during searching solution on Google, and tried by adding `os.environ['CUDA_LAUNCH_BLOCKING'] = '1'`, but it seems not the same error as stack trace printed. Besides, I test the code on cpu and find it runs well, but it throws the error on gpu.

**Comment by weiruchenai** [comment]
OK，yesterday I try to downsize the scale to 0.4(defoult 0.5), it worked. So I think may be the input is too big that it reach the memory of my RTX2060 6G during training. That is dumb. Anyway, thanks again.
