### ISSUE TITLE
How to perform data Augmentation operations？如何在dataset.py中进行数据增强操作？

### ISSUE THREAD

**Issue by BRWZ** [milesial/Pytorch-UNet#211]
我怎样才能在dataset.py中进行数据增强操作？谢谢

**Comment by milesial** [comment]
Hi, check out https://pytorch.org/docs/stable/torchvision/transforms.html

**Comment by andanders** [comment]
The link is dead but I think this is what you are looking for
https://pytorch.org/vision/0.11/transforms.html
I'm also trying to figure out how to perform data augmentation.
