### ISSUE TITLE
TypeError: Cannot handle this data type: (1, 1, 768), |u1 when predict

### ISSUE THREAD

**Issue by yvanliang** [milesial/Pytorch-UNet#214]
I use labelme to label four categories, and use labelme's own tools to generate 8-bit PNG masks, size is 576 * 768. In training, the program reported an error: 1 only batches of spatial targets supported (3D tensors) but got targets of size:: [1,1,288,384], (scale is 0.5), so I used  torch.squeeze () to compress the dimension and train successfully. However, in the prediction, there is an error: typeerror: cannot handle this data type: (1, 1, 768), | U1. If you can help me, I would like to thank you very much!

Traceback (most recent call last):
  File "predict.py", line 129, in <module>
    result = mask_to_image(mask)
  File "predict.py", line 97, in mask_to_image
    return Image.fromarray((mask * 255).astype(np.uint8))
  File "C:\Users\lyyly\Anaconda3\envs\Pregnant\lib\site-packages\PIL\Image.py", line 2751, in fromarray
    raise TypeError("Cannot handle this data type: %s, %s" % typekey) from e
TypeError: Cannot handle this data type: (1, 1, 768), |u1

**Comment by lyylyy66668888** [comment]
I don't know if the mask files is suitable for your code, but there is no problem in the train process, so I think it might be correct.

**Comment by lyylyy66668888** [comment]
I have changed the mask files to one-hot, each pixel was 0or1or2or3, but this problem still exists.

**Comment by lyylyy66668888** [comment]
I have changed the mask files, each pixel was 0or1or2or3(0 and C-1), but this problem still exists.

**Comment by aawink7** [comment]
I have been facing the same issue, did you figure it out @lyylyy66668888 ?
@milesial do you have any suggestions?

**Comment by HaixiongLi** [comment]
I meet the same question, did you solve them?

**Comment by mmachon** [comment]
Did one of you solve this error? I did the same steps to use multi-class classifications with RGB images 600 * 800 as PNG. I can't find a solution.

**Comment by anassmu** [comment]
actually you just should  return np.argmax(full_mask, axis=0)


        full_mask = probs.squeeze().cpu().numpy()
        return  np.argmax(full_mask, axis=0) #> out_threshold

**Comment by Valentina-Gol** [comment]
mask = mask.astype(np.uint8)

**Comment by gittjob** [comment]
请问怎么解决的，我也遇到类似的情况
