### ISSUE TITLE
predict.py: error: the following arguments are required: --input/-i

### ISSUE THREAD

**Issue by MRLQ-Q** [milesial/Pytorch-UNet#215]
Thank your code,please help me 
   my  error is usage: predict.py [-h] [--model FILE] --input INPUT [INPUT ...]
                  [--output INPUT [INPUT ...]] [--viz] [--no-save]
                  [--mask-threshold MASK_THRESHOLD] [--scale SCALE]
predict.py: error: the following arguments are required: --input/-i

**Comment by milesial** [comment]
You have to specify your input images.
Next time, please read the error messages before opening issues :)
