### ISSUE TITLE
UnpicklingError: invalid load key, '{'.

### ISSUE THREAD

**Issue by mostafiz67** [milesial/Pytorch-UNet#217]
Hello,
I am just trying to run the train.py file in the Google Colab. Everything was file until these codes:

`if args.load:
          net.load_state_dict(
            torch.load(args.load, map_location=device)
        )
        logging.info(f'Model loaded from {args.load}')
        net.to(device=device)`

program is showing **UnpicklingError: invalid load key, '{'.** Please, check the think, I uploaded the screenshot of the error 
[[![Screenshot-from-2020-09-20-21-28-44.png](https://i.postimg.cc/hPLc0hRS/Screenshot-from-2020-09-20-21-28-44.png)](https://postimg.cc/yk8M11N5)](url)

But I tried so many ways (using google)but unfortunately, no one is working!

Could you tell me what I have to do?

**Comment by milesial** [comment]
Hi, can you show what parameter was passed to --load ? It seems that your checkpoint might be corrupted.

**Comment by mostafiz67** [comment]
@milesial  thank you for your reply. I did not change anything (except the data location path etc). I just running your same code, same dataset (Caravan)

**Comment by milesial** [comment]
Which pretrained model are you using? Mine or yours?

**Comment by mostafiz67** [comment]
The full file is yours. I just change 
`dir_img = '/content/gdrive/My Drive/Colab Notebooks/Pytorch-UNet-master/data/imgs/train_hq/train_hq/'
dir_mask = '/content/gdrive/My Drive/Colab Notebooks/Pytorch-UNet-master/data/masks/train_masks/train_masks/'`

The rest of the code is yours (same)!

**Comment by milesial** [comment]
The problem seems to be with the deserialization or the trained model. I'd suggest you download it again.

**Comment by xino1** [comment]
Hello,
Unfortunately, I have the same issue.
I try to run your code just changing these two strings:   
dir_img = 'data/imgs/'
dir_mask = 'data/masks/'
Can you help me, what else do I need to do?

And if it possible, what else do I need to do if I want to try it with my own data?

**Comment by xino1** [comment]
As far as I understand this problem applies only to google collaboratory. The code works on a PC.
