### ISSUE TITLE
doubts in training

### ISSUE THREAD

**Issue by anaghazachariah** [milesial/Pytorch-UNet#218]
true_masks.size()=torch.Size([1, 3, 128, 128])
masks_pred.size()=torch.Size([1, 1, 128, 128])
I am getting errors because these 2 are different..how to correct my error

**Comment by milesial** [comment]
Change your true masks from 3 channels to 1 channels, they should be only 1 probabilities channel and not RGB

**Comment by anaghazachariah** [comment]
@milesial  another error
RuntimeError: only batches of spatial targets supported (3D tensors) but got targets of dimension: 4

**Comment by Jeff860530** [comment]
Try this mask = mask[:,:1,:,:]
means[batch:channel[0]:columns:rows]

**Comment by Spawnfile** [comment]
`true_masks = true_masks[:,0, :,:].unsqueeze(1)`

makes both shapes equal.

**Comment by dufan175** [comment]
> `true_masks = true_masks[:,0, :,:].unsqueeze(1)`
> 
> makes both shapes equal.
> 
> Additionally you must add this layer to `eval.py` script too. When calculating DICE score you need to use `true_mask` input again, so if you do NOT change there, you will get error at the 10 percent ( default value ) of loading bar.



> `true_masks = true_masks[:,0, :,:].unsqueeze(1)`
> 
> makes both shapes equal.
> 
> Additionally you must add this layer to `eval.py` script too. When calculating DICE score you need to use `true_mask` input again, so if you do NOT change there, you will get error at the 10 percent ( default value ) of loading bar.

Hi,i used your method and i added the layer to `eval.py` ,but it said next:
Traceback (most recent call last):        
  File "train.py", line 180, in <module>
    val_percent=args.val / 100)
  File "train.py", line 97, in train_net
    val_score = eval_net(net, val_loader, device)
  File "/UNet/Pytorch-UNet-master/eval.py", line 33, in eval_net
    return tot / n_val
ZeroDivisionError: division by zero

**Comment by Spawnfile** [comment]
It seems the error is about your DataLoader which is passed to `eval_net` function as `val_loader` parameter name. Check the DataLoader works properly.

**Comment by milesial** [comment]
Closing, as this issue is now outdated after the recent code refactor.
