### ISSUE TITLE
pretrain model does not work

### ISSUE THREAD

**Issue by adamas-v** [milesial/Pytorch-UNet#220]
hello ,i load your pretrain model and test it with a .jpg image ,but i get output image which was just white

**Comment by milesial** [comment]
Can you share here your input image? thanks.

**Comment by CNruiwang** [comment]
here is the information about input.

![QQ截图20201006174548](https://user-images.githubusercontent.com/50786797/95185935-f693d000-07fb-11eb-9fc2-81db5120450a.png)

**Comment by milesial** [comment]
Thanks, can you share the minimal code needed to reproduce this? Including the download of the pretrained model and the prediction commands used.

**Comment by JoyChen1998** [comment]
Hello! I also got the same problem.  I just  use your code & pretrain model,  change nothing.
The image I input is `ILSVRC2012_test_00000004.jpg `, then I got a large area of white.

**Comment by joshbambrick** [comment]
I am also having this issue. Here is my code: https://colab.research.google.com/gist/joshbambrick/91ad3351d96a3732f3122a5732ba233d/carvana.ipynb

**Comment by milesial** [comment]
I will update the pretrained model in the coming days, so this is not relevant anymore.

**Comment by msnh2012** [comment]
@milesial Waiting for you~
