### ISSUE TITLE
Both the pre-trained model and the dataset you trained yourself get black images with no effect.

### ISSUE THREAD

**Issue by tongxiaozhong14** [milesial/Pytorch-UNet#221]
hello ,i load your pretrain model and test it with a .jpg image ,but i get output image which was just black。hello ,i load your pretrain model and test it with a .jpg image ,but i get output image which was just white

**Comment by lh2n18** [comment]
overfitting...maybe

**Comment by milesial** [comment]
Closing, as this issue is now outdated after the recent code refactor.
