### ISSUE TITLE
MODEL.pth not created

### ISSUE THREAD

**Issue by dancassin** [milesial/Pytorch-UNet#224]
After training a model on custom data with 1 class, no MODEL.pth file was created even though it says it was created.
It says the checkpoint directory was created and the checkpoint was saved, but only the checkpoint directory was created.
Any ideas what would lead to no file being created?

`Epoch 1/1: 100% 90/90 [48:42<00:00, 26.06s/img, loss (batch)=0.0459]
Validation round:   0% 0/10 [00:00<?, ?batch/s]
Validation round:  10% 1/10 [00:08<01:16,  8.45s/batch]
Validation round:  20% 2/10 [00:15<01:04,  8.06s/batch]
Validation round:  30% 3/10 [00:22<00:54,  7.78s/batch]
Validation round:  40% 4/10 [00:29<00:45,  7.60s/batch]
Validation round:  50% 5/10 [00:37<00:37,  7.45s/batch]
Validation round:  60% 6/10 [00:44<00:29,  7.47s/batch]
Validation round:  70% 7/10 [00:54<00:24,  8.17s/batch]
Validation round:  80% 8/10 [01:01<00:15,  7.87s/batch]
Validation round:  90% 9/10 [01:08<00:07,  7.64s/batch]
Validation round: 100% 10/10 [01:15<00:00,  7.48s/batch]
INFO: Validation Dice Coeff: 8.114837442008138e-07
Epoch 1/1: 100% 90/90 [50:03<00:00, 33.37s/img, loss (batch)=0.0459]
INFO: Created checkpoint directory
INFO: Checkpoint 1 saved !`

**Comment by dancassin** [comment]
Looks like this was an issue with Colab. Saving directly to a folder in My Drive instead of the current selected file seems to have solved to issue.

**Comment by kimile599** [comment]
dir_img = '/content/Pytorch-UNet/data/imgs/'
dir_mask = '/content/Pytorch-UNet/data/masks/'
dir_checkpoint = '/content/Pytorch-UNet/checkpoints/'

I have changed the default dirs to above ones, but can't find the checkpoint file in colab and google drive.
The colab drive disk is decreasing which indicates the checkpoint has been saved somewhere
