### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by husheng876** [milesial/Pytorch-UNet#225]
The code i ran it but find there was a error,the memory is out of memory.But I use the 2080ti GPU which has 12G memory.It's far more than the 3G.Why would this cause?And I also try to mark out the code "net.to(device=device)" in the file train.py in 169 line.Then there is some problem as below:
![image](https://user-images.githubusercontent.com/28149798/95565856-5afc9c80-0a53-11eb-822f-3bbde23b339b.png)

**Comment by milesial** [comment]
What is your batch size and image sizes?

**Comment by husheng876** [comment]
the batchsize is 1 and image size is about 1022✘767&nbsp; &nbsp;1504✘1129 and so on.is the image size should be fixed and be smaller?


 
---Original---

**Comment by milesial** [comment]
You may have a problem with your setup, or a DataLoader bug. With the Carvana dataset it fits on my machine that has way less memory.
Consider opening a bug in the pytorch repo?

**Comment by husheng876** [comment]
sorry, i forgot to tell you i used the dataset"ISIC2017".And use the training data as the image and its label as the mask.
