### ISSUE TITLE
How to cite this code?

### ISSUE THREAD

**Issue by Yingping-LI** [milesial/Pytorch-UNet#227]
Thanks a lot for sharing the code!

If I want to publish a paper, the code of the new method is modified based on this code,  how do I cite it ?
Thanks a lot!

**Comment by milesial** [comment]
Hi! You can cite this by including a link to the repo (https://github.com/milesial/Pytorch-UNet) along with my full name: Alexandre Milesi.
Don't forget to also cite the original authors https://arxiv.org/abs/1505.04597
Thanks
