### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by GutlapalliNikhil** [milesial/Pytorch-UNet#230]
I have 5 rgb images and 5 respective masks. While I was training, I was getting error like

INFO: Using device cuda
INFO: Network:
	3 input channels
	1 output channels (classes)
	Bilinear upscaling
INFO: Creating dataset with 5 examples
2020-10-17 10:55:47.542163: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
INFO: Starting training:
        Epochs:          5
        Batch size:      1
        Learning rate:   0.0001
        Training size:   5
        Validation size: 0
        Checkpoints:     True
        Device:          cuda
        Images scaling:  0.5
    
Epoch 1/5:  20%|██        | 1/5 [00:01<00:04,  1.03s/img, loss (batch)=0.905]
Traceback (most recent call last):
  File "train.py", line 181, in <module>
    val_percent=args.val / 100)
  File "train.py", line 92, in train_net
    if global_step % (n_train // (10 * batch_size)) == 0:
ZeroDivisionError: integer division or modulo by zero

Can some please help me why I was getting this?

**Comment by milesial** [comment]
5 images // 10 * 1 is 0, you should modify modify the 10 to 1 if you want to train on that few images
