### ISSUE TITLE
怎么实现多类的分割？需要如何修改呢？

### ISSUE THREAD

**Issue by wangfusheng-cqu** [milesial/Pytorch-UNet#236]
如题

**Comment by wangfusheng-cqu** [comment]
有谁知道的吗？

**Comment by lycutter** [comment]
请问你实现了吗？我现在也在研究这个

**Comment by wangfusheng-cqu** [comment]
你好！这个是去年的，好像是重新找了个源码，有点忘了。


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: lycutter ***@***.***&gt;
发送时间: 2021年8月9日 20:54
收件人: milesial/Pytorch-UNet ***@***.***&gt;
抄送: wangfusheng-cqu ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[milesial/Pytorch-UNet] 怎么实现多类的分割？需要如何修改呢？ (#236)





 
请问你实现了吗？我现在也在研究这个
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
