### ISSUE TITLE
1only batches of spatial targets supported (3D tensors) but got targets of size:

### ISSUE THREAD

**Issue by Zhangwenyao1** [milesial/Pytorch-UNet#237]
hi,When i run my dataset ,it occured this problem!
my images have 3 channel(rgb),and label have 7 classes。 
 I change your code as net = UNet(n_channels=3, n_classes=3,bilinear=True).

Thank you !

**Comment by wangfusheng-cqu** [comment]
I meet same problem with you, the code only apply to  two classes

**Comment by hilmicanguven** [comment]
I have same issue when I tried to train with Virtual KITTI dataset (consists of RGB images and their masks).

**Comment by milesial** [comment]
If you have 7 classes then change that in the constructor of the network.

**Comment by wangfusheng-cqu** [comment]
You can tell me more about it，I hope to get your help。 my QQ：652317513






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "milesial/Pytorch-UNet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月7日(星期六) 晚上9:37
收件人:&nbsp;"milesial/Pytorch-UNet"<Pytorch-UNet@noreply.github.com&gt;;
抄送:&nbsp;"咸鱼野鹤"<652317513@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [milesial/Pytorch-UNet] 1only batches of spatial targets supported (3D tensors) but got targets of size: (#237)





 
If you have 7 classes then change that in the constructor of the network.

**Comment by Zhangwenyao1** [comment]
I have solved this problem , so if other guys have this problem , you can leave a message below! I think  we can help each other!

**Comment by hilmicanguven** [comment]
yes, we still have problem. we want to apply multi-class segmentation using virtual KITTI dataset. but when we want to change n_classes, then we get this error. can you help me please? thank you

**Comment by wangfusheng-cqu** [comment]
> I have solved this problem , so if other guys have this problem , you can leave a message below! I think we can help each other!

I have same problem in multi-class segmentation,can you share the code with us.

**Comment by Zhangwenyao1** [comment]
> > I have solved this problem , so if other guys have this problem , you can leave a message below! I think we can help each other!
> 
> I have same problem in multi-class segmentation,can you share the code with us.

My wechat  945117033

**Comment by Zhangwenyao1** [comment]
> yes, we still have problem. we want to apply multi-class segmentation using virtual KITTI dataset. but when we want to change n_classes, then we get this error. can you help me please? thank you

you should have to transfer your label into n_classes.

**Comment by hilmicanguven** [comment]
Our dataset consists of RGB images and masked RGB images.  they are annotated different colors. what do you mean when you say " transfer your label into n_classes". I do not understand exactly.

**Comment by Zhangwenyao1** [comment]
> Our dataset consists of RGB images and masked RGB images. they are annotated different colors. what do you mean when you say " transfer your label into n_classes". I do not understand exactly.

For example , if you have 4 classes,you can transfer this 4 colors in to [ 0 0 1] [ 0 0 2] [ 0 0 3] and [0 0 4].and save the last column as label

**Comment by Zhangwenyao1** [comment]
> If you have 7 classes then change that in the constructor of the network.

thank you ! Can you tell what means about checkpoint? It is necessary?Can I delete it?

**Comment by kirmans** [comment]
> > Our dataset consists of RGB images and masked RGB images. they are annotated different colors. what do you mean when you say " transfer your label into n_classes". I do not understand exactly.
> 
> For example , if you have 4 classes,you can transfer this 4 colors in to [ 0 0 1] [ 0 0 2] [ 0 0 3] and [0 0 4].and save the last column as label

Hi I have same problem, i dont exactly understand what you mean. Can you describe more about your solution.

**Comment by luosiwu** [comment]
> > Our dataset consists of RGB images and masked RGB images. they are annotated different colors. what do you mean when you say " transfer your label into n_classes". I do not understand exactly.
> 
> For example , if you have 4 classes,you can transfer this 4 colors in to [ 0 0 1] [ 0 0 2] [ 0 0 3] and [0 0 4].and save the last column as label

I still do not understand. So what is the label format?

**Comment by tsorewilly** [comment]
In case anyone still face this issue, just squeeze the redundant channel in the target. The "1" in this question's target is redundant and is the reason for the error.
