### ISSUE TITLE
How to evaluate segmentation model with empty masks ?

### ISSUE THREAD

**Issue by picEmily** [milesial/Pytorch-UNet#241]
I get an IoU and a Dice score of 0 when there is no object to find mask and my model correctly predicted an empty mask which is wrong.

I tried also to inverse the masks when the masks are empty but it gives to high iou and dice scores even if the predicted mask isn't completly empty.

what should I do?

**Comment by milesial** [comment]
If both the target and the prediction are empty, dice and IoU are 0/0 which is undefined.
It is up to you to treat this as a score of 1 or as a special case.
