### ISSUE TITLE
ValueError: Target size (torch.Size([1, 3, 256, 256])) must be the same as input size (torch.Size([1, 1, 256, 256]))

### ISSUE THREAD

**Issue by Kurocuki** [milesial/Pytorch-UNet#244]
`Epoch 1/5:   0%|          | 0/37 [00:05<?, ?img/s]
Traceback (most recent call last):
  File "D:/project/Pytorch-UNet-master/train.py", line 181, in <module>
    val_percent=args.val / 100)
  File "D:/project/Pytorch-UNet-master/train.py", line 80, in train_net
    loss = criterion(masks_pred, true_masks)
  File "D:\Python\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Python\lib\site-packages\torch\nn\modules\loss.py", line 601, in forward
    reduction=self.reduction)
  File "D:\Python\lib\site-packages\torch\nn\functional.py", line 2112, in binary_cross_entropy_with_logits
    raise ValueError("Target size ({}) must be the same as input size ({})".format(target.size(), input.size()))
ValueError: Target size (torch.Size([1, 3, 256, 256])) must be the same as input size (torch.Size([1, 1, 256, 256]))

Process finished with exit code 1`

why?

**Comment by oneThousand1000** [comment]
> `Epoch 1/5: 0%| | 0/37 [00:05<?, ?img/s]
> Traceback (most recent call last):
> File "D:/project/Pytorch-UNet-master/train.py", line 181, in
> val_percent=args.val / 100)
> File "D:/project/Pytorch-UNet-master/train.py", line 80, in train_net
> loss = criterion(masks_pred, true_masks)
> File "D:\Python\lib\site-packages\torch\nn\modules\module.py", line 541, in **call**
> result = self.forward(*input, **kwargs)
> File "D:\Python\lib\site-packages\torch\nn\modules\loss.py", line 601, in forward
> reduction=self.reduction)
> File "D:\Python\lib\site-packages\torch\nn\functional.py", line 2112, in binary_cross_entropy_with_logits
> raise ValueError("Target size ({}) must be the same as input size ({})".format(target.size(), input.size()))
> ValueError: Target size (torch.Size([1, 3, 256, 256])) must be the same as input size (torch.Size([1, 1, 256, 256]))
> 
> Process finished with exit code 1`
> 
> why?

Because the shape of  your true_masks is [1, 3, 256, 256], while  the shape of  your masks_predis [1, 1, 256, 256], maybe you should convert your true_masks  into gray scale image, that works for me :)

**Comment by Kurocuki** [comment]
thx, I have solved this problem by changing the input
