### ISSUE TITLE
Question about the size of the data set

### ISSUE THREAD

**Issue by WxpHB** [milesial/Pytorch-UNet#245]
Hi,
Thx for your excellent work. but when i ran this code on a small data set(about 30000 imgs/masks)，the speed is about 16img/s, but when tested on a big data set(about One million),the speed is about 2-5img/s,too slow. Is there something wrong?
![图片](https://user-images.githubusercontent.com/47773138/100995148-5c010480-3592-11eb-9966-749cbc7a2a61.png)

**Comment by milesial** [comment]
This is most likely caused by the regexes in https://github.com/milesial/Pytorch-UNet/blob/381924dfd6396c92b17ceebaa9c607f3f9392106/utils/dataset.py#L45

For datasets that large, I would encourage you to modify this method to not use `glob` and to make it custom to your dataset.

**Comment by WxpHB** [comment]
> 
> 
> This is most likely caused by the regexes in
> 
> https://github.com/milesial/Pytorch-UNet/blob/381924dfd6396c92b17ceebaa9c607f3f9392106/utils/dataset.py#L45
> 
> For datasets that large, I would encourage you to modify this method to not use `glob` and to make it custom to your dataset.

Thx，
the limitation of the speed has nothing to do with glob()，after some modification，i can deal with 100million dataset.
