### ISSUE TITLE
prediction error

### ISSUE THREAD

**Issue by lukui1995** [milesial/Pytorch-UNet#25]
Hi,When i run the predict,py,it has the following error."RuntimeError: Given groups=1, weight of size [64, 3, 3, 3], expected input[1, 4, 319, 319] to have 3 channels, but got 4 channels instead"

Can you tell me the solution? Thank you very much.

**Comment by qq237942920** [comment]
my problem is "invalid argument 0: Sizes of tensors must match except in dimension 1. Got 52 and 51 in dimension 2",when I try to run the prediction.py

**Comment by qq237942920** [comment]
i found the way to solve my problem in the closed issue,thx!
