### ISSUE TITLE
Is this UNet missing the skip connection parts?

### ISSUE THREAD

**Issue by cainmagi** [milesial/Pytorch-UNet#252]
I find that this U-Net implementation does not have any skip connection. It seems that it is not a true U-Net, but only an auto-encoder. I wonder why this implementation so popular. It is very misleading.

**Comment by milesial** [comment]
It does have skip connections ...
https://github.com/milesial/Pytorch-UNet/blob/381924dfd6396c92b17ceebaa9c607f3f9392106/unet/unet_parts.py#L57-L69

**Comment by cainmagi** [comment]
> It does have skip connections ...
> https://github.com/milesial/Pytorch-UNet/blob/381924dfd6396c92b17ceebaa9c607f3f9392106/unet/unet_parts.py#L57-L69

Thank you! I understand.
