### ISSUE TITLE
Error from dataloader.py

### ISSUE THREAD

**Issue by petervlad** [milesial/Pytorch-UNet#253]
![Capture](https://user-images.githubusercontent.com/32743023/104474318-8f3da700-55c6-11eb-948b-bfc5e7e89ddb.PNG)
I receive this error when I'm trying to run test.py, it persists even when I change the data.

**Comment by milesial** [comment]
If you're on windows, PyTorch Dataloader on multiple threads can have problems, use a single thread. Check out the closed issues there was a similar one that was solved.
