### ISSUE TITLE
predict.py input imagefolder and output predictfolder

### ISSUE THREAD

**Issue by haitian-zhang** [milesial/Pytorch-UNet#254]
How can I enter a picture folder instead of multiple pictures.I want to do this:python predict.py -i E:/wulanhua/image/ -o E:/wulanhua/predict/ ,How to achieve it?

**Comment by milesial** [comment]
`-i` can be given multiple images, so using your shell expansion will work: `-i mydir/*.jpg`

**Comment by oguzcanbekar** [comment]
Did it work in your code correctly? 

In my code when I am trying 
python predict.py -i test/testimgheart0-slice232_z.png -o result\Output.jpg --mode
l checkpoints\CP_epoch5.pth 
with 1 .png it is working. But when I want to predict all pngs in this file like that: 
python predict.py -i test/*.png -o result/ --model checkpoints\CP_epoch5.pth
It is showing this error:
File "predict.py", line 119, in <module>
    img = Image.open(fn)
  File "C:\Users\HMKIST\anaconda3\envs\tfgpu\lib\site-packages\PIL\Image.py", line 2904, in open
    fp = builtins.open(filename, "rb")
OSError: [Errno 22] Invalid argument: 'test/*.png'

Can you help me please?
