### ISSUE TITLE
Pretrained Model giving weird results

### ISSUE THREAD

**Issue by SharanSMenon** [milesial/Pytorch-UNet#256]
I tried using the pre-trained model from the releases section but my results end up looking like this:
![car_OUT](https://user-images.githubusercontent.com/31973632/106372689-66e0d700-6340-11eb-8ae7-5e9d39fc6fd9.jpg)

I tried the model on the following image:
![car](https://user-images.githubusercontent.com/31973632/106372693-72cc9900-6340-11eb-9200-57030f6219c4.jpg)

All I did was download the repository and the model to my computer and then I ran `predict.py` on the image.

**Comment by milesial** [comment]
Did you pass `--scale=1` to the script ? The pretrained model was trained on 100% scale.

**Comment by maobaoqi** [comment]
@SharanSMenon I got the same bad results and set --scale=1 also not work well
