### ISSUE TITLE
Using Pretrained Model for Dataset with more than 3 Channels

### ISSUE THREAD

**Issue by georgezywang** [milesial/Pytorch-UNet#261]
First and foremost, thank you for posting this wonderful repo! I am working on training a dataset with input size (200, 200, 98), so there are in total 98 input channels as opposed to 3, which is the case for RGB images. Given that the pretrained model specifies `net.n_channels = 3`, I am wondering if it is possible, at all, to use the pretrained model as a starting point for training on my own dataset? I won't expect this to work for most models, but since this is a FCN, chances are there might be a way to get things settled?

**Comment by milesial** [comment]
Nothing is impossible and you could do some surgery to transfer some weights. But you would need more weights in the first layer, so that one can't be reused.
I would suggest just training from scratch, the pretrained network was fast to train for 5 epochs.

**Comment by georgezywang** [comment]
Thank you!
