### ISSUE TITLE
train

### ISSUE THREAD

**Issue by He9702** [milesial/Pytorch-UNet#265]
The bit depth of my image is 24 bits, but my mask is 1 bit. 
Does this have a big impact on the result? How can I solve this problem? 

![屏幕截图 2021-03-10 175433](https://user-images.githubusercontent.com/71333170/110611658-6272ce00-81ca-11eb-9bea-8521ed137af7.png)

**Comment by zhedahe** [comment]
no problem

**Comment by zhedahe** [comment]
> 
> 
> The bit depth of my image is 24 bits, but my mask is 1 bit.
> Does this have a big impact on the result? How can I solve this problem?
> 
> ![屏幕截图 2021-03-10 175433](https://user-images.githubusercontent.com/71333170/110611658-6272ce00-81ca-11eb-9bea-8521ed137af7.png)

no problem
