### ISSUE TITLE
how to train with batch_size equal to 4

### ISSUE THREAD

**Issue by hejun888** [milesial/Pytorch-UNet#268]
when i set batch_size equal to 4, the following error occurs and how to set batch_size equal to 4 to train network
![1](https://user-images.githubusercontent.com/28728850/115256100-83332980-a161-11eb-8c9d-34136324f703.jpg)

**Comment by milesial** [comment]
If your images are of different sizes, the default Dataloader won't be able to batch them together. You would have to create a custom `collate` function.

**Comment by milesial** [comment]
Closing, as this issue is now outdated after the recent code refactor.
