### ISSUE TITLE
wrong with loss

### ISSUE THREAD

**Issue by kakiharuka** [milesial/Pytorch-UNet#269]
I don't know why my loss is negative.And it has a very large absolute value.
![image](https://user-images.githubusercontent.com/57217361/115960234-cbc45b80-a542-11eb-8a54-319e38ae5efb.png)

**Comment by milesial** [comment]
This is usually because you loaded your target masks incorrectly.

**Comment by kakiharuka** [comment]
thanks for your help.l have solved it.
