### ISSUE TITLE
Dice coefficient is greater than 1

### ISSUE THREAD

**Issue by Aya-S** [milesial/Pytorch-UNet#271]
training on another dataset, binary mask for 1 class and background.
Getting negative loss like -1000 and Dice coeffiecnt greater that 1
this makes no sense and I can't trace back the bug.
any ideas please?

**Comment by dscarmo** [comment]
Probably because your network output is not limited to 0 - 1 (e. g. with a Sigmoid)

**Comment by milesial** [comment]
Closing, as this issue is now outdated after the recent code refactor.
