### ISSUE TITLE
How to get each resulting image in one folder rather than a file?

### ISSUE THREAD

**Issue by chulyoung-code** [milesial/Pytorch-UNet#272]
hi thank you for your code and smart

I want to get segmentation images for my own training data

so I want to process one folder at a time rather than entering them one by one in command.

.txt file or change the path etc... what should I do?

**Comment by Rusching** [comment]
You can modify the file predict.py, which is about how to receive parameters from cmd. The easiest way is to explicitly write your own img path into file and specify the output path of predict results, and write how to traverse all files in you img path.

**Comment by Rusching** [comment]
> hi thank you for your code and smart
> 
> I want to get segmentation images for my own training data
> 
> so I want to process one folder at a time rather than entering them one by one in command.
> 
> .txt file or change the path etc... what should I do?

You can modify the file predict.py, which is about how to receive parameters from cmd. The easiest way is to explicitly write your own image path into file and specify the output path of predicted results, and write how to traverse all files in you image path.
