### ISSUE TITLE
Some problems about preprocess in dataset.py

### ISSUE THREAD

**Issue by Minami77** [milesial/Pytorch-UNet#273]
Thanks for sharing your code！
 I have some problems:
1. can i use transforms.Normalize and transforms.ToTensor() to relpace this
![`392$L(PSO)J6Q{~7WYWN3X](https://user-images.githubusercontent.com/50018272/119255215-18a45c00-bbed-11eb-914c-9df555990858.png)
2.  value of scale 
   my imgs' size is 512x512, scale=0.5, then the input is 256x256 for net. 
   whehter the input size must be 256x256 when predicting? 
   can i use 512x512? If this happens does it work？
![L50{6EMZ2$M3Q}Q5(H)WMOT](https://user-images.githubusercontent.com/50018272/119255238-3bcf0b80-bbed-11eb-9475-82eef2e9eee6.png)

**Comment by milesial** [comment]
1. Yes you can do it if it works better for you
2. No, the input should be the original size when predicting, if you give `--scale 0.5` it will resize the image.
