### ISSUE TITLE
the input imgs and masks?

### ISSUE THREAD

**Issue by henbucuoshanghai** [milesial/Pytorch-UNet#275]
The input images and target masks should be in the data/imgs and data/masks

the input imgs are the original images?
how to get the target masks?  tha mask is only 0 and 255 in the image? the h w of the mask is the same as the original image?

**Comment by milesial** [comment]
Yes, the input images are the original images (RGB)
The masks should have the same size as the images, and black and white for binary classification.

**Comment by Litou-lyh** [comment]
> Yes, the input images are the original images (RGB)
> The masks should have the same size as the images, and black and white for binary classification.

How about multiple classes?

**Comment by milesial** [comment]
For multi class you can load them one hot encoded

**Comment by CasonTsai** [comment]
@milesial  

> Yes, the input images are the original images (RGB)
> The masks should have the same size as the images, and black and white for binary classification.

hello,does 'black and white for binary classification.' mean pixel value  <0 or 255>   rather than < 0 or 1>  in mask image,

**Comment by milesial** [comment]
O and 1 for binary
