### ISSUE TITLE
Thanks for the great repository!

### ISSUE THREAD

**Issue by chaoyuaw** [milesial/Pytorch-UNet#28]
Thanks for the great repository!

We have a project that partially uses a modification of your u-net model. We're wondering if you'd mind if we release that code. Of course we'll be sure to make it clear that part of that uses a modification of your code.

If you agree, could you please also let me know if you have a preferred way for us to acknowledge your contribution? (e.g. citing your real name and affiliation rather than citing "milesial". ). Thanks! (My email is cywu@utexas.edu if you'd like to discuss about this through email. )

**Comment by milesial** [comment]
Hi ! Thanks, that's cool ! I don't mind, I'm contacting you by email.
