### ISSUE TITLE
A bug in evaluate.py and one question

### ISSUE THREAD

**Issue by qimingyudaowenti** [milesial/Pytorch-UNet#289]
May be here should be `net.n_classes + 1` instead of `net.n_classes`:
https://github.com/milesial/Pytorch-UNet/blob/d8984977848d924644d575f5e46c475d84ff1772/evaluate.py#L19
I notice that the size of mask batch is `N, H, W` without C (not `N, 1, H, W`). Is this omission mainly to facilitate the calculation of the one-hot label?

**Comment by milesial** [comment]
The masks are of shape N, H, W so that after the one hot it becomes N, C, H, W yes, no need for the extra dimension.

Why do you think it should be `net.n_classes + 1`? n_classes include the background.
I agree that when n_classes==1, we shouldn't calculate the one_hot, I will change that.
