### ISSUE TITLE
batch size  error,is it must be 1?

### ISSUE THREAD

**Issue by CasonTsai** [milesial/Pytorch-UNet#292]
when i set batch size ==2  get the error,the gpu memory is enough
![image](https://user-images.githubusercontent.com/18262642/131463896-8c813342-ade5-4954-a772-cb5942cd6d6f.png)
if set batch size ==1 i get correct ,

**Comment by CasonTsai** [comment]
i have solved it ,in high version pytorch should be add contiguous() before view
inter = torch.dot(input.contiguous().view(-1), target.contiguous().view(-1))#cason

**Comment by CasonTsai** [comment]
> What PyTorch version are you on? It's strange that the batch or image dimensions were not contiguous.

the pytorch version is 1.7.1

**Comment by milesial** [comment]
Ok, I only tested on PyTorch 1.9+. I pushed a commit that should fix this, so your workaround is not needed anymore.

**Comment by han-sui** [comment]
I also encounter the similar problem. it will be ok when batch from1to 5,but bigger will happen this TypeError: 'module' object is not callable. does it also caused by the version?
