### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by Flyingdog-Huang** [milesial/Pytorch-UNet#294]
python train.py --amp          device:  cpu                                                                                              INFO: Using device cpu                                                                                    INFO: Network:                                                                                                    3 input channels                                                                                          2 output channels (classes)                                                                               Bilinear upscaling                                                                                INFO: Creating dataset with 5088 examples                                                                 wandb: Currently logged in as: huanglx (use `wandb login --relogin` to force relogin)                     wandb: Tracking run with wandb version 0.12.1                                                             wandb: Syncing run atomic-universe-6                                                                      wandb:  View project at https://wandb.ai/huanglx/u-net                                                    wandb:  View run at https://wandb.ai/huanglx/u-net/runs/c3ddvahx                                          wandb: Run data is saved locally in D:\project\Floor Plan\3-Algorithm\SemanticSegmentation\Pytorch-UNet\wandb\run-20210906_153600-c3ddvahx                                                                          wandb: Run `wandb offline` to turn off syncing.                                                                                                                                                                     INFO: Starting training:                                                                                          Epochs:          5                                                                                        Batch size:      1                                                                                        Learning rate:   1e-05                                                                                    Training size:   4580                                                                                     Validation size: 508                                                                                      Checkpoints:     True                                                                                     Device:          cpu                                                                                      Images scaling:  0.5                                                                                      Mixed Precision: True                                                                                                                                                                                       E:\conda\install\envs\unet\lib\site-packages\torch\cuda\amp\grad_scaler.py:115: UserWarning: torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.                                             warnings.warn("torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.")           Epoch 1/5:   0%|                                                               | 0/4580 [00:05<?, ?img/s] Traceback (most recent call last):                                                                          File "train.py", line 190, in <module>                                                                      amp=args.amp)                                                                                           File "train.py", line 79, in train_net                                                                      for batch in train_loader:                                                                              File "E:\conda\install\envs\unet\lib\site-packages\torch\utils\data\dataloader.py", line 359, in __iter__                                                                                                             return self._get_iterator()                                                                             File "E:\conda\install\envs\unet\lib\site-packages\torch\utils\data\dataloader.py", line 305, in _get_iterator                                                                                                        return _MultiProcessingDataLoaderIter(self)                                                             File "E:\conda\install\envs\unet\lib\site-packages\torch\utils\data\dataloader.py", line 918, in __init__                                                                                                             w.start()                                                                                               File "E:\conda\install\envs\unet\lib\multiprocessing\process.py", line 105, in start                        self._popen = self._Popen(self)                                                                         File "E:\conda\install\envs\unet\lib\multiprocessing\context.py", line 223, in _Popen                       return _default_context.get_context().Process._Popen(process_obj)                                       File "E:\conda\install\envs\unet\lib\multiprocessing\context.py", line 322, in _Popen                       return Popen(process_obj)                                                                               File "E:\conda\install\envs\unet\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__            reduction.dump(process_obj, to_child)                                                                   File "E:\conda\install\envs\unet\lib\multiprocessing\reduction.py", line 60, in dump                        ForkingPickler(file, protocol).dump(obj)                                                              BrokenPipeError: [Errno 32] Broken pipe                                                                                                                                                                             wandb: Waiting for W&B process to finish, PID 9624                                                        wandb: Program failed with code 1.  Press ctrl-c to abort syncing.                                        wandb:                                                                                                    wandb: Find user logs for this run at: D:\project\Floor Plan\3-Algorithm\SemanticSegmentation\Pytorch-UNet\wandb\run-20210906_153600-c3ddvahx\logs\debug.log                                                        wandb: Find internal logs for this run at: D:\project\Floor Plan\3-Algorithm\SemanticSegmentation\Pytorch-UNet\wandb\run-20210906_153600-c3ddvahx\logs\debug-internal.log                                           wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)                      wandb:                                                                                                    wandb: Synced atomic-universe-6: https://wandb.ai/huanglx/u-net/runs/c3ddvahx

**Comment by Flyingdog-Huang** [comment]
![image](https://user-images.githubusercontent.com/43697342/132178740-c32beece-ba57-4df4-b740-1649a9c0e981.png)

**Comment by Flyingdog-Huang** [comment]
make work_num=0, that can be solved

**Comment by syk0417** [comment]
> make work_num=0, that can be solved
 can be not solved
