### ISSUE TITLE
The dataset of segmentation

### ISSUE THREAD

**Issue by ly-atdawn** [milesial/Pytorch-UNet#3]
In your code, you use Carvana Image Masking Challenge data.   Now, we have the coordinate (xi, yi) of objects in image, Do you know how to generate these segmentation images?
![68747470733a2f2f6672616d617069632e6f72672f4f634538486c55366d6536312f4b4e5474384746517a7844522e706e67](https://user-images.githubusercontent.com/23294606/37285680-b061dae6-263a-11e8-82b1-1391e511d6bc.png)
Input the left image and object's coordinate (xi, yi) , the right image how to generate?? Thanks

**Comment by milesial** [comment]
Hi, as stated in the README, you can generate the segmentation image for a specific input with the `predict.py` script:

`python predict.py -i input_image.jpg -o ouput_image.jpg`

The segmentation image will then be saved in the `output_image.jpg` file.

To view the two images side by side with the coordinates like in the screenshot, you can add the `--viz` flag:

`python predict.py -i input_image.jpg -o ouput_image.jpg --viz`
