### ISSUE TITLE
How to solve this error?

### ISSUE THREAD

**Issue by sjytker** [milesial/Pytorch-UNet#304]
**I didn't build a dataset like this way before, and seems like google doesn't know about it either.**

Traceback (most recent call last):
  File "train.py", line 192, in <module>
    amp=args.amp)
  File "train.py", line 42, in train_net
    train_set, val_set = random_split(dataset, [n_train, n_val], generator=torch.Generator().manual_seed(0))
TypeError: random_split() got an unexpected keyword argument 'generator'

**Comment by Lloyd-Pottiger** [comment]
the most possible reason is that your torch version is less than 1.5, maybe you can update torch into a newer version.

**Comment by milesial** [comment]
As said in the readme, PyTorch >= 1.9.0 is recommended, and in that version `random_split` works.
