### ISSUE TITLE
RuntimeError: Class values must be smaller than num_classes.

### ISSUE THREAD

**Issue by nnoyuwan** [milesial/Pytorch-UNet#306]
INFO: Using device cuda
INFO: Network:
	3 input channels
	2 output channels (classes)
	Bilinear upscaling
INFO: Creating dataset with 60 examples
wandb: Currently logged in as: anony-mouse-140736 (use `wandb login --relogin` to force relogin)
wandb: wandb version 0.12.4 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.12.3
wandb: Syncing run olive-frog-51
wandb:  View project at https://wandb.ai/anony-mouse-140736/U-Net?apiKey=7810e0152a6c8d3974e5746284f68a2bc3b09ab5
wandb:  View run at https://wandb.ai/anony-mouse-140736/U-Net/runs/4gtz3i4t?apiKey=7810e0152a6c8d3974e5746284f68a2bc3b09ab5
wandb: Run data is saved locally in C:\Users\50919\PycharmProjects\Pytorch-UNet\wandb\run-20211015_203042-4gtz3i4t
wandb: Run `wandb offline` to turn off syncing.
INFO: Starting training:
        Epochs:          5
        Batch size:      1
        Learning rate:   1e-05
        Training size:   54
        Validation size: 6
        Checkpoints:     True
        Device:          cuda
        Images scaling:  0.5
        Mixed Precision: False
    
Epoch 1/5:   0%|          | 0/54 [00:00<?, ?img/s]
Epoch 1/5:   0%|          | 0/54 [02:36<?, ?img/s]
Traceback (most recent call last):
  File "C:/Users/50919/PycharmProjects/Pytorch-UNet/train.py", line 192, in <module>
    amp=args.amp)
  File "C:/Users/50919/PycharmProjects/Pytorch-UNet/train.py", line 96, in train_net
    hot = F.one_hot(true_masks, net.n_classes)
_**RuntimeError: Class values must be smaller than num_classes.**_

My mask color is black and white imge with a channel, and I has set the n_classes to 1 and 2, but all get this error, and this is true_masks value [https://ibb.co/5r5F5Gf](url)

**Comment by milesial** [comment]
Hi, this might be related to https://github.com/milesial/Pytorch-UNet/issues/311 and should be fixed now, can you try again on the new master?
