### ISSUE TITLE
Mask image preprocess with resize

### ISSUE THREAD

**Issue by xinzhuang** [milesial/Pytorch-UNet#311]
## Situation:
Thanks for your implemention of UNet! It's easy to use. I use it to train a mulit-class segmentation task.

**Mask image**:multi classes,pixel value from 0 to N-1,each value indicates one object class. only one channel,image mode is 'L'.

## Problem:
when I set scale=0.5,after preprocessing, bigger pixel values than N-1,such as N,N+1 appear in the processed mask image.
And then,the trainer encounters a bug in loss compution that pixel value bigger than class num.  
## Solution: 
 add resample parameter to resize call.
`pil_img = pil_img.resize((newW, newH),resample= Image.NEAREST)`
according to Pillow api [reference](https://pillow.readthedocs.io/en/stable/reference/Image.html#functions),

> Image.resize(size, resample=None, box=None, reducing_gap=None)[source]
Returns a resized copy of this image.

> Parameters
- resample – An optional resampling filter. This can be one of PIL.Image.NEAREST, PIL.Image.BOX, PIL.Image.BILINEAR, PIL.Image.HAMMING, PIL.Image.BICUBIC or PIL.Image.LANCZOS. If the image has mode “1” or “P”, it is always set to PIL.Image.NEAREST. If the image mode specifies a number of bits, such as “I;16”, then the default filter is PIL.Image.NEAREST. Otherwise, the default filter is PIL.Image.BICUBIC. See: Filters.

Hope this can help. Thank you again.

**Comment by milesial** [comment]
Thanks! I guess it depends on the mask format and how PIL loads it. https://github.com/milesial/Pytorch-UNet/commit/8f317cb13c17ef25a86b25a0c24390e04cd4db82 should fix it, let me know if it doesn't.

**Comment by vedantroy** [comment]
Hi! I was wondering why you chose `BICUBIC` for the masks instead of `NEAREST`?

**Comment by milesial** [comment]
`pil_img = pil_img.resize((newW, newH), resample=Image.NEAREST if is_mask else Image.BICUBIC)` is using NEAREST for masks
