### ISSUE TITLE
dice score code issue

### ISSUE THREAD

**Issue by dirtycomputer** [milesial/Pytorch-UNet#319]
Is the code below is necessary?????  (in dice_score.py)
```
    if sets_sum.item() == 0:
            sets_sum = 2 * inter
```

**Comment by milesial** [comment]
Yes. If both the predicted and target sets are empty, the convention is to report a dice score of 1

**Comment by vedantroy** [comment]
Does this mean we can replace the given if statement with `if sets_sum == 0: return 1`?

**Comment by milesial** [comment]
Yes you're right, I'll do an update as this cleans up the code.
