### ISSUE TITLE
mask format problem

### ISSUE THREAD

**Issue by way790110** [milesial/Pytorch-UNet#320]
i hava a some question. 

I want to create my own dataset for trainnig. 

my dataset only have one class(set class to  2). if i set class to 1 ,loss is always zero, there wiil be no change.

when mask format is boolean , my mask is all black. but this can training.

when mask format is  only 0 and 255, my mask is normal (black and white), but this setting have error. 

![Screenshot from 2021-11-18 20-21-22](https://user-images.githubusercontent.com/33109449/142414489-d681f13c-509d-464e-a40d-c4df9a5853ed.png)

when mask format is  only 0 and 255 and setting class to 255.  that can training, but set class to 255 is strange.

how to setting the model , i can use normal mask and set class to 2 ?

Can someone help me or give me some suggestions?

**Comment by milesial** [comment]
Your mask should be boolean: 0/1. Not 0/2, not 0/255. You say that it's training fine with a boolean mask. What is the issue then?
