### ISSUE TITLE
prediction on multi class

### ISSUE THREAD

**Issue by kimile599** [milesial/Pytorch-UNet#328]
I have 4 class + 1 BG to detection. So i put n_classes=5

The training was fine, but when i try to predict the result, got the error as this:

![微信截图_20220110155211](https://user-images.githubusercontent.com/53457043/148867929-823fd128-cfbb-4e5d-81f2-d3cb394abecc.png)

**Comment by milesial** [comment]
Make sure the n_channels and n_classes match in the training and prediction scripts
