### ISSUE TITLE
training on multi-class masks

### ISSUE THREAD

**Issue by zhaodadu111** [milesial/Pytorch-UNet#329]
hello there, im trying to train this code on a multi-class medical image datasets, it works all fine during the training process, but when i try to predict the result i found that only one class was predicted. do you know how to solve this problem?

**Comment by River-mao** [comment]
Hello！Have you solved this problem?

**Comment by zhaodadu111** [comment]
> 

yes, i have solved this problem, i have rewritten the test file

**Comment by zengjie617789** [comment]
@NUS-Tim does the mask file generate more value other than 0 and 1?

**Comment by zherenz** [comment]
@NUS-Tim Hi, in the binary segmentation, the predicted values seem to be 0 and 0.5. So you can change mask*255 to mask*510 in the mask_to_image(mask: np.ndarray) function to generate the images with values of 0 and 255.
