### ISSUE TITLE
The pretrained model has unexpected keys

### ISSUE THREAD

**Issue by young169** [milesial/Pytorch-UNet#333]
all of unexpected keys are bias tensor, which cannot directly load by your predict.py file. I just change the default model path to "parser.add_argument('--model', '-m', default='unet_carvana_scale0.5_epoch1.pth', metavar='FILE', help='Specify the file in which the model is stored')"
Is there some pretrained model that can fix this problem? 
![image](https://user-images.githubusercontent.com/18310166/154211363-ff295eea-48e2-4db6-8e23-ef800ba533de.png)

**Comment by milesial** [comment]
Can you update to latest master and try with the pretrained models in the new v3 release?

**Comment by young169** [comment]
> Can you update to latest master and try with the pretrained models in the new v3 release?

I changed to scale1.0_epoch2.pth, and it wored OK, thanks!
