### ISSUE TITLE
Copy and crop part

### ISSUE THREAD

**Issue by eark25** [milesial/Pytorch-UNet#334]
Why using padding on cropping x1 not x2 in copy and crop part of the class Up in unet_parts.py?

**Comment by milesial** [comment]
Why not?

**Comment by eark25** [comment]
I'm confused because in the original unet paper they cropped the output from downsampling path which is 'x2' in this case. Instead, in your code, 'x1' is being cropped (or expanded, i'm not sure about that), so I just want to know the reason behind this decision.

**Comment by milesial** [comment]
Both should be fine.
By cropping the downsampled features, you lose some information, while if you pad the upsampled features, you don't lose anything. I think that was my thinking behind that, but in reality it shouldn't affect convergence much?

**Comment by eark25** [comment]
Yeah, the loss of information makes sense here. Thanks for the answers!

**Comment by imskull** [comment]
In my case, using padding introduces bugs in edge pixels, it looks like color bleeding, I fixed it by changing padding(x1) to crop(x2) as the paper suggest. I suspect it caused by my target images have color in border, that is different with OP's case(plain black in border).
