### ISSUE TITLE
train.py文件执行时的一些错误

### ISSUE THREAD

**Issue by BlakeHong** [milesial/Pytorch-UNet#339]
在本机上运行 由于显卡性能比较低 修改图像尺寸缩放输入从0.5到0.38 运行后到一个epoch中的10%发现
OSError: [WinError 1455] 页面文件太小，无法完成操作。
Error loading "H:\Anaconda\envs\unet\lib\site-packages\torch\lib\cusolverMg64_10.dll" or one of its dependencies.
两个报错
而且运行train.py文件发现C盘内存不断变小，想问怎么解决呢？

**Comment by milesial** [comment]
Please use english, else I can't help you. Thanks

**Comment by BlakeHong** [comment]
![$ S_~}5XBG9(BX(1@YSL3CC](https://user-images.githubusercontent.com/50291293/158631439-1601884b-473f-4643-bb48-398221bc49f0.png)

**Comment by milesial** [comment]
It seems your machine is not fit to run this kind of workload. I suggest using cloud ressources like collab.

**Comment by BlakeHong** [comment]
thank you

**Comment by Victor-0220-yy** [comment]
![image](https://user-images.githubusercontent.com/74761231/163365973-fab0625b-389f-4367-9d09-e3e9977f0ba4.png)
excuse me ,could you please  help me deal with  this problem?
predict.py: error: the following arguments are required: --input/-i
