### ISSUE TITLE
can we use this to repeat arxiv.org/abs/1505.04597

### ISSUE THREAD

**Issue by tianxiangli1924** [milesial/Pytorch-UNet#340]
Hi, in the following paper https://arxiv.org/abs/1505.04597 i found it linked to your github. but in your github i don't know can we use this structure to repeat this paper with MRI data?

**Comment by milesial** [comment]
Yes you can, it's mainly a matter of correctly preprocessing the MRI data. The building blocks of the UNet are in this repo.
