### ISSUE TITLE
error  about  backward  in  dice_loss.py

### ISSUE THREAD

**Issue by bobo0810** [milesial/Pytorch-UNet#35]
There is an error in line 23 of dice_loss.py

error:
` grad_input = grad_output * 2 * (target * self.union + self.inter)/ self.union * self.union `

correct:
` grad_input = grad_output * 2 * (target * self.union - self.inter)/ self.union * self.union `

proving process：

![](http://boboprivate.oss-cn-beijing.aliyuncs.com/18-10-26/7783988.jpg)

**Comment by bobo0810** [comment]
@milesial

**Comment by milesial** [comment]
@bobo0810  Oops ! Thanks for catching that. Gotta work on my derivatives ... (u/v)' = (u' * v **-** u * v')/(v^2) indeed !
In practice, this loss was not used for training, only for evaluation, so that's why all was working well, kinda.
Fixed it in 649124b.
Thanks !
