### ISSUE TITLE
when i exec python predict.py -i test.jpeg -o output.jpeg report erro

### ISSUE THREAD

**Issue by daixiangzi** [milesial/Pytorch-UNet#36]
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 120 and 118 in dimension 2 at /opt/conda/conda-bld/pytorch_1535488076166/work/aten/src/THC/generic/THCTensorMath.cu:87

**Comment by milesial** [comment]
Is this related to https://github.com/milesial/Pytorch-UNet/issues/17 ? You need to be in python 3. If you are, can you please tell me what are the dimensions of your images ?
