### ISSUE TITLE
masks reading error after data augmentation

### ISSUE THREAD

**Issue by MSEwantCS** [milesial/Pytorch-UNet#369]
Hi milesial,

I have succeeded in training the data prepared by labelme.

However, when I augmented the imgs and masks using imgaug, the augmented masks cannot be read properply, with error:

RuntimeError: only batches of spatial targets supported (3D tensors) but got targets of dimension: 4

I checked the size of errored true_mask when trianing, and it returns torch.Size([1, 407, 402, 3]). While the working true_masks returns something like torch.size([1, 407, 402])

**I guess it is caused by the data augment procedure, which changes the format of the masks. However, I do not know how to revise the augment code or the Unet code to fix the error. Your advice on how to make it work is appreciated!**

The agument code is shown below:

import cv2
import imgaug as ia
import imgaug.augmenters as iaa
from imgaug.augmentables.segmaps import SegmentationMapsOnImage

for j in range(1, 102):

    image = cv2.imread(f'./data/imgs/{j}.png')
    segmap = cv2.imread(f'./data/masks/{j}.png')

    # Here, we arbitrarily place some squares on the image.
    # Class 0 is our intended background class.
    segmap = SegmentationMapsOnImage(segmap, shape=image.shape)

    # Define our augmentation pipeline.
    seq = iaa.SomeOf((1, 5), [
        iaa.Dropout([0.05, 0.2]),      # drop 5% or 20% of all pixels
        iaa.Multiply((0.8, 1.2), per_channel=0.2), 
        iaa.contrast.LinearContrast((0.5, 2.0), per_channel=0.5), # improve or worsen the contrast
        iaa.Sharpen((0.0, 1.0)),       # sharpen the image
            # Scale/zoom them, translate/move them, rotate them and shear them.
        iaa.Affine(
            scale={"x": (0.8, 1.2), "y": (0.8, 1.2)},
            translate_percent={"x": (-0.2, 0.2), "y": (-0.2, 0.2)},
            rotate=(-25, 25),
            shear=(-8, 8)
        ),  # rotate by -25 to 25 degrees (affects segmaps)
        iaa.ElasticTransformation(alpha=2, sigma=1)  # apply water effect (affects segmaps)
    ])

    # Augment images and segmaps.
    for i in range(10):
        # 经过这行代码之后，就可以分别拿到增强后的原图和分割图，就可以和自己代码做整合了
        images_aug_i, segmaps_aug_i = seq(image=image, segmentation_maps=segmap)
        
        cv2.imwrite(f'aug data/imgs/{j}_aug_img_{i}.png', images_aug_i)
        cv2.imwrite(f'aug data/masks/{j}_aug_img_{i}.png', segmaps_aug_i.arr)

**Comment by MSEwantCS** [comment]
solved. the label.png generated by labelme shall be loaded with PIL

**Comment by Parsa744** [comment]
hi, 
can u explain more how u solve it
best
