### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

### ISSUE THREAD

**Issue by 40618233** [milesial/Pytorch-UNet#372]
Hi,
I have a problem with this place, can you help me?

![image](https://user-images.githubusercontent.com/57423080/173360300-72b08a74-bd00-4fa2-b5a1-570bcbcc3cb8.png)

**Comment by 40618233** [comment]
> Hi, I have a problem with this place, can you help me?
> 
> ![image](https://user-images.githubusercontent.com/57423080/173360300-72b08a74-bd00-4fa2-b5a1-570bcbcc3cb8.png)

![image](https://user-images.githubusercontent.com/57423080/173361032-2f90c584-a718-4ed3-95f6-8bf8a0fa15a5.png)

**Comment by milesial** [comment]
This might be either:
- a problem with your CUDA setup
- an issue coming from an OOM, in that case I would move to a larger GPU or reduce the image scaling
