### ISSUE TITLE
Should you also save the optimizer state?

### ISSUE THREAD

**Issue by vedantroy** [milesial/Pytorch-UNet#376]
Thanks for making this implementation open-source! I had a quick question about it.

During check pointing, you save the model's state dictionary, but not the optimizer's state dictionary.
I was curious why you don't also save the optimizer's state dictionary.

**Comment by milesial** [comment]
Yes in theory if you want an accurate suspend/resume mechanism, optimizer and LR scheduler states should also be saved. I was not really concerned with that use-case, so for now it only loads the model weights and initializes the optimizer/scheduler back to default.

If this is a popular request I may add it to the repo in the future.
