### ISSUE TITLE
Saving to MODEL.pth

### ISSUE THREAD

**Issue by gonzalofdez98** [milesial/Pytorch-UNet#377]
Hi,
when i train the model all i got are the checkpoints. I know I have to transform them into a MODEL.pth but i don't know how. Could you please tell me how?
Thanks a lot.

**Comment by DeepKnowledge1** [comment]
you can find it in checkpoints folder, 

use last one, e.g, checkpoint_epoch5.pth, 
if you dont want to set the path to the model, Just copy it to the main directory and rename it to MODEL.pth.

**Comment by milesial** [comment]
MODEL.pth is just a placeholder for a model checkpoint file, you can just set --model and point to your checkpoint when predicting
