### ISSUE TITLE
About Dice loss

### ISSUE THREAD

**Issue by HappySleeep** [milesial/Pytorch-UNet#381]
In training, the dice of background is  ALSO  caculated!  Is that better than only use the dice of foreground when the foreground is small?
 
    Thank you!

**Comment by milesial** [comment]
It really depends on your usecase and dataset. You can try both options and compare results.

**Comment by ynma-hanvo** [comment]
> It really depends on your usecase and dataset. You can try both options and compare results.

hi, can you elaborate on this, what case should we use the background .
