### ISSUE TITLE
How's the performance of this implementation

### ISSUE THREAD

**Issue by eglxiang** [milesial/Pytorch-UNet#39]

**Comment by milesial** [comment]
The network implementation relies on Pytorch, so its performance is on par with the framework's. There shouldn't be anything special if you use the last version of pytorch. If you use `bilinear=True` for the upsampling, things are faster and need less memory.

About the data loading and overall pipeline, it's Python so you get what you expect.

**Comment by xiaoxingzeng** [comment]
This implementation is very different from the origin U-Net,  I think its depend on your task.

**Comment by milesial** [comment]
@xiaoxingzeng Can you tell me what's different from the original architecture ? I think my implementation matches the Fig. 1 from https://arxiv.org/pdf/1505.04597.pdf

**Comment by xiaoxingzeng** [comment]
> 
> 
> @xiaoxingzeng Can you tell me what's different from the original architecture ? I think my implementation matches the Fig. 1 from https://arxiv.org/pdf/1505.04597.pdf

Hi milesial, I check the paper and your code.
Sorry，it's my mistake, I reference the paper <Image-to-Image Translation with Conditional Adversarial Networks> not the origin paper you referenced.  Your reimplementation is correct.
