### ISSUE TITLE
ValueError: autodetected range of [-inf, inf] is not finite

### ISSUE THREAD

**Issue by a1802lzw** [milesial/Pytorch-UNet#395]
![image](https://user-images.githubusercontent.com/58769778/196576845-cea45ed0-6568-497c-940a-4998d8e12e3d.png)

![image](https://user-images.githubusercontent.com/58769778/196576978-a65f8f0c-7e02-4b8b-9def-2cde6b116fdd.png)

Hello, I found a problem

**Comment by milesial** [comment]
Fixed in https://github.com/milesial/Pytorch-UNet/commit/a013c80ca6b011ba34ba0700b961b77e0ed003a2

**Comment by t19b205d** [comment]
thanks!!
