### ISSUE TITLE
为什么 3.0版本的模型大小和之前1.0 2.0不一样

### ISSUE THREAD

**Issue by RookieAI** [milesial/Pytorch-UNet#396]
对比了class UNet，也没什么区别啊

**Comment by milesial** [comment]
Hi, please use english to raise issues

**Comment by RookieAI** [comment]
Sorry, it is 121,328KB of unet_carvana_scale1.0_epoch2.pth in v3.0 and 67, 511KB of unet_carvana_scale1_epoch5.pth in v2.0, v1.0. I compare the unet_model.py, unet_part.py between v3.0 and v1.0, but cannot find answer.

**Comment by RookieAI** [comment]
Sorry, it is 121,328KB of unet_carvana_scale1.0_epoch2.pth in v3.0 and 67, 511KB of unet_carvana_scale1_epoch5.pth in v2.0, v1.0. I compare the unet_model.py, unet_part.py between v3.0 and v1.0, but cannot find why the size of model file is different in three versions

**Comment by milesial** [comment]
Between v2 and v3, some bias was removed, and the bilinear setting was switched to off by default. That explains the sire difference.

![image](https://user-images.githubusercontent.com/30204471/197540610-bacd3166-7ee8-461c-b9ed-884fcf111967.png)

**Comment by RookieAI** [comment]
OK, thank you very much
