### ISSUE TITLE
Problem in string concatenation in train.py

### ISSUE THREAD

**Issue by ploncomi** [milesial/Pytorch-UNet#403]
In train.py, the following line is present:

```
torch.save(net.state_dict(), str(dir_checkpoint / 'checkpoint_epoch{}.pth'.format(epoch)))
```
As this code tries to apply an / operator to two strings, the following error appears:

```
TypeError: unsupported operand type(s) for /: 'str' and 'str'
```

Best regards.

**Comment by milesial** [comment]
`dir_checkpoint` is a path object https://github.com/milesial/Pytorch-UNet/blob/a013c80ca6b011ba34ba0700b961b77e0ed003a2/train.py#L21
so this error only happens because you changed to code to use a string
