### ISSUE TITLE
BUG: No parameter of 'foreach' for RMSprop in torch 1.9

### ISSUE THREAD

**Issue by Yaser-wyx** [milesial/Pytorch-UNet#413]
In the latest version, you use the parameter  'foreach' for optim.RMSprop in line 78 in train.py. However, this is not supported in PyTorch 1.9, which will make an error when init the RMSprop.

![image](https://user-images.githubusercontent.com/26665516/208826435-5ff78297-c849-4b3d-b05c-87405aad6fa1.png)

![image](https://user-images.githubusercontent.com/26665516/208826194-7f8a15ab-2f29-470d-ab47-1c21196bb482.png)
This is supported in version 1.12.
![image](https://user-images.githubusercontent.com/26665516/208826347-fe2ad35b-9b2f-41c2-9c0b-14389931045c.png)

**Comment by milesial** [comment]
Hi, yes please use >=1.12. Sorry for the inconvenience, I'll update the readme.
