### ISSUE TITLE
a problem in predict

### ISSUE THREAD

**Issue by JeYohl** [milesial/Pytorch-UNet#414]
hi,i have a problem,why pics channel will be changed to num of class,for example:
my pic channel is [3,m,n],when i set class to 2,pic will be changed to [2,m,n] while i am composing. then it will cause the following channel errors。
Here's my log：
image.shape:torch.Size([1, 3, 540, 960])
img.shape:torch.Size([2, 540, 960])
pic.shape：torch.Size([2, 540, 960])
Traceback (most recent call last):
  File "predict.py", line 103, in <module>
    device=device)
  File "predict.py", line 38, in predict_img
    full_mask = tf(probs.cpu()).squeeze()
  File "/home/makeid/Downloads/conda3/envs/unet_pytorch/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 61, in __call__
    img = t(img)
  File "/home/makeid/Downloads/conda3/envs/unet_pytorch/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 183, in __call__
    return F.to_pil_image(pic, self.mode)
  File "/home/makeid/Downloads/conda3/envs/unet_pytorch/lib/python3.7/site-packages/torchvision/transforms/functional.py", line 275, in to_pil_image
    raise ValueError("Only modes {} are supported for 2D inputs".format(permitted_2_channel_modes))
ValueError: Only modes ['LA'] are supported for 2D inputs

**Comment by milesial** [comment]
Hi, are you on the latest version? There is no `tf(probs.cpu()).squeeze()` line currently in predict.py

**Comment by JeYohl** [comment]
yes,about two months ago,I had the pleasure of studying your project,the engineering of that time is used today.
here is the previous version prediction function：

def predict_img(net,
                full_img,
                device,
                scale_factor=1,
                out_threshold=0.5):
    net.eval()

    img = torch.from_numpy(BasicDataset.preprocess(full_img, scale_factor, is_mask=False))
    img = img.unsqueeze(0)
    img = img.to(device=device, dtype=torch.float32)
    with torch.no_grad():
        output = net(img)
        if net.n_classes > 1:
            probs = F.softmax(output, dim=1)[0]
        else:
            probs = torch.sigmoid(output)[0]
        print('image.shape:{}'.format(img.shape))
        tf = transforms.Compose([
            transforms.ToPILImage(),
            transforms.Resize((full_img.size[1], full_img.size[0])),
            transforms.ToTensor()
        ])

        full_mask = tf(probs.cpu()).squeeze()


    if net.n_classes == 1:
        return (full_mask > out_threshold).numpy()
    else:
        return F.one_hot(full_mask.argmax(dim=0), net.n_classes).permute(2, 0, 1).numpy()

**Comment by JeYohl** [comment]
thanks for your reply,i have solved the problem by repalcing with the latest prediction function。
