### ISSUE TITLE
KeyError: 'mask_values'

### ISSUE THREAD

**Issue by aTunass** [milesial/Pytorch-UNet#415]
when i run predict.py file, it gives error getting 4 channels instead of 3 channels, so i converted the image from RGBA to RGB, then i run it again it gives error like below, my conversion then does it have any effect and if possible can i get a fix for this
*Convert RGBA to RGB
![Screenshot from 2023-01-01 12-31-06](https://user-images.githubusercontent.com/119738823/210161962-0ed17c44-8b01-4200-8a11-2aa4c9a79136.png)
*Error
![Screenshot from 2023-01-01 12-30-20](https://user-images.githubusercontent.com/119738823/210161966-6c7fefc4-e3cc-4a17-a924-d2adca741b8f.png)

**Comment by milesial** [comment]
Hi, can you try the latest master?

**Comment by aTunass** [comment]
oh it worked, thank you so much

**Comment by aTunass** [comment]
Anyway, when i fix the code in your 
way, the code runs and returns the mask without ndim=3, and it's a 2 dimensional array, i tried to convert them to 3 dimensional so that the image can be read with open cv using np.array(), but it doesn't work. So can you give me some solutions, please?
*when i run code, it doesn't print '3333333333'
![Screenshot from 2023-01-02 00-24-59](https://user-images.githubusercontent.com/119738823/210179562-3bf02868-00b0-45a2-a025-0f914d2b59c4.png)
*this is my code to convert array
![Screenshot from 2023-01-02 00-25-18](https://user-images.githubusercontent.com/119738823/210179570-a4232d8d-0cc4-4560-9591-3f5ced0dcfdd.png)

**Comment by milesial** [comment]
The predict function returns a 2D array with either class indices when n_classes > 1 or probabilities when n_classes == 1, that's expected.
What is the issue exactly? The argmax has already be done in the predict function at that point, no need to do it in mask_to_image too. mask_to_image will return you a PIL image that you can convert to openCV easily

**Comment by aTunass** [comment]
oh sorry, I'm quite new in this field, maybe I misunderstood the problem in another direction, because I was able to convert the image from PIL image to Numpy array successfully, but I still can't use cv2 .imshow () for them so I thought they were related to the above function.
