### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Junye-Chen** [milesial/Pytorch-UNet#416]
when i run `python train.py --scale 1.0 --amp` , the following error occurs.
```
INFO: Using device cuda
INFO: Network:
        3 input channels
        2 output channels (classes)
        Transposed conv upscaling
INFO: Creating dataset with 20 examples
INFO: Scanning mask files to determine unique values
  0%|                                                                                                                              | 0/20 [00:00<?, ?it/s]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/workspace2/conda/conda_envs/nndet/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/workspace2/github/Pytorch-UNet-master/utils/data_loading.py", line 28, in unique_mask_values
    mask_file = list(mask_dir.glob(idx + mask_suffix + '.*'))[0]
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 212, in <module>
    train_model(
  File "train.py", line 43, in train_model
    dataset = CarvanaDataset(dir_img, dir_mask, img_scale)
  File "/workspace2/github/Pytorch-UNet-master/utils/data_loading.py", line 121, in __init__
    super().__init__(images_dir, mask_dir, scale, mask_suffix='_mask')
  File "/workspace2/github/Pytorch-UNet-master/utils/data_loading.py", line 54, in __init__
    unique = list(tqdm(
  File "/workspace2/conda/conda_envs/nndet/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/workspace2/conda/conda_envs/nndet/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
IndexError: list index out of range

```
i guess maybe some errors happen in` INFO: Scanning mask files to determine unique values`? but i have no idea about how to figure it out.

**Comment by GaoQF1016** [comment]
Hello, I have encountered the same problem. At present, my data/masks directory only has two png data, such as 1.png and 2.png. Do you have any solution?

**Comment by GaoQF1016** [comment]
> What is the content of your data/masks directory?

Hello, I have encountered the same problem. At present, my data/masks directory only has two png data, such as 1.png and 2.png. Do you have any solution?

**Comment by Junye-Chen** [comment]
> > What is the content of your data/masks directory?
> 
> Hello, I have encountered the same problem. At present, my data/masks directory only has two png data, such as 1.png and 2.png. Do you have any solution?

I have already fixed it. the key point is the filename, you must follow the rule of the imgs/masks name.
eg. **21_training.jpg** for img and **21_training_mask.png** for mask
hopefully It can help u.

**Comment by Junye-Chen** [comment]
> What is the content of your data/masks directory?

thank you for your reply! I've already addressed it.

**Comment by GaoQF1016** [comment]
> > > What is the content of your data/masks directory?
> > 
> > 
> > Hello, I have encountered the same problem. At present, my data/masks directory only has two png data, such as 1.png and 2.png. Do you have any solution?
> 
> I have already fixed it. the key point is the filename, you must follow the rule of the imgs/masks name. eg. **21_training.jpg** for img and **21_training_mask.png** for mask hopefully It can help u.

Thank you very much! The problem has been solved. By the way, the data dimension is [40,40,3], and the mask dimension is [40,40]. Is such data valid? Or what is your data dimension?

**Comment by milesial** [comment]
A fix should be in master now so you don't have to rename files.

Dimensions look good. If they aren't loaded correctly from your custom dataset, feel free to modify the data loading code.
