### ISSUE TITLE
AttributeError: module 'torch.cuda' has no attribute 'OutOfMemoryError'

### ISSUE THREAD

**Issue by sp7414** [milesial/Pytorch-UNet#431]
While training, an error occurred: AttributeError: module 'torch.cuda' has no attribute 'OutOfMemoryError'. How to solve this?

**Comment by milesial** [comment]
- What PyTorch version are you using?
- What base docker image are you using?

**Comment by SiruLiu645** [comment]
> 

I use the 1.12 pytorch version, also have this problem

**Comment by sp7414** [comment]
install torch=1.13 will solve this problem



---- Replied Message ----
| From | ***@***.***> |
| Date | 03/01/2023 14:48 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [milesial/Pytorch-UNet] AttributeError: module 'torch.cuda' has no attribute 'OutOfMemoryError' (Issue #431) |

I use the 1.12 pytorch version, also have this problem

**Comment by milesial** [comment]
Yes 1.13 or later will fix it

**Comment by AryaDan11** [comment]
I use the 1.13 pytorch version, also have this problem

**Comment by Schweizliu** [comment]
> I use the 1.13 pytorch version, also have this problem

yes，did you solve it？
