### ISSUE TITLE
How to add augmentation to both image and mask with a percentage of dataset?

### ISSUE THREAD

**Issue by jjjonathan14** [milesial/Pytorch-UNet#435]
Augmentation like rotation, affine will change the shape of the image so we need to apply same augmentation to mask as well

**Comment by milesial** [comment]
I suggest looking into https://pytorch.org/vision/stable/transforms.html

They talk specifically about transforming images and masks together here: https://pytorch.org/vision/stable/transforms.html#functional-transforms
