### ISSUE TITLE
batch size mismatch or spatial target dimensions

### ISSUE THREAD

**Issue by CodLiver** [milesial/Pytorch-UNet#44]
Hello, 

I found this wonderful code and wanted to test on my models:

There was line in your warnings that:

`outputs = outputs.permute(2, 3, 0, 1).contiguous().view(-1, 2)`

should be added. however, then I get: `ValueError: Expected input batch_size (1605632) to match target batch_size (32).`

my train size is 1600 images total. and batch is 32, numwork is 2.

Besides, when I removed it, then I get:

`invalid argument 3: only batches of spatial targets supported (3D tensors) but got targets of dimension: 1`

my length of 4d array is: `32,2,224,224` or the mirrored (no  sure)

thanks and best regards,

**Comment by milesial** [comment]
Hi, what line of what file is causing this error ?
