### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by eeehco** [milesial/Pytorch-UNet#445]
Hello author. I would like to ask if the pre trained model you provided can only be used on data with channel 2. After changing the number of channels for my data, using this pre trained model will report an error.
![image](https://github.com/milesial/Pytorch-UNet/assets/102967148/9eefb273-bcbf-49ff-91e2-5b48cded811b)

**Comment by milesial** [comment]
Hi, the pretrained model provided was trained on the Carvana dataset, which has 3-channels images.
