### ISSUE TITLE
How to add data augmentation into dataset before training?

### ISSUE THREAD

**Issue by Li-Yidong** [milesial/Pytorch-UNet#462]
I found out the model is not performing well on test data, so I want to do data augmentation on the dataset. 
Where should I add the code?

**Comment by neilkimn** [comment]
If you head to the `BasicDataset` class, you'll see that the dataset generation logic is defined in that class. Depending on your use-case, you can change the [`__getitem__()`](https://github.com/milesial/Pytorch-UNet/blob/master/utils/data_loading.py#L93) function of the `BasicDataset` class to apply arbitrary transformations and/or augmentations, or write an additional method on `BasicDataset`, just like there is `preprocess()`. 

See [PyTorch Dataset class](https://pytorch.org/tutorials/beginner/data_loading_tutorial.html#dataset-class) for an example on how to do this.

**Comment by Li-Yidong** [comment]
> If you head to the `BasicDataset` class, you'll see that the dataset generation logic is defined in that class. Depending on your use-case, you can change the [`__getitem__()`](https://github.com/milesial/Pytorch-UNet/blob/master/utils/data_loading.py#L93) function of the `BasicDataset` class to apply arbitrary transformations and/or augmentations, or write an additional method on `BasicDataset`, just like there is `preprocess()`.
> 
> See [PyTorch Dataset class](https://pytorch.org/tutorials/beginner/data_loading_tutorial.html#dataset-class) for an example on how to do this.

Thanks!!
