### ISSUE TITLE
ValueError: axes don't match array

### ISSUE THREAD

**Issue by I-CANT-CODE** [milesial/Pytorch-UNet#47]
Running into an issue when training on my own data set.

I cloned the repo, added folders data/train and data/train_masks,

only part of the code I changed was in load.py

`def get_full_img_and_mask(id, dir_img, dir_mask):
    im = Image.open(dir_img + id + '.jpg')
    mask = Image.open(dir_mask + id + '_mask.gif')
    return np.array(im), np.array(mask)`

I changed to
`def get_full_img_and_mask(id, dir_img, dir_mask):
    im = Image.open(dir_img + id + '.png')
    mask = Image.open(dir_mask + id + '.png')
    return np.array(im), np.array(mask)`

because the file names are in png format and the corresponding files are the same name but in a different directory.

here is the error:

Starting epoch 1/5.

Traceback (most recent call last):
  File "train.py", line 139, in <module>
    img_scale=args.scale)
  File "train.py", line 64, in train_net
    for i, b in enumerate(batch(train, batch_size)):
  File "/home/users/rssadre/RAPIDS-IDREAM/Pytorch-UNet/utils/utils.py", line 37, in batch
    for i, t in enumerate(iterable):
  File "/home/users/rssadre/RAPIDS-IDREAM/Pytorch-UNet/utils/utils.py", line 17, in hwc_to_chw
    return np.transpose(img, axes=[2, 0, 1])
  File "/home/users/rssadre/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 639, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "/home/users/rssadre/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: axes don't match array

**Comment by milesial** [comment]
Are your images in `dir_img` in colors (RGB) ? It seems that after the loading the images don't have 3 dimensions. Can you check the shape of `im` ?

**Comment by I-CANT-CODE** [comment]
my pictures are all black and white but I am not sure if they are formatted as RGB

**Comment by milesial** [comment]
that's the problem, I think they are loaded with only 1 channel so the shape is HxW where it should be CxHxW. You can try to change the code you mentionned to `return np.expand_dims(np.array(im),axis=2), np.array(mask)`

**Comment by I-CANT-CODE** [comment]
Made the changes you mentioned and still am getting

    Starting training:
        Epochs: 5
        Batch size: 10
        Learning rate: 0.1
        Training size: 1900
        Validation size: 100
        Checkpoints: True
        CUDA: True
    
Starting epoch 1/5.
Traceback (most recent call last):
  File "train.py", line 139, in <module>
    img_scale=args.scale)
  File "train.py", line 64, in train_net
    for i, b in enumerate(batch(train, batch_size)):
  File "/home/users/rssadre/RAPIDS-IDREAM/Pytorch-UNet/utils/utils.py", line 37, in batch
    for i, t in enumerate(iterable):
  File "/home/users/rssadre/RAPIDS-IDREAM/Pytorch-UNet/utils/utils.py", line 17, in hwc_to_chw
    return np.transpose(img, axes=[2, 0, 1])
  File "/home/users/rssadre/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 639, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "/home/users/rssadre/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: axes don't match array

**Comment by milesial** [comment]
In the `hwc_to_chw` function before the line 17, can you print the shape of `img` (`img.shape`) and give it to me ? It should have 3 dimensions, no less.

**Comment by JoanHHH** [comment]
@milesial Hi, thanks for sharing. My image shape is H × W, how should I modify the code?

**Comment by JoanHHH** [comment]
@milesial I added `img = np.reshape(img,img.shape+(1,))` in hwc_to_chw(),  the error disappeared, but I don't know if it really solved the problem

**Comment by milesial** [comment]
You image should be H x W * C, with C a "dummy" dimension in your case because there is only one channel. The code you cited adds this dimension so it should be OK now.

**Comment by yangyang9706** [comment]
hello, I  have the same problem with you. My dataset is also the same with you .  And I modify the mode as your discussion above. But I get the problem
 Starting training:
        Epochs: 5
        Batch size: 10
        Learning rate: 0.1
        Training size: 2204
        Validation size: 116
        Checkpoints: True
        CUDA: True
    
Starting epoch 1/5.
(200, 125, 1)
(197, 125, 1)
(197, 125, 1)
(200, 125, 1)
(200, 125, 1)
(197, 125, 1)
(197, 125, 1)
(197, 125, 1)
(200, 125, 1)
(200, 125, 1)
Traceback (most recent call last):
  File "train.py", line 141, in <module>
    img_scale=args.scale)
  File "train.py", line 67, in train_net
    imgs = np.array([i[0] for i in b]).astype(np.float32)
ValueError: could not broadcast input array from shape (200,125) into shape (1)

How should I deal with these? 
Thank you.
