### ISSUE TITLE
dice computation error

### ISSUE THREAD

**Issue by andygaofei** [milesial/Pytorch-UNet#48]
Hi, 

Thanks for your effort first of all.

There is a computation problem when evaluating with function eval_net().

 In the first epoch, the dice_val is correct I think like this:
**Starting epoch 1/100.
tensor(1.00000e-02 *
       8.4271, device='cuda:0')
tensor(0.3177, device='cuda:0')
tensor(0.1262, device='cuda:0')
tensor(0.5119, device='cuda:0')
tensor(0.1107, device='cuda:0')
tensor(0.1193, device='cuda:0')
tensor(1.00000e-02 *
       9.0274, device='cuda:0')
tensor(1.00000e-02 *
       7.9401, device='cuda:0')
tensor(1.00000e-02 *
       9.0199, device='cuda:0')
tensor(0.1371, device='cuda:0')
tensor(0.1182, device='cuda:0')
tensor(0.4859, device='cuda:0')
tensor(1.00000e-02 *
       8.5216, device='cuda:0')
tensor(0.2082, device='cuda:0')
tensor(1.00000e-02 *
       7.0810, device='cuda:0')
tensor(0.1223, device='cuda:0')
tensor(0.1023, device='cuda:0')
tensor(1.00000e-02 *
       8.5076, device='cuda:0')
tensor(1.00000e-02 *
       9.6932, device='cuda:0')
tensor(0.1094, device='cuda:0')
tensor(1.00000e-02 *
       8.7262, device='cuda:0')
tensor(0.1857, device='cuda:0')
tensor(0.1320, device='cuda:0')
tensor(1.00000e-02 *
       8.2069, device='cuda:0')
tensor(0.1559, device='cuda:0')
tensor(0.6490, device='cuda:0')
tensor(0.4299, device='cuda:0')
tensor(0.2339, device='cuda:0')
Validation Dice Coeff: 0.182405274361372**

but in the next epochs, the dice_val values are greater than 1, seeming not correct:
**Starting epoch 2/100.
tensor(1.9652, device='cuda:0')
tensor(1.9619, device='cuda:0')
tensor(1.9684, device='cuda:0')
tensor(1.9776, device='cuda:0')
tensor(1.9677, device='cuda:0')
tensor(1.9536, device='cuda:0')
tensor(1.9535, device='cuda:0')
tensor(1.9511, device='cuda:0')
tensor(1.9650, device='cuda:0')
tensor(1.9740, device='cuda:0')
tensor(1.9599, device='cuda:0')
tensor(1.9791, device='cuda:0')
tensor(1.9591, device='cuda:0')
tensor(1.9796, device='cuda:0')
tensor(1.9708, device='cuda:0')
tensor(1.9666, device='cuda:0')
tensor(1.9587, device='cuda:0')
tensor(1.9612, device='cuda:0')
tensor(1.9631, device='cuda:0')
tensor(1.9644, device='cuda:0')
tensor(1.9655, device='cuda:0')
tensor(1.9709, device='cuda:0')
tensor(1.9672, device='cuda:0')
tensor(1.9603, device='cuda:0')
tensor(1.9744, device='cuda:0')
tensor(1.9513, device='cuda:0')
tensor(1.9824, device='cuda:0')
tensor(1.9781, device='cuda:0')
Validation Dice Coeff: 1.9660872902188982**

I am a newcomer with Pytorch and I cannot fix this problem. 

Do you have any idea about this problem?
Thank you!

**Comment by milesial** [comment]
Hi, are your masks binary, and loaded as binary ? The dice loss is not implemented for multiclass masks.

**Comment by andygaofei** [comment]
I got it. The masks read using PIL.Image.Open is not binary. I need make a thresholding after that. I have fixed this problem.
Thanks!








At 2019-04-03 17:35:51, "milesial" <notifications@github.com> wrote:


Hi, are your masks binary, and loaded as binary ? The dice loss is not implemented for multiclass masks.
