### ISSUE TITLE
为什么预测出来的图片全黑，能不能回复一下

### ISSUE THREAD

**Issue by FRC1221** [milesial/Pytorch-UNet#482]

**Comment by huyingjiao** [comment]
你好，我遇到了相同的问题，你的问题解决了吗

**Comment by FRC1221** [comment]
> 你好，我遇到了相同的问题，你的问题解决了吗

没有，换其他的

**Comment by HunterTom94** [comment]
你是不是 跑train的时候用了 --amp？可以试试不要用amp再train一遍

**Comment by deeperlearner** [comment]
I have the same problem. I did not use amp. Did you solve it?

**Comment by deeperlearner** [comment]
In my case, maybe smaller batch-size can solve it.
