### ISSUE TITLE
why the out of self.up1 is 256 but 512 , and the out of self.down4 is 512 but 1024?

### ISSUE THREAD

**Issue by wky1998** [milesial/Pytorch-UNet#49]
Thanks for your work, but i have some questions. why the out of self.up1 is 256 but 512 , and the out of self.down4 is 512 but 1024? Why the in_ch is four times out_ch in self.up?

**Comment by milesial** [comment]
The channels of all the layers are from the figure 1 in the [original paper](https://arxiv.org/pdf/1505.04597.pdf).
You can see that the input of `up` has 4 times as many channels for the input (after the concatenation) than for the output (before the concatenation, which is handled by the next `up`)
