### ISSUE TITLE
run train.py error

### ISSUE THREAD

**Issue by sunbin1205** [milesial/Pytorch-UNet#5]
Thank you for sharing your code, but I wanted to retrain my data set to make a mistake and run the train.py.
Traceback (most recent call last):
  File "train.py", line 129, in <module>
    gpu=options.gpu)
  File "train.py", line 58, in train_net
    val_dice = eval_net(net, val, gpu)
  File "/media/Linux/sun/Pytorch-UNet-master/eval.py", line 27, in eval_net
    y_pred = net(X)
  File "/home/zbw/anaconda2/envs/sun/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/Linux/sun/Pytorch-UNet-master/unet/unet_model.py", line 32, in forward
    x = self.up1(x5, x4)
  File "/home/zbw/anaconda2/envs/sun/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/Linux/sun/Pytorch-UNet-master/unet/unet_parts.py", line 72, in forward
    x = torch.cat([x2, x1], dim=1)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 92 and 91 in dimension 2 at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:111
I hope to get your reply soon.thanks

**Comment by sunbin1205** [comment]
What is the format of the data set required by the network?

**Comment by sunbin1205** [comment]
Thanks for your reply so soon!
But I still didn't run successfully, and that's my problem, asking for help.
1. Do you mean that the final input to unet must be 640*640?
2. My picture size is 1500*1500, which file parameters need to be changed?
Sorry, I'm new.
3. I tried to change the image size in the utils. py file, but it didn't work.
def decode(list):
    mask = np.zeros((1500*1500), np.bool)

    for i, e in enumerate(list):
        if(i%2 == 0):
            mask[e-1:e-2+list[i+1]] = True

    mask = mask.reshape(1500, 1500).transpose()

    return mask

thank you very much!!!

**Comment by sunbin1205** [comment]
Add: my dataset has only two classes, background and building.
I really need your help. Thank you.

**Comment by sunbin1205** [comment]
when run main.py error as:
epoch 1/5...
Traceback (most recent call last):
  File "main.py", line 97, in <module>
    train(net)
  File "main.py", line 58, in train
    left, right = split_into_squares(np.array(im))
NameError: global name 'split_into_squares' is not defined

and If run train.py separately, the trained parameter file such as model.pth does not seem to be saved.
help help!!!

**Comment by sunbin1205** [comment]
I trained my own data set to run train.py again, but I found that the retraining model didn't seem to be stored, and I ran main.py to make this error. Can you help me?thanks
epoch 1/5...
Traceback (most recent call last):
File "main.py", line 97, in
train(net)
File "main.py", line 58, in train
left, right = split_into_squares(np.array(im))
NameError: global name 'split_into_squares' is not defined

and insplit run train.py successfully ignor the model,pth,the dic coeff seems wrong!
Validation Dice Coeff: 0.0208227457479
Starting epoch 2/10.
Validation Dice Coeff: 2.32310811679
Starting epoch 3/10.
Validation Dice Coeff: 2.32310811679
Starting epoch 4/10.
Validation Dice Coeff: 2.32310811679

**Comment by milesial** [comment]
For the errors on `main.py`: this is an outdated file I used for experimenting, it should be deleted as it calls deleted functions, sorry for that. For training, use the `train.py` file.

For the errors on `train.py`, it seems that your batch size is detected as a tuple, check that it is a number in the log messages.

With `train.py`, by default checkpoints will be created et the end of every epoch.

For the Dice coeff, I don't know, check that a validation set is correctly created by the script. What is your `Training size` and `Validation size` in the logs at the start of training ?

**Comment by sunbin1205** [comment]
I'm sorry, I failed again!!
1. For the tuple problem in train, it was found that the reason was variable i, but I didn't know what to do with it.
2. Because of my limited data, currently only 144 training, test on 7, so I want to change the requirements of the size of the input images, such as input 512 * 512 images, can you help me to think about how to modify the resize algorithm?
Or other relevant documents, I tried some, but failed.
3. I mainly want to know how the post-processing of CRF is applied to the model. Looking at the code, it seems that CRF is only used in pridict, is it?
Thank you for your patience!
Looking forward to your reply!

**Comment by milesial** [comment]
If you have 512x512 squares images that's perfect, you can directly pass them without doing what I did, which is splitting each image into squares. You can then bypass the function `split_ids` and come up with you own train and validation data, instead of my `get_imgs_and_masks` function.

If you can replace those lines
https://github.com/milesial/Pytorch-UNet/blob/f57fa46f2d8cd4b0a13be0ee88708fa4dd4e0a88/train.py#L51-L52
with you own datasets of tuples (img, mask), you're good to go.

You can call the resize function when generating your dataset if you want, with default params it will half the width and the height of the input image.

The CRF was more an experimentation to improve result on the prediction, indeed, by playing with the CRF parameters manually. The training was done without the CRF, by applying the loss directly on the output masks.

**Comment by sunbin1205** [comment]
Thanks again for your reply!
The other question is, if I want to call the CRF algorithm directly, can I use this statement directly?
    yy = dense_crf(np.array(full_img).astype(np.uint8), y)
and Both of these parameters are the array of images, right?
but,When the function dense_crf function is called, the following error occurs.
 17, in dense_crf
    d.setUnaryEnergy(U)
  File "pydensecrf/densecrf.pyx", line 82, in pydensecrf.densecrf.DenseCRF.setUnaryEnergy (pydensecrf/densecrf.cpp:3524)
ValueError: Bad shape for unary energy (Need (2, 512), got (2, 262144))
My input test image size is 512*512.,Where is my operational problem? Can you point it out for me? Thank you!

**Comment by milesial** [comment]
This function takes first the full input image, and then the output mask that you got from the net. It doesn't take arrays but only a tuple (image, mask). It returns an image with probabilities, that you can transform into the final mask by applying a threshold on those probabilities (0.5 for me).

The image input and mask input to the function have to be HxW, make sure you have that. 
The image must have 3 channels (512x512x3 for you), and the mask must have 1 channel I think (512x512 for you).

The function will then create two channels out of the input mask, that represents the initial probabilities.
https://github.com/milesial/Pytorch-UNet/blob/c34a455f1722e0b899e9e92c7766b83a9a641980/utils/crf.py#L10

Make sure the correct width and height are calculated at the start of the function, it should be 512 and 512.

**Comment by sunbin1205** [comment]
Thanks to your guidance, I solved the nput problem of last time.
And the CRF algorithm can run through, but a new problem occured.
After CRF processing, the picture is all black.
I looked at the output of the dense_crf, all zeros.
With your experience, can you help me to analyze what might be the problem?
I'm sure my first input is 512*512*3, and the second is 512*512.
Thank you very much!

**Comment by sunbin1205** [comment]
Thanks to your guidance, I solved the input problem of last time.
And the CRF algorithm can run through, but a new problem occured.
After CRF processing, the picture is all black.
I looked at the output of the dense_crf, all zeros.
With your experience, can you help me to analyze what might be the problem?
I'm sure my first input is 5125123, and the second is 512*512.
Thank you very much!

**Comment by sunbin1205** [comment]
Thanks to your guidance, I solved the input problem of last time.
And the CRF algorithm can run through, but a new problem occured.
After CRF processing, the picture is all black.
I looked at the output of the dense_crf, all zeros.
With your experience, can you help me to analyze what might be the problem?
I'm sure my first input is 512*512*3, and the second is 512*512.
Thank you very much!

**Comment by milesial** [comment]
Have you tried plotting the inputs of the function, to make sure they are correct images and masks ? If those are correct, the output should be correct too.

I've never had problems with dense_crf, as I applied the basic usage from https://github.com/lucasb-eyer/pydensecrf.

**Comment by sunbin1205** [comment]
I'm so sorry to bother you again.
But this problem is never solved and it bothers me!!
So I have to explain to you again my problems and identify some questions:
1. The two inputs of the dense_srf function are two image formats or are they converted to array type input?
Because I see np.array in your function, but no matter which form will have the following error!
*******************src_image***************
[[[126 141 129]
  [ 95 111  97]
  [ 86 100  83]
  ...,
  [ 82  98  77]
  [ 81  98  77]
  [ 71  86  66]]

 [[134 152 138]
  [122 140 125]
  [118 135 119]
  ...,
  [ 88 108  84]
  [ 90 110  86]
  [ 86 103  80]]

 [[123 137 124]
  [147 162 148]
  [124 142 126]
  ...,
  [ 89 108  84]
  [ 96 116  90]
  [ 85 102  80]]

 ...,
 [[108 124 110]
  [ 92 110  92]
  [ 93 106  88]
  ...,
  [113 130 107]
  [111 128 105]
  [111 128 111]]

 [[166 181 178]
  [144 162 155]
  [137 157 147]
  ...,
  [121 136 113]
  [119 134 106]
  [122 133 112]]

 [[118 135 130]
  [128 144 139]
  [134 149 143]
  ...,
  [ 68  80  60]
  [ 85  99  80]
  [ 97 109  95]]]
*****************mask_image*******************
[[[161 161 161]
  [130 130 130]
  [100 100 100]
  ...,
  [ 32  32  32]
  [ 63  63  63]
  [ 94  94  94]]

 [[141 141 141]
  [112 112 112]
  [ 84  84  84]
  ...,
  [ 15  15  15]
  [ 35  35  35]
  [ 57  57  57]]

 [[117 117 117]
  [ 93  93  93]
  [ 68  68  68]
  ...,
  [  7   7   7]
  [ 14  14  14]
  [ 25  25  25]]

 ...,
 [[227 227 227]
  [233 233 233]
  [219 219 219]
  ...,
  [251 251 251]
  [225 225 225]
  [191 191 191]]

 [[213 213 213]
  [215 215 215]
  [214 214 214]
  ...,
  [232 232 232]
  [212 212 212]
  [204 204 204]]

 [[201 201 201]
  [186 186 186]
  [173 173 173]
  ...,
  [171 171 171]
  [176 176 176]
  [205 205 205]]]
******************crf_image*****************
/media/Linux/sun/unet-master/unet-master/unet-master/utils/crf.py:13: RuntimeWarning: divide by zero encountered in log
  U = -np.log(output_probs)
Traceback (most recent call last):
  File "test_predict.py", line 41, in <module>
    img_mask_crf = dense_crf(np.array(img0), np.array(img00))
  File "/media/Linux/sun/unet-master/unet-master/unet-master/utils/crf.py", line 18, in dense_crf
    d.setUnaryEnergy(U)
  File "pydensecrf/densecrf.pyx", line 80, in pydensecrf.densecrf.DenseCRF.setUnaryEnergy (pydensecrf/densecrf.cpp:3370)
ValueError: Does not understand character buffer dtype format string ('e')
It can be seen that my two input images should be no problem, but it seems does not conform to the input requirements of CRF function!
So, I convert my mask image to the.npy file.
Feed to the CRF function again, the function runs.
However, from the output of the results, this calculation is also a failure!!
*****************mask_image*******************
[[ 0.34307694  0.25254577  0.19556901 ...,  0.06595198  0.12270801
   0.20498461]
 [ 0.27618128  0.23008606  0.17581019 ...,  0.04315171  0.06496601
   0.10133726]
 [ 0.24400418  0.21350899  0.13050212 ...,  0.02899374  0.03430962
   0.04988175]
 ...,
 [ 0.47824165  0.45803908  0.4359895  ...,  0.51509374  0.43747255
   0.39037436]
 [ 0.43725255  0.44684029  0.44850186 ...,  0.48320094  0.44397473
   0.41795644]
 [ 0.40656748  0.38304046  0.35984883 ...,  0.34599233  0.36646444
   0.41143322]]
******************crf_image*****************
[[0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 ...,
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]]
Part of my code is like this, maybe it's convenient for you to help me analyze the wrong reasons!
imgs_npy = np.load('imgs_mask_test_1.npy')            
imgs_npy = imgs_npy.reshape(512,-1)
     
print("*******************src_image***************") 
img_src = cv2.imread('2002.jpg')
print(img0)    
print("*****************mask_image*******************") 
#img_mask = cv2.imread('../results/img_mask0.jpg') 
print(imgs_npy)  
print("******************crf_image*****************") 
img_mask_crf = dense_crf(np.array(img0), imgs_npy)
print(img_mask_crf)
What's the problem? I can't think of it!
I hope you can help me to solve this problem again.thanks!!!!!!

**Comment by sunbin1205** [comment]
I'm so sorry to bother you again.
But this problem is never solved and it bothers me!!
So I have to explain to you again my problems and identify some questions:

The two inputs of the dense_srf function are two image formats or are they converted to array type input?
Because I see np.array in your function, but no matter which form will have the following error!
****src_image
[[[126 141 129]
[ 95 111 97]
[ 86 100 83]
...,
[ 82 98 77]
[ 81 98 77]
[ 71 86 66]]
[[134 152 138]
[122 140 125]
[118 135 119]
...,
[ 88 108 84]
[ 90 110 86]
[ 86 103 80]]

[[123 137 124]
[147 162 148]
[124 142 126]
...,
[ 89 108 84]
[ 96 116 90]
[ 85 102 80]]

...,
[[108 124 110]
[ 92 110 92]
[ 93 106 88]
...,
[113 130 107]
[111 128 105]
[111 128 111]]

[[166 181 178]
[144 162 155]
[137 157 147]
...,
[121 136 113]
[119 134 106]
[122 133 112]]

[[118 135 130]
[128 144 139]
[134 149 143]
...,
[ 68 80 60]
[ 85 99 80]
[ 97 109 95]]]
mask_image**
[[[161 161 161]
[130 130 130]
[100 100 100]
...,
[ 32 32 32]
[ 63 63 63]
[ 94 94 94]]

[[141 141 141]
[112 112 112]
[ 84 84 84]
...,
[ 15 15 15]
[ 35 35 35]
[ 57 57 57]]

[[117 117 117]
[ 93 93 93]
[ 68 68 68]
...,
[ 7 7 7]
[ 14 14 14]
[ 25 25 25]]

...,
[[227 227 227]
[233 233 233]
[219 219 219]
...,
[251 251 251]
[225 225 225]
[191 191 191]]

[[213 213 213]
[215 215 215]
[214 214 214]
...,
[232 232 232]
[212 212 212]
[204 204 204]]

[[201 201 201]
[186 186 186]
[173 173 173]
...,
[171 171 171]
[176 176 176]
[205 205 205]]]
crf_image
/media/Linux/sun/unet-master/unet-master/unet-master/utils/crf.py:13: RuntimeWarning: divide by zero encountered in log
U = -np.log(output_probs)
Traceback (most recent call last):
File "test_predict.py", line 41, in 
img_mask_crf = dense_crf(np.array(img0), np.array(img00))
File "/media/Linux/sun/unet-master/unet-master/unet-master/utils/crf.py", line 18, in dense_crf
d.setUnaryEnergy(U)
File "pydensecrf/densecrf.pyx", line 80, in pydensecrf.densecrf.DenseCRF.setUnaryEnergy (pydensecrf/densecrf.cpp:3370)
ValueError: Does not understand character buffer dtype format string ('e')

It can be seen that my two input images should be no problem, but it seems does not conform to the input requirements of CRF function!
So, I convert my mask image to the.npy file.
Feed to the CRF function again, the function runs.
However, from the output of the results, this calculation is also a failure!!

mask_image*
[[ 0.34307694 0.25254577 0.19556901 ..., 0.06595198 0.12270801
0.20498461]
[ 0.27618128 0.23008606 0.17581019 ..., 0.04315171 0.06496601
0.10133726]
[ 0.24400418 0.21350899 0.13050212 ..., 0.02899374 0.03430962
0.04988175]
...,
[ 0.47824165 0.45803908 0.4359895 ..., 0.51509374 0.43747255
0.39037436]
[ 0.43725255 0.44684029 0.44850186 ..., 0.48320094 0.44397473
0.41795644]
[ 0.40656748 0.38304046 0.35984883 ..., 0.34599233 0.36646444
0.41143322]]
*crf_image
[[0 0 0 ..., 0 0 0]
[0 0 0 ..., 0 0 0]
[0 0 0 ..., 0 0 0]
...,
[0 0 0 ..., 0 0 0]
[0 0 0 ..., 0 0 0]
[0 0 0 ..., 0 0 0]]

Part of my code is like this, maybe it's convenient for you to help me analyze the wrong reasons!
imgs_npy = np.load('imgs_mask_test_1.npy')
imgs_npy = imgs_npy.reshape(512,-1)

print("**src_image")
img_src = cv2.imread('2002.jpg')
print(img0)
print("mask_image")
#img_mask = cv2.imread('../results/img_mask0.jpg')
print(imgs_npy)
print("*crf_image")
img_mask_crf = dense_crf(np.array(img0), imgs_npy)
print(img_mask_crf)


What's the problem? I can't think of it!
I hope you can help me to solve this problem again.thanks!!!!!!

**Comment by milesial** [comment]
I don't see any problems with your arrays dimensions. However, the mask image should have values between 0 and 1 (floating point), because those are regarded as probabilities by CRF. Make sure the input image and mask are both float ndarrays. The values of the input image should be between 0 and 255 if I remember correctly.

**Comment by sunbin1205** [comment]
0 ~ 1?
Maybe that's the problem?
In order to see where the problem went wrong, I visualized every step of the CRF function.
I've found that one of the problems is that after the statement     U = -np.log(output_probs)  in the dense_crf function is running, there is a decimal in the floating point matrix greater than 1, is that the problem?The partial display is as follows
*******************dense_crf_3***************
<pydensecrf.densecrf.DenseCRF2D object at 0x7f31bc0833f0>
*******************dense_crf_4***************
[[[ 0.42018837  0.2910822   0.21762013 ...,  0.06822746  0.13091542
    0.2293938 ]
  [ 0.32321429  0.26147658  0.19335446 ...,  0.04411045  0.06717241
    0.10684746]
  [ 0.27971944  0.24017395  0.13983937 ...,  0.02942235  0.03491202
    0.05116884]
  ...,
  [ 0.65055078  0.61256135  0.57268238 ...,  0.72379971  0.57531542
    0.49491024]
  [ 0.57492429  0.59210849  0.59511673 ...,  0.66010106  0.58694154
    0.54121006]
  [ 0.52183175  0.48295176  0.44605097 ...,  0.42463619  0.45643914
    0.53006488]]

 [[ 1.0698005   1.37616277  1.63184202 ...,  2.71882844  2.0979476
    1.58482039]
  [ 1.28669786  1.46930182  1.73835039 ...,  3.14303303  2.73389101
    2.28930116]
  [ 1.41056991  1.54407632  2.03636575 ...,  3.54067516  3.37232947
    2.99810004]
  ...,
look forward your reply!thanks

**Comment by milesial** [comment]
Yes, as these are probabilities, they have to be between 0 and 1. In my `predict.py`, I applied a sigmoid to the output mask in order to get a [0, 1] range, before passing it to the CRF. That should fix it.

**Comment by sunbin1205** [comment]
thanks for your help!
