### ISSUE TITLE
why I got bad result

### ISSUE THREAD

**Issue by hac135** [milesial/Pytorch-UNet#53]
![result2](https://user-images.githubusercontent.com/17588948/56189778-5d975500-605b-11e9-883c-371da9e2fa3c.png)

**Comment by hac135** [comment]
I just download the program and use predict.py

**Comment by milesial** [comment]
It seems that your image is not from the Carvana dataset, so maybe you could fine-tune the model and train it with your images so it can adapt to the new background and lighting.

**Comment by hac135** [comment]
thanks, so this Unet can only works well on Carvana dataset ?

**Comment by milesial** [comment]
If you use the `MODEL.pth` yes because those are the weights that I trained on Carvana. Of course the model can be used on many tasks and datasets if it is retrained from scratch. See `train.py`.
