### ISSUE TITLE
custom dataset 

### ISSUE THREAD

**Issue by vcvishal** [milesial/Pytorch-UNet#54]
when i run with my own dataset  predicted image i white

**Comment by milesial** [comment]
Please specify your problem so I can help you.. What dataset are you trying to train on ?

**Comment by vcvishal** [comment]
i am using dataset provided by https://github.com/zhixuhao/unet
i set number of channel to 1 and image type .png but this gives error below 
Starting training:
        Epochs: 1
        Batch size: 1
        Learning rate: 0.1
        Training size: 57
        Validation size: 3
        Checkpoints: True
        CUDA: False

Starting epoch 1/1.
Traceback (most recent call last):
  File "train.py", line 139, in <module>
    img_scale=args.scale)
  File "train.py", line 75, in train_net
    masks_pred = net(imgs)
  File "D:\miniconda\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\vcvis\Desktop\Pytorch-UNet-master ok\unet\unet_model.py", line 22, in forward
    x1 = self.inc(x)
  File "D:\miniconda\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\vcvis\Desktop\Pytorch-UNet-master ok\unet\unet_parts.py", line 32, in forward
    x = self.conv(x)
  File "D:\miniconda\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\vcvis\Desktop\Pytorch-UNet-master ok\unet\unet_parts.py", line 22, in forward
    x = self.conv(x)
  File "D:\miniconda\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\miniconda\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
    input = module(input)
  File "D:\miniconda\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\miniconda\lib\site-packages\torch\nn\modules\conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [64, 3, 3, 3], expected input[1, 256, 256, 1] to have 3 channels, but got 256 channels instead


again when i used isic dataset it gives blank (white) image

i am new please guide me what are the changes i should make for correct output
help me
thank you

**Comment by milesial** [comment]
Make sure your input images are correctly loaded with good dimensions, with a batch dimension first and the channel dimension last (1 in your case if the images are loaded as grey). If you don't have the channel dimension (given the error, that may be it) you have to call `torch.unsqueeze` on the tensors first.

**Comment by vcvishal** [comment]
thank you for reply 
would you please guide me where to edit code for torch.unsqueeze and what are values pass to it

**Comment by milesial** [comment]
You can try to add `imgs = imgs.unsqueeze(-1)` before [this line](https://github.com/milesial/Pytorch-UNet/blob/e2e46ce509382a45b1db4e1f639aeed568f6cb3e/train.py#L75). If it doesn't work, give me the output of `print(imgs.shape)`

**Comment by vcvishal** [comment]
first of all sorry to disturb you again  and again, 
first i place imgs=imgs.unsqueeze(-1) in side if gpu block, it runs with negative loss on cpu, when i try to run it on gpu it gives error i am attatching images what i did and got
![cpu run when unsqueeze inside if gpu block](https://user-images.githubusercontent.com/49521759/56947865-09f13500-6b4c-11e9-8f2e-2ff43847412c.png)
![when run on gpu](https://user-images.githubusercontent.com/49521759/56947866-0a89cb80-6b4c-11e9-9375-ccbfa06965fb.png)
![when squeeze before](https://user-images.githubusercontent.com/49521759/56947870-0bbaf880-6b4c-11e9-9b8a-327fd987a325.png)
i hope you will help 
thank you

**Comment by vcvishal** [comment]
sorry, it did not works and also sorry for disturb again again
first i only insert the code as you said i have a attached code and output image
second i modify utils.py, i also attached that output and code image 
i hope you help me
![unsqueeze with original code](https://user-images.githubusercontent.com/49521759/56950948-34df8700-6b54-11e9-9738-6ebcbdf87903.png)
![unsqueez with modification in util](https://user-images.githubusercontent.com/49521759/56950951-3610b400-6b54-11e9-80d2-c70ad009a64e.jpg)

what should i do, the only dataset i am using provided by https://github.com/zhixuhao/unet
thank you

**Comment by milesial** [comment]
Remove the `unsqueeze` it is not needed, and replace the line in `utils.py` with : `return np.transpose(img[:,:,np.newaxis], axes=[2, 0, 1])`.

**Comment by vcvishal** [comment]
thank you it runs but there are two problem 
1 negative loss
2 blank out put 
i am attaching image, ground truth and also output i got
thank you
![0_OUT](https://user-images.githubusercontent.com/49521759/56960702-54d07400-6b6f-11e9-858f-b3d4f6e9fb42.png)
![0](https://user-images.githubusercontent.com/49521759/56960703-55690a80-6b6f-11e9-9fda-0ad4b3a476ca.png)
![0](https://user-images.githubusercontent.com/49521759/56960710-5b5eeb80-6b6f-11e9-96fe-41f28a0b94db.png)

first image is blank 
second is original image 
and third is its ground truth
guide me
thank you

**Comment by milesial** [comment]
I can't help you much more, it's specific to your dataset. Make sure your masks are correctly loaded. The loss can't be negative so you have to debug that first, and then see if the output is still blank.

**Comment by vcvishal** [comment]
thank you
