### ISSUE TITLE
 Target and input must have the same number of elements

### ISSUE THREAD

**Issue by yangpeng1995** [milesial/Pytorch-UNet#58]
`criterion = torch.nn.BCELoss()
loss = criterion(masks_pred,true_masks)
`
E:\pythonProject\MyDL2\U_net2>python main.py
Starting training:num_epochs:50,Batch_size:2
Epoch 1/50
----------
imgs_size:torch.Size([2, 3, 256, 256])
masks_size:torch.Size([2, 3, 256, 256])
C:\Users\yp\Anaconda3\lib\site-packages\torch\nn\modules\loss.py:512: UserWarning: Using a target size (torch.Size([2, 3, 256, 256])) that is different to the input size (torch.Size([2, 1, 256, 256])) is deprecated. Please ensure they have the same size.
  return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
Traceback (most recent call last):
  File "main.py", line 120, in <module>
    train()
  File "main.py", line 109, in train
    train_model(model,criterion, optimizer, scheduler, train_dataload, valid_dataload,num_epochs)
  File "main.py", line 53, in train_model
    loss = criterion(masks_pred,true_masks)
  File "C:\Users\yp\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\yp\Anaconda3\lib\site-packages\torch\nn\modules\loss.py", line 512, in forward
    return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
  File "C:\Users\yp\Anaconda3\lib\site-packages\torch\nn\functional.py", line 2106, in binary_cross_entropy
    "!= input nelement ({})".format(target.numel(), input.numel()))
ValueError: Target and input must have the same number of elements. target nelement (393216) != input nelement (131072)

**input size equal image size ? if so , why is target size different to the input size?**

**Comment by milesial** [comment]
Make sûre you created the net with the right number of classes. It seems you loaded your masks with 3 channels, do you have 3 classes + background ?

**Comment by cruigo93** [comment]
hello! Have the same problem, it's not clear for me how to use it. For example, I have mask in png which contain only 0 and 255 and 3 channels image. If I try n_channels=3, n_classes=3 it kinda works but with strange behavior of loss while score is increasing. Can someone explain me what I do wrong?

**Comment by yangpeng1995** [comment]
My problem has been solved .Maybe you can try change you mask's channel to single channel such as "mask = Image.open("xxx").convert('L')".Good lucjk!



------------------ 原始邮件 ------------------
发件人: "cruigo93"<notifications@github.com>; 
发送时间: 2019年5月28日(星期二) 晚上6:31
收件人: "milesial/Pytorch-UNet"<Pytorch-UNet@noreply.github.com>; 
抄送: "平常心"<www.yp1995@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [milesial/Pytorch-UNet]  Target and input must have the samenumber of elements (#58)




hello! Have the same problem, it's not clear for me how to use it. For example, I have mask in png which contain only 0 and 255 and 3 channels image. If I try n_channels=3, n_classes=3 it kinda works but with strange behavior of loss while score is increasing. Can someone explain me what I do wrong?

**Comment by yangpeng1995** [comment]
Thank you for your answer.I got it.



------------------ 原始邮件 ------------------
发件人: "milesial"<notifications@github.com>; 
发送时间: 2019年5月27日(星期一) 晚上8:48
收件人: "milesial/Pytorch-UNet"<Pytorch-UNet@noreply.github.com>; 
抄送: "平常心"<www.yp1995@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [milesial/Pytorch-UNet]  Target and input must have the samenumber of elements (#58)




Make sûre you created the net with the right number of classes. It seems you loaded your masks with 3 channels, do you have 3 classes + background ?

**Comment by JessicaDuFirst** [comment]
I met the same problem, but your solution can not sovle my problem:"
in binary_cross_entropy
    "!= input nelement ({})".format(target.numel(), input.numel()))
ValueError: Target and input must have the same number of elements. target nelement (230400) != input nelement (460800)"

Please help me . my mask is already one channel
