### ISSUE TITLE
Do you need large GPU memory?

### ISSUE THREAD

**Issue by kyuusaku** [milesial/Pytorch-UNet#6]
Hi, I ran the code. I used the new Pytorch 0.4.0. I found it needs large GPU memory. Batchsize=4 uses 10G memory. Is it right?

**Comment by Mastercorp** [comment]
Yeah, sounds right. Depending on your inputimage size you can not fit a lot of images on the memory.

**Comment by milesial** [comment]
Seems correct, I trained with a batch size of 1 I think and I barely maxed out my 3GB memory. Consider rescaling your images even more if you want to train quicker.
