### ISSUE TITLE
CUDA Out of memory

### ISSUE THREAD

**Issue by Arktius** [milesial/Pytorch-UNet#61]
Hej man,

I've just downloaded your repo and wanted to make familiar with the training script, but I got this error displayed.

python train.py -g

    Starting training:
        Epochs: 5
        Batch size: 10
        Learning rate: 0.1
        Training size: 61
        Validation size: 3
        Checkpoints: True
        CUDA: True

> Starting epoch 1/5.
> Traceback (most recent call last):
>   File "train.py", line 139, in <module>
>     img_scale=args.scale)
>   File "train.py", line 75, in train_net
>     masks_pred = net(imgs)
>   File "C:\Users\Admin\Anaconda3\envs\docupars\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
>     result = self.forward(*input, **kwargs)
>   File "F:\Pytorch-UNet-master\Pytorch-UNet-master\unet\unet_model.py", line 22, in forward
>     x1 = self.inc(x)
>   File "C:\Users\Admin\Anaconda3\envs\docupars\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
>     result = self.forward(*input, **kwargs)
>   File "F:\Pytorch-UNet-master\Pytorch-UNet-master\unet\unet_parts.py", line 32, in forward
>     x = self.conv(x)
>   File "C:\Users\Admin\Anaconda3\envs\docupars\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
>     result = self.forward(*input, **kwargs)
>   File "F:\Pytorch-UNet-master\Pytorch-UNet-master\unet\unet_parts.py", line 22, in forward
>     x = self.conv(x)
>   File "C:\Users\Admin\Anaconda3\envs\docupars\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
>     result = self.forward(*input, **kwargs)
>   File "C:\Users\Admin\Anaconda3\envs\docupars\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
>     input = module(input)
>   File "C:\Users\Admin\Anaconda3\envs\docupars\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
>     result = self.forward(*input, **kwargs)
>   File "C:\Users\Admin\Anaconda3\envs\docupars\lib\site-packages\torch\nn\modules\batchnorm.py", line 83, in forward
>     exponential_average_factor, self.eps)
>   File "C:\Users\Admin\Anaconda3\envs\docupars\lib\site-packages\torch\nn\functional.py", line 1697, in batch_norm
>     training, momentum, eps, torch.backends.cudnn.enabled
> RuntimeError: CUDA out of memory. Tried to allocate 1000.00 MiB (GPU 0; 8.00 GiB total capacity; 3.04 GiB already allocated; 2.98 GiB free; 13.10 MiB cached)

NVIDIA-smi:

> 
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 431.36       Driver Version: 431.36       CUDA Version: 10.1     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |===============================+======================+======================|
> |   0  GeForce RTX 206... WDDM  | 00000000:01:00.0  On |                  N/A |
> | 34%   44C    P8    19W / 175W |    477MiB /  8192MiB |     12%      Default |
> +-------------------------------+----------------------+----------------------+
> 
> +-----------------------------------------------------------------------------+
> | Processes:                                                       GPU Memory |
> |  GPU       PID   Type   Process name                             Usage      |
> |=============================================================================|
> |    0      1544    C+G   Insufficient Permissions                   N/A      |
> |    0      3236    C+G   ...t_cw5n1h2txyewy\ShellExperienceHost.exe N/A      |
> |    0      6916    C+G   C:\Windows\explorer.exe                    N/A      |
> |    0      9064    C+G   P:\FireFox\firefox.exe                     N/A      |
> |    0     10976    C+G   P:\FireFox\firefox.exe                     N/A      |
> |    0     11564    C+G   ...48.51.0_x64__kzf8qxf38zg5c\SkypeApp.exe N/A      |
> |    0     11796    C+G   ...dows.Cortana_cw5n1h2txyewy\SearchUI.exe N/A      |
> |    0     12652    C+G   ...hell.Experiences.TextInput.InputApp.exe N/A      |
> |    0     13096    C+G   ...DIA GeForce Experience\NVIDIA Share.exe N/A      |
> |    0     15380    C+G   ...10.540.0_x86__zpdnekdrzrea0\Spotify.exe N/A      |
> +-----------------------------------------------------------------------------+

There should be enough memory to store the data. 

Thanks in advance for any advice.

**Comment by milesial** [comment]
I can't really help you on that, it may be specific to your GPU or drivers. Try reducing the batch size until it works, maybe.

**Comment by panda1040** [comment]
The same as me, i reducing the batch size from 8 to 4 so it can working. Beside, my GPU is GTX1070.

**Comment by Arktius** [comment]
A batch size of 1 works on my 8GB card. Everything above not surprisingly. I'm working with images of size 1000x1000 pixels and I thing the largest one has 800KB!

**Comment by SpaceView** [comment]
> A batch size of 1 works on my 8GB card. Everything above not surprisingly. I'm working with images of size 1000x1000 pixels and I thing the largest one has 800KB!
I got the same problem when I start the training test as described with Kaggle images in GTX1080i, batch_size can only be 1.

**Comment by AlexRenl** [comment]
I got the same problem.  I use 1080Ti, and batch size is only 1. Still out of memory...

**Comment by Arktius** [comment]
> I got the same problem. I use 1080Ti, and batch size is only 1. Still out of memory...

Close all other applications, use just a single monitor at 1080P. I had my TV connected last time and took quite a lot of VRAM.

**Comment by Belval** [comment]
Just another data point here:

I cloned the project and training on my GTX 1080Ti with 10GB of free VRAM crashes with `-b 1`. I had to set downscaling to 0.2 to make it work. Images are all < 1000x1000 pixels.

**Comment by ActonMartin** [comment]
THe batch size is one already! When I change the downscaling to 0.2. It works.
