### ISSUE TITLE
could not broadcast input array from shape (3,384,384) into shape (3)

### ISSUE THREAD

**Issue by AbnerAi** [milesial/Pytorch-UNet#63]
Hi,  When I run “imgs =  np.array([i[0] for i in b]).astype(np.float32)”  In train.py，ValueError: could not broadcast input array from shape (3,384,384) into shape (3)
My input training set is 3 channels，I don't know where the problem is?

**Comment by AbnerAi** [comment]
The size of my training set image is arbitrary, not the same...
For example: 1022*767 1504*1129 2048*1536
2272*1704 722*542 and so on

**Comment by AbnerAi** [comment]
The possible answer is that the numpy arry in the list must also be the same size. Can't I load training sets of different sizes? Must the image size of the training set be exactly the same?

**Comment by milesial** [comment]
Yes all the images and masks should be the same size in order to fit into arrays and tensor, you should resize them before the data loading.

**Comment by AbnerAi** [comment]
thanks

**Comment by AbnerAi** [comment]
> Yes all the images and masks should be the same size in order to fit into arrays and tensor, you should resize them before the data loading.

thanks.
