### ISSUE TITLE
what is the performance of the given model trained on your dataset?

### ISSUE THREAD

**Issue by zst1992** [milesial/Pytorch-UNet#64]
Hi, thank you very much for your code. what is the performance of the given model (model.pth) on your own dataset. Thank you very much and have a good day.

**Comment by milesial** [comment]
Hi, as stated in the readme, I obtained a dice coefficient of 0.988423 with `model.pth` on the Carvana dataset. This was before fixing a data loading bug ( https://github.com/milesial/Pytorch-UNet/commit/a357099e4eace375489f18babb2947d9103733fd ), so I was only training on the left squares of images. Now the performance should be better but I haven't retrained the model.
