### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'tuple' and 'int'

### ISSUE THREAD

**Issue by AbnerAi** [milesial/Pytorch-UNet#66]
Hi,milesial  happy weekend!

Traceback (most recent call last):
  File "train.py", line 133, in <module>
    img_scale=args.scale)
  File "train.py", line 77, in train_net
    print('{0:.4f} --- loss: {1:.6f}'.format(i * batch_size / N_train, loss.item()))
TypeError: unsupported operand type(s) for /: 'tuple' and 'int'
 print('Epoch finished ! Loss: {}'.format(epoch_loss / i))

I found that i is a tuble type, so why do you make tuble and int do four arithmetic operations here? I found that no one mentioned this question. Is it wrong for me?

**Comment by milesial** [comment]
Hi, the `i` is defined here :
https://github.com/milesial/Pytorch-UNet/blob/e2e46ce509382a45b1db4e1f639aeed568f6cb3e/train.py#L64
so it should not be a tuple. Are you on python 3 ?
