### ISSUE TITLE
Why use padding=1 not 0?

### ISSUE THREAD

**Issue by shoujieqiu** [milesial/Pytorch-UNet#68]
I saw the net  architecture in paper,and size of image changes 572->570->568,why use padding=1 not 0 when kernel_size=3?

**Comment by milesial** [comment]
With padding the edges are not lost from the convolution, so it should always be better. I suppose if you want to strictly follow the paper, you should remove the padding, and lose 1 pixel for each edge and for each convolution.

**Comment by shoujieqiu** [comment]
thanks for your reply!
