### ISSUE TITLE
loss is negative

### ISSUE THREAD

**Issue by booyoungxu** [milesial/Pytorch-UNet#7]
Hi,
Thanks for your open-source code of your project. I have few questions when I use my private data to tain the model, I resize my data to [256, 128] and get negative loss and very large like this.
![image](https://user-images.githubusercontent.com/22422251/40101000-9517981e-5918-11e8-8170-ddaa06def00e.png
Is this normal？If not, how can I fix that? 
Looking forward to your reply!

**Comment by booyoungxu** [comment]
Thanks for your reply. My target values are not between 0 and 1. Hope after I fixed, it will work~

**Comment by Gumballing** [comment]
@booyoungxu 
Hello,I have the same error as you.The loss was always about -2000 or -3000.
![image](https://user-images.githubusercontent.com/37538696/61290940-a815a280-a7ff-11e9-81ee-c47d7a142593.png)
Have you fixed it?How did you do it?
Looking forward to your reply.

**Comment by AbnerAi** [comment]
> @booyoungxu
> Hello,I have the same error as you.The loss was always about -2000 or -3000.
> ![image](https://user-images.githubusercontent.com/37538696/61290940-a815a280-a7ff-11e9-81ee-c47d7a142593.png)
> Have you fixed it?How did you do it?
> Looking forward to your reply.

I also have the same problem, how can I solve it? I look forward to your reply!
