### ISSUE TITLE
Why the predicted image's background is black?

### ISSUE THREAD

**Issue by W998K** [milesial/Pytorch-UNet#70]
Hi , I want to consult you why the background of my predicted image is black? how can I to improve it?

**Comment by milesial** [comment]
Could you please detail you problem ? What dataset are you training on ? Have you checked the true masks are loaded correctly ?

**Comment by 960725** [comment]
Can you leave a contact?  You can add me 741032241@qq.com

**Comment by shijianjian** [comment]
Can you elaborate more? What I am thinking is that it is probably caused by the value ranges. Please make sure you are using either 0-1 range or 0-255 range. The predicted value may have a wrong scale if you are not using sigmoid.
