### ISSUE TITLE
Error in merge_masks

### ISSUE THREAD

**Issue by mira-murali** [milesial/Pytorch-UNet#72]
I wrote a custom Pytorch Dataloader to take in images of size `(720, 1280)`, scale them by 0.5 so `(360, 640)` and my masks are of dimensions `(360, 640, 2)` in HWC format.

During testing predict.py throws an error here:
```new[:, :full_w // 2 +1] = img1[:, :full_w // 2+1]```
The error is:
`ValueError: could not broadcast input array from shape (2,641,720) into shape (2,641)`

Because `img1` has shape `(2, 641, 720)` and new has shape `(2, 641)` because of the CWH format of `img1`. 

If I do try to change that code snippet to work for my data, I get the following error:
`ValueError: Bad shape for unary energy (Need (2, 2560), got (2, 1843200))`

Can anyone tell me why?

I changed the indexing here ```new[:, :full_w // 2 +1] = img1[:, :full_w // 2+1]``` to ```new[:, :full_w // 2] = img1[:, :full_w // 2]``` so my dimensions would be even, but I don't understand why the indexing is including the end index as well in the first place, i.e., `img1[:3]` should only take values at indices `[0, 1, 2]`. Why does this particular indexing also include the last index?

Thank you.

**Comment by milesial** [comment]
The `merge_mask` was intended to be used for only one classes (C=1, HxW masks), so if you want to merge masks with more than 1 classes with HxWxC masks maybe you could try :

```
h = img1.shape[0]
c = img1.shape[2]
new = np.zeros((h, full_w, c), np.float32)
new[:, :full_w // 2 + 1, :] = img1[:, :full_w // 2 + 1, :]
new[:, full_w // 2 + 1:, :] = img2[:, -(full_w // 2 - 1):, :]
```

If you still got errors with the unary energy, you can disable dense_crf in `predict.py`

**Comment by mira-murali** [comment]
Thanks for the quick response!
I did try doing that and disabling dense_crf but the result was just a black image.

**Comment by milesial** [comment]
Yes I think you should try other hyper-parameters. The network ends with a sigmoid so the outputs should be probabilities. A threshold around 0.5 would make sense, 0.005 is too low.

**Comment by mira-murali** [comment]
Thanks! I realized I was using a very poor model. I changed the model I was using, and the output was much better with a threshold of 0.5.

**Comment by milesial** [comment]
Nice!
