### ISSUE TITLE
ValueError: Target and input must have the same number of elements. target nelement (1373880) != input nelement (457960)

### ISSUE THREAD

**Issue by huskyachao** [milesial/Pytorch-UNet#76]
Hellow, when I use my own training data (train: 0001~0500.png，mask:0001~0500.png, both 542*428pixel)  to run the train.py， I get this error.   I would be grateful if anyone can help me. The blow is what I ran and what I got:
#########################################
Achaos@admin:~/Pytorch-UNet$ python3 train.py

    Starting training:
        Epochs: 5
        Batch size: 10
        Learning rate: 0.1
        Training size: 950
        Validation size: 50
        Checkpoints: True
        CUDA: False

Starting epoch 1/5.
/home/Achaos/.local/lib/python3.6/site-packages/torch/nn/functional.py:1351: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
/home/Achaos/.local/lib/python3.6/site-packages/torch/nn/modules/loss.py:498: UserWarning: Using a target size (torch.Size([1373880])) that is different to the input size (torch.Size([457960])) is deprecated. Please ensure they have the same size.
  return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
Traceback (most recent call last):
  File "train.py", line 139, in <module>
    img_scale=args.scale)
  File "train.py", line 80, in train_net
    loss = criterion(masks_probs_flat, true_masks_flat)
  File "/home/Achaos/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/Achaos/.local/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 498, in forward
    return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
  File "/home/Achaos/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 2058, in binary_cross_entropy
    "!= input nelement ({})".format(target.numel(), input.numel()))
ValueError: Target and input must have the same number of elements. target nelement (1373880) != input nelement (457960)
#################################

**Comment by milesial** [comment]
Hi, 
- how many classes do you have?
- how are you loading your masks (how many channels are in the loaded matrices)?

**Comment by huskyachao** [comment]
I set channels = 3, and classes = 1. But I doubt it is right for me because i don't understand what the class means in my situation. 
My goal : I want to training the model with two kinds of pictures ( for example, imgs = A, masks = B) to learn the inner relationship between them, and predict one kind of them with the other. Pictures in A are RGB .png and pictures in B are Gray .png (I used the ''im = resize_and_crop(Image.open(dir + id + suffix).convert('L') '' to trans RGB to Gray for pictures in B).  
Q: So am I right to set only one class?  If not, how to train the model to get what I want?  It bothers me a lot.

**Comment by milesial** [comment]
Yes if your masks are grey then you have n_classes = 1 (one probability per pixel)

**Comment by huskyachao** [comment]
> Yes if your masks are grey then you have n_classes = 1 (one probability per pixel)

what about a mask of RGB?  n_classes = 3?

**Comment by milesial** [comment]
Yes that's it: 3 classes = 3 channels for the mask

**Comment by huskyachao** [comment]
> Yes that's it: 3 classes = 3 channels for the mask

when I change n_classes =3, and run with "python3 train.py -e 10 -b 4 -l 0.01 -g -s 1
" I meet with a new problem:
##############
Traceback (most recent call last):
  File "train.py", line 140, in <module>
    img_scale=args.scale)
  File "train.py", line 92, in train_net
    val_dice = eval_net(net, val, gpu)
  File "/home/Achaos/Pytorch-UNet/eval.py", line 25, in eval_net
    tot += dice_coeff(mask_pred, true_mask).item()
  File "/home/Achaos/Pytorch-UNet/dice_loss.py", line 40, in dice_coeff
    s = s + DiceCoeff().forward(c[0], c[1])
  File "/home/Achaos/Pytorch-UNet/dice_loss.py", line 10, in forward
    self.inter = torch.dot(input.view(-1), target.view(-1))
RuntimeError: invalid argument 2: sizes do not match at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:25

**Comment by milesial** [comment]
Yes, the dice coefficient makes no sense for multiclass, you can read about it on wikipedia. You have to find another way to evaluate the network.
