### ISSUE TITLE
F.interpolate is a function not a class

### ISSUE THREAD

**Issue by CXMANDTXW** [milesial/Pytorch-UNet#77]
In unet_parts.py,line 57.
self.up = F.interpolate(scale_factor=2, mode='bilinear', align_corners=True)
I am confused about F.interpolate is a function not a class,it doesn't seem to work.
Error:
self.up = F.interpolate(scale_factor=2, mode='bilinear', align_corners=True)
TypeError: interpolate() missing 1 required positional argument: 'input'

**Comment by milesial** [comment]
unet_parts.py line 57 reads:
https://github.com/milesial/Pytorch-UNet/blob/e2e46ce509382a45b1db4e1f639aeed568f6cb3e/unet/unet_parts.py#L55-L58

I am not using `F.interpolate`, where did you get that ?

**Comment by CXMANDTXW** [comment]
sorry,my bad,It should be that I changed this wrong.
