### ISSUE TITLE
UserWarning: Using a target size (torch.Size([1, 3, 224, 224])) that is different to the input size (torch.Size([1, 7, 224, 224])) is deprecated. Please ensure they have the same size.

### ISSUE THREAD

**Issue by bilibili2007** [milesial/Pytorch-UNet#79]
Hello!milesial!
I have a problem for you.
My image and my mask have 3 channels.I want to be able to separate 7 possibilities.
So,I set n_channels=3 and n_classes=7.
but I get this error:
`
INFO: Using device cuda
INFO: Network:
	3 input channels
	7 output channels (classes)
	Bilinear upscaling
INFO: Starting training:
        Epochs:          5
        Batch size:      1
        Learning rate:   0.1
        Training size:   738
        Validation size: 130
        Checkpoints:     True
        Device:          cuda
        Images scaling:  1
    
Epoch 1/5:   0%|                                       | 0/738 [00:00<?, ?img/s]/home/nvidia/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/loss.py:498: UserWarning: Using a target size (torch.Size([1, 3, 224, 224])) that is different to the input size (torch.Size([1, 7, 224, 224])) is deprecated. Please ensure they have the same size.
  return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)

Traceback (most recent call last):
  File "train.py", line 158, in <module>
    val_percent=args.val / 100)
  File "train.py", line 70, in train_net
    loss = criterion(masks_pred, true_masks)
  File "/home/nvidia/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nvidia/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 498, in forward
    return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
  File "/home/nvidia/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/functional.py", line 2044, in binary_cross_entropy
    "!= input nelement ({})".format(target.numel(), input.numel()))
ValueError: Target and input must have the same number of elements. target nelement (150528) != input nelement (351232)
`

How can I solve this problem？
I am looking forward to your reply:)

**Comment by milesial** [comment]
Hi, please pull the last commit on master.
You should not load your masks with 3 channels, but according to the documentation for the `target` parameter here: https://pytorch.org/docs/stable/nn.html#torch.nn.BCEWithLogitsLoss

**Comment by XUYUNYUN666** [comment]
RuntimeError: 1only batches of spatial targets supported (non-empty 3D tensors) but got targets of size: : [1, 1, 500, 636]   
if i use the grayscale masks,  there are so many problems about the target size and dimension in loss function

**Comment by DAVID-Hown** [comment]
UserWarning: Using a target size (torch.Size([96, 3, 224, 224])) that is different to the input size (torch.Size([96])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
