### ISSUE TITLE
can u provide the pre-trained modles in your research?

### ISSUE THREAD

**Issue by hanyeliu** [milesial/Pytorch-UNet#82]
Hi:
can u provide the pre-trained modles in your research?

**Comment by milesial** [comment]
Hi, the pretrained model was available for the commit https://github.com/milesial/Pytorch-UNet/tree/e2e46ce509382a45b1db4e1f639aeed568f6cb3e and before. After that, I cleaned up the code and the model and I don't think the same file will load. I will try to add a pretrained model for the new version in the future

**Comment by Branikas** [comment]
@hanyeliu I am trying to train a model right now, but its a slow process cause I m using a CPU instead of a GPU and my data are quite different than a typical natural scene segmentation so I don;t know if it will work for you.
However, if you want to try anyway, I can try and upload something.

**Comment by hanyeliu** [comment]
Thanks for your reply. I have the Gpu machine. and if i train your modles on the GPU machines, do i need to change something in your code?

**Comment by Branikas** [comment]
I meant I can provide a .pth file so that you can test on your own data.

**Comment by milesial** [comment]
@hanyeliu if you take my model from the previous commit it works on GPU

**Comment by hanyeliu** [comment]
@milesial @Branikas Thanks for your help!
