### ISSUE TITLE
Expected object of scalar type Byte but got scalar type Double for sequence element 5 in sequence argument at position #1 'tensors'

### ISSUE THREAD

**Issue by lovecsm** [milesial/Pytorch-UNet#88]
After I put the picture and mask in the corresponding directory, running tarin.py gets the following error message:
runfile('/home/joe/IdeaProjects/DeepLeaning/Unet/Pytorch-UNet/train.py', wdir='/home/joe/IdeaProjects/DeepLeaning/Unet/Pytorch-UNet')
INFO: Using device cuda
INFO: Network:
	{0} input channels
	1 output channels (classes)
	Bilinear
INFO: Creating dataset with 81 examples
INFO: Starting training:
        Epochs:          5
        Batch size:      20
        Learning rate:   0.1
        Training size:   73
        Validation size: 8
        Checkpoints:     True
        Device:          cuda
        Images scaling:  0.5
    
Epoch 0.2:   0%|          | 0/73 [00:00<?, ?img/s]
Traceback (most recent call last):
  File "/home/joe/Programs/anaconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-5ee5a186667e>", line 1, in <module>
    runfile('/home/joe/IdeaProjects/DeepLeaning/Unet/Pytorch-UNet/train.py', wdir='/home/joe/IdeaProjects/DeepLeaning/Unet/Pytorch-UNet')
  File "/home/joe/.IntelliJIdea2019.2/config/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/joe/.IntelliJIdea2019.2/config/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/joe/IdeaProjects/DeepLeaning/Unet/Pytorch-UNet/train.py", line 173, in <module>
    val_percent=args.val / 100)
  File "/home/joe/IdeaProjects/DeepLeaning/Unet/Pytorch-UNet/train.py", line 63, in train_net
    for batch in train_loader:
  File "/home/joe/Programs/anaconda3/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/joe/Programs/anaconda3/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/joe/Programs/anaconda3/lib/python3.5/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/joe/Programs/anaconda3/lib/python3.5/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/joe/Programs/anaconda3/lib/python3.5/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/joe/Programs/anaconda3/lib/python3.5/site-packages/torch/utils/data/_utils/collate.py", line 74, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/home/joe/Programs/anaconda3/lib/python3.5/site-packages/torch/utils/data/_utils/collate.py", line 74, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/home/joe/Programs/anaconda3/lib/python3.5/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: Expected object of scalar type Byte but got scalar type Double for sequence element 5 in sequence argument at position #1 'tensors'
Process finished with exit code 137 (interrupted by signal 9: SIGKILL)

Also, I didn't modify anything. How am I supposed to solve this problem?
Thanks.

**Comment by milesial** [comment]
Why does it say ` {0} input channels` if you haven't modified anything ? Are your input images RGB ?

**Comment by lovecsm** [comment]
> Why does it say ` {0} input channels` if you haven't modified anything ? Are your input images RGB ?
Thank you for your reply！！
ha-ha, the reason why it say `{0} input channels` is I was using python3.5, which does not support string templates, I changed all the log statements without affecting the program itself, it just like this:
```
logging.info('''Starting training:
        Epochs:          {0}
        Batch size:      {1}
        Learning rate:   {2}
        Training size:   {3}
        Validation size: {4}
        Checkpoints:     {5}
        Device:          {6}
        Images scaling:  {7}
    '''.format(epochs, batch_size, lr, n_train, n_val, save_cp, device.type, img_scale))
```
AND
```
net = UNet(n_channels=1, n_classes=1)
    log_txt = 'Network:\n' + '\t{0} input channels\n' + '\t{1} output channels (classes)\n'\
        .format(net.n_channels, net.n_classes) + ('\tBilinear' if net.bilinear else 'Dilated conv') + 'upscaling'
    logging.info(log_txt)
```
I used a gray image, so the number of channels I filled in was 1, but would it cause this error?

**Comment by milesial** [comment]
Mmh, can you try printing the type of `img` and `mask` after this line https://github.com/milesial/Pytorch-UNet/blob/7cb24a105aa4261eb6daafbb9b0552fd0fdf6fd1/utils/dataset.py#L59 ? Maybe the images are loaded as bytes instead of floats.

**Comment by lovecsm** [comment]
> Mmh, can you try printing the type of `img` and `mask` after this line
> 
> https://github.com/milesial/Pytorch-UNet/blob/7cb24a105aa4261eb6daafbb9b0552fd0fdf6fd1/utils/dataset.py#L59
> 
> ? Maybe the images are loaded as bytes instead of floats.

Well,  they are uint8. I got another error, when I converted the type of pixel to float64, so I am using python3.7, it working well.
Thanks for your guidance

**Comment by ImMial** [comment]
I got the same problem.
I used the nii file slice as input and made some changes to adapt such as channel.
```

    def preprocessnii(cls, pil_img, resize):
        pil_img = Image.fromarray(pil_img).resize(resize)
        img_nd = np.array(pil_img)

        if len(img_nd.shape) == 2:
            img_nd = np.expand_dims(img_nd, axis=2)

        # HWC to CHW
        img_trans = img_nd.transpose((2, 0, 1))
        if img_trans.max() > 1:
            img_trans = img_trans / 255

        return img_trans.astype(np.float64)
```
Don't know why but the output datatype is not always float32. So I solved the same problem by regular the output of process method.

**Comment by Venshao** [comment]
> I got the same problem.
> I used the nii file slice as input and made some changes to adapt such as channel.
> 
> ```
> 
>     def preprocessnii(cls, pil_img, resize):
>         pil_img = Image.fromarray(pil_img).resize(resize)
>         img_nd = np.array(pil_img)
> 
>         if len(img_nd.shape) == 2:
>             img_nd = np.expand_dims(img_nd, axis=2)
> 
>         # HWC to CHW
>         img_trans = img_nd.transpose((2, 0, 1))
>         if img_trans.max() > 1:
>             img_trans = img_trans / 255
> 
>         return img_trans.astype(np.float64)
> ```
> 
> Don't know why but the output datatype is not always float32. So I solved the same problem by regular the output of process method.

Good method, we used a similar solution.
