### ISSUE TITLE
what version of numpy is used,and what should be filled in this place？？？

### ISSUE THREAD

**Issue by duanliangtao** [milesial/Pytorch-UNet#89]
when i use the latest version of predict.py，something was wrong，It seems that I should fill some path in this place,but i don't what to fill in?
![image](https://user-images.githubusercontent.com/48194157/69838822-27c47b00-1290-11ea-8199-1d147567b41e.png)
can you tell what version of numpy do you use,when i use the latest version(v1.17.4),but it has no attribute 'unsqueeze':
![image](https://user-images.githubusercontent.com/48194157/69838929-7eca5000-1290-11ea-9b50-003372ee425d.png)
Look forward to your reply!!!

**Comment by milesial** [comment]
Hi, you should leave as it is, the Dataset is not used except for its `preprocess` method. I should maybe change it to a class method.
I am using numpy 1.16.2
