### ISSUE TITLE
Image Preprocessing

### ISSUE THREAD

**Issue by estelle1722** [milesial/Pytorch-UNet#9]
Hi!
Your work is great!I am intersted very much.Could you tell me something about your dataset preprocessing?My problems are as follows:
1.Do the dataset images have different sizes?How do you do preprocessing if it does?
Thanks.

**Comment by estelle1722** [comment]
Oh,scaling the images down by half is a good idea.
Thank you.

**Comment by milesial** [comment]
No problem :)
