### ISSUE TITLE
Unet

### ISSUE THREAD

**Issue by Zebrocode** [milesial/Pytorch-UNet#90]

**Comment by Zebrocode** [comment]
self.down4 = Down(512, 512) could you please tell me why the paragrams is (512,512) rather than (512,1024). I see the figure in Unet paper the that the last layer double the channel 
![图片](https://user-images.githubusercontent.com/28325377/69927071-d287a400-14f1-11ea-89e7-06a0a85441ff.png)

**Comment by milesial** [comment]
Hi, I am using bilinear upsampling before the concatenation of white and blue, so in order for the channels before the green arrow and after to match, all the these channels on the right side are halved. 

Read more in #69
