### ISSUE TITLE
Batch loss results

### ISSUE THREAD

**Issue by Branikas** [milesial/Pytorch-UNet#92]
Hi milesial and all.

Sorry for making such a dump question, but for some reason I get values of batch error higher than 1. Do you have any idea why could this be? 
I think it has to do with how I load the data, but my images are RGB-255, while the masks are binary, 0 or 1. Is there a problem with that?
Thanks.

**Comment by milesial** [comment]
No that's good, the masks should be 0 or 1 and the images RGB.
Is it the validation Dice loss that is higher than 1 or the train loss ?
Have you pulled the last commit ?

**Comment by Branikas** [comment]
The train loss, In validation I get normal values, that's why I think I have messed up with loading.
I will check how I preprocess the data because I have almost 1M patches and can't manually check if all the masks are black.
I haven't, I will pull and try again.
Thank you very much.

**Comment by Branikas** [comment]
Hey Milesial, sorry for asking in this thread, but I thought I shouldn't make another one, I have another question. How exactly the network predicts the mask for an image that has a different size than the ones used during training and validation? 
Does it segment it or it automatically expands the input layer while keeping the distribution of the trained weights?
Many thanks in advance!

**Comment by milesial** [comment]
Hi, the UNet is fully convolutional, so only kernel weights for convolutions are learned. These convolutions can be applied to images of any size.
Whatever the image size, there will be the same amount of parameters to learn because of convolutions.

**Comment by Branikas** [comment]
Gosh, you re right, and the respective output will accordingly be bigger to match the input image with the same parameters. Thank you so much!
