### ISSUE TITLE
RuntimeError: Expected object of scalar type Long but got scalar type Float for argument #2 'target'

### ISSUE THREAD

**Issue by sajidmahmud** [milesial/Pytorch-UNet#93]
I am doing a multiclass segmentation, my input images are grayscale and the label masks are rgb. I changed my masks from 3 channel rgb to 8 channels ( because the number of classes are 8 in my case). I get this error when I wish to run it. Here is the error

////

Traceback (most recent call last):
  File "/home/rni/Downloads/Life or death/Pytorch-UNet/train.py", line 181, in <module>
    val_percent=args.val / 100)
  File "/home/rni/Downloads/Life or death/Pytorch-UNet/train.py", line 87, in train_net
    loss = criterion(masks_pred, true_masks)
  File "/home/rni/anaconda3/envs/Sajid/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rni/anaconda3/envs/Sajid/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 916, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "/home/rni/anaconda3/envs/Sajid/lib/python3.7/site-packages/torch/nn/functional.py", line 1995, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/rni/anaconda3/envs/Sajid/lib/python3.7/site-packages/torch/nn/functional.py", line 1826, in nll_loss
    ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: Expected object of scalar type Long but got scalar type Float for argument #2 'target'

I have attached the dataset.py file which I changed to accomodate changing mask shape from 3 channel to 8 channel (basically rgb to one hot encoding)

////

from os.path import splitext
from os import listdir
import numpy as np
from glob import glob
import torch
from torch.utils.data import Dataset
import logging
from PIL import Image

color_dict = {0:(255,0,0),
              1:(43,255,0),
              2:(128,0,255),
              3:(0,255,255),
              4:(255,128,0),
              5:(255,0,255),
              6:(255,255,0),
              7:(0,0,0)}
def rgb_to_onehot(rgb_arr, color_dict):
    num_classes = len(color_dict)
    shape = rgb_arr.shape[:2]+(num_classes,)
    arr = np.zeros( shape, dtype=np.int8 )
    for i, cls in enumerate(color_dict):
        arr[:,:,i] = np.all(rgb_arr.reshape( (-1,3) ) == color_dict[i], axis=1).reshape(shape[:2])
    return arr

def onehot_to_rgb(onehot, color_dict):
    single_layer = np.argmax(onehot, axis=-1)
    output = np.zeros( onehot.shape[:2]+(3,) )
    for k in color_dict.keys():
        output[single_layer==k] = color_dict[k]
    return np.uint8(output)

class BasicDataset(Dataset):
    def __init__(self, imgs_dir, masks_dir, scale=1):
        self.imgs_dir = imgs_dir
        self.masks_dir = masks_dir
        self.scale = scale
        assert 0 < scale <= 1, 'Scale must be between 0 and 1'

        self.ids = [splitext(file)[0] for file in listdir(imgs_dir) 
                    if not file.startswith('.')]
        logging.info(f'Creating dataset with {len(self.ids)} examples')

    def __len__(self):
        return len(self.ids)

    def preprocess(self, pil_img,flag):
        w, h = pil_img.size
        newW, newH = int(self.scale * w), int(self.scale * h)
        assert newW > 0 and newH > 0, 'Scale is too small'
        pil_img = pil_img.resize((newW, newH))

        img_nd = np.array(pil_img)

        if len(img_nd.shape) == 2:
            img_nd = np.expand_dims(img_nd, axis=2)

        # HWC to CHW
        if(flag==1):
            img_trans = img_nd.transpose((2, 0, 1))
            if img_trans.max() > 1:
                img_trans = img_trans / 255
        else:
            img_trans = rgb_to_onehot(img_nd,color_dict)
            img_trans = img_trans.transpose((2, 0, 1))
            if img_trans.max() > 1:
                img_trans = img_trans / 255

        return img_trans

    def __getitem__(self, i):
        idx = self.ids[i]
        mask_file = glob(self.masks_dir + idx + '*')
        img_file = glob(self.imgs_dir + idx + '*')

        assert len(mask_file) == 1, \
            f'Either no mask or multiple masks found for the ID {idx}: {mask_file}'
        assert len(img_file) == 1, \
            f'Either no image or multiple images found for the ID {idx}: {img_file}'
        mask = Image.open(mask_file[0])
        img = Image.open(img_file[0])

        assert img.size == mask.size, \
            f'Image and mask {idx} should be the same size, but are {img.size} and {mask.size}'

        img = self.preprocess(img,1)
        mask = self.preprocess(mask,2)

        return {'image': torch.from_numpy(img), 'mask': torch.from_numpy(mask)}

**Comment by milesial** [comment]
The error seems pretty clear. The target masks should be long integer (class indices), not RGB. Check out the documentation https://pytorch.org/docs/stable/nn.html?highlight=crossentropyloss#torch.nn.CrossEntropyLoss

**Comment by sajidmahmud** [comment]
I changed my target masks to long, and this error occurs.

Traceback (most recent call last):
  File "/home/rni/Downloads/Life or death/Pytorch-UNet/train.py", line 182, in <module>
    val_percent=args.val / 100)
  File "/home/rni/Downloads/Life or death/Pytorch-UNet/train.py", line 88, in train_net
    loss = criterion(masks_pred, true_masks)
  File "/home/rni/anaconda3/envs/Sajid/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rni/anaconda3/envs/Sajid/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 916, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "/home/rni/anaconda3/envs/Sajid/lib/python3.7/site-packages/torch/nn/functional.py", line 1995, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/rni/anaconda3/envs/Sajid/lib/python3.7/site-packages/torch/nn/functional.py", line 1826, in nll_loss
    ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: 1only batches of spatial targets supported (non-empty 3D tensors) but got targets of size: : [1, 8, 165, 768]

**Comment by milesial** [comment]
Please read the documentation https://pytorch.org/docs/stable/nn.html?highlight=crossentropyloss#torch.nn.CrossEntropyLoss

You shouldn't have 8 channels but only 1 with the class indices as values

![image](https://user-images.githubusercontent.com/30204471/70005639-9f352b80-156a-11ea-8e94-2fe8c7e0ee6e.png)
