### ISSUE TITLE
Some problems occurred in predict.py.

### ISSUE THREAD

**Issue by DL-Alva** [milesial/Pytorch-UNet#94]
Hi, sorry for troubling you. But when I run predict.py, it remind AttributeError: 'numpy.ndarray' object has no attribute 'unsqueeze':

Traceback (most recent call last):
  File "origin_predict.py", line 135, in <module>
    device=device)
  File "origin_predict.py", line 32, in predict_img
    img = img.unsqueeze(0)
AttributeError: 'numpy.ndarray' object has no attribute 'unsqueeze'

Do you know how to deal with it? Thank you so much.

**Comment by milesial** [comment]
Hi, can you try after pulling the last commit on master ?

**Comment by DL-Alva** [comment]
Thank you for your reply. I try to use torch.from_numpy(img).unsqeeze(0），to transfer the numpy type of img to that of torch.

**Comment by glesx** [comment]
I'm having a similar problem with predict.py:

python predict.py -i validation.jpg --viz --no-save
```
Traceback (most recent call last):
  File "predict.py", line 132, in <module>
    device=device)
  File "predict.py", line 44, in predict_img
    transforms.Resize(full_img.shape[1]),
AttributeError: 'JpegImageFile' object has no attribute 'shape'

 
```

**Comment by glesx** [comment]
I'm getting the following error:

python predict.py -i validation.jpg --viz --no-save

```
Traceback (most recent call last):
  File "predict.py", line 132, in <module>
    device=device)
  File "predict.py", line 25, in predict_img
    ds = BasicDataset('', '', scale=scale_factor)
  File "C:\Users\glesx\OneDrive - Monsanto\Migrated from My PC\Documents\GitHub\Pytorch-UNet\utils\dataset.py", line 18, in __init__
    self.ids = [splitext(file)[0] for file in listdir(imgs_dir)
FileNotFoundError: [WinError 3] The system cannot find the path specified: ''
```

**Comment by cmlyldz** [comment]
I am also getting similar error
python predict.py -i austin.png --viz --no-save
`Reloaded modules: unet, unet.unet_model, unet.unet_parts, utils.data_vis, utils.dataset
Traceback (most recent call last):

  File "D:\PW\courses\neuralNetworks\repo\Pytorch-UNet\predict.py", line 141, in <module>
    device=device)

  File "D:\PW\courses\neuralNetworks\repo\Pytorch-UNet\predict.py", line 26, in predict_img
    ds = BasicDataset('', '', scale=scale_factor)

  File "D:\PW\courses\neuralNetworks\repo\Pytorch-UNet\utils\dataset.py", line 18, in __init__
    self.ids = [splitext(file)[0] for file in listdir(imgs_dir)

FileNotFoundError: [WinError 3] The system cannot find the path specified: ''`

**Comment by milesial** [comment]
Hi, can you try again after pulling the last commit ?

**Comment by cmlyldz** [comment]
Commit is works for me. But there is another problem.
![image](https://user-images.githubusercontent.com/31888490/70661747-3eda7400-1c65-11ea-9649-5a97e62598d9.png)


I use passing this error with - transforms.Resize(np.array(full_img).shape[1]), - but when I use this my predicted image is totally white.

**Comment by milesial** [comment]
You validation DICE is > 1 so there is a problem with your masks. If you have 2 classes, make sure the mask values are 0s or 1s

**Comment by cmlyldz** [comment]
I have only one class. As an example my train image;
![image](https://user-images.githubusercontent.com/31888490/70663355-7860ae80-1c68-11ea-9e0a-6fb07386ce78.png)

And my mask;
![image](https://user-images.githubusercontent.com/31888490/70663387-844c7080-1c68-11ea-9faf-4128c4614639.png)

**Comment by milesial** [comment]
Verify that after loading your mask, the tensor contains only 0s and 1s

**Comment by cmlyldz** [comment]
It has only true and falses, I think it means 0 and 1;

![image](https://user-images.githubusercontent.com/31888490/70672559-ee244480-1c7f-11ea-9ac1-dd0584e93792.png)

**Comment by milesial** [comment]
can you print the resulting true mask tensor and the network output values ?

**Comment by cmlyldz** [comment]
Can you be more spesific? Where are they?

**Comment by milesial** [comment]
In the train loop https://github.com/milesial/Pytorch-UNet/blob/ebe3bbb3ca67502db407eaa8273071a871d4b744/train.py#L81

print masks_pred and true_masks and make sure they are as expected

**Comment by cmlyldz** [comment]
True mask;
![image](https://user-images.githubusercontent.com/31888490/70673106-b0282000-1c81-11ea-8e43-ecb986ce9286.png)
mask_pred;
![image](https://user-images.githubusercontent.com/31888490/70673126-c930d100-1c81-11ea-8bdd-a06029d68313.png)

**Comment by milesial** [comment]
Please show some of the values of these tensors : min, max, type, ...

**Comment by cmlyldz** [comment]
I hope you mention about following image;
![image](https://user-images.githubusercontent.com/31888490/70674620-d13f3f80-1c86-11ea-9df1-0452b779225b.png)

**Comment by milesial** [comment]
Yes that what I meant. The values of the true mask should be between [0, 1], as they are probabilities. Divide your true masks by 255 in your loader

**Comment by cmlyldz** [comment]
no its same. its not bypassed.

**Comment by cmlyldz** [comment]
I solve the problem, it is about .tif files.

> I can reproduce that on Windows. Downgrading libtiff to 4.0.10 (conda install libtiff=4.0.10) works. Investigating it...
> 
> PS: it works fine on macOS and Linux, only Windows is failing.

After changing libtiff version it works properly.

**Comment by Janene-Li** [comment]
> I'm getting the following error:
> 
> python predict.py -i validation.jpg --viz --no-save
> 
> ```
> Traceback (most recent call last):
>   File "predict.py", line 132, in <module>
>     device=device)
>   File "predict.py", line 25, in predict_img
>     ds = BasicDataset('', '', scale=scale_factor)
>   File "C:\Users\glesx\Documents\GitHub\Pytorch-UNet\utils\dataset.py", line 18, in __init__
>     self.ids = [splitext(file)[0] for file in listdir(imgs_dir)
> FileNotFoundError: [WinError 3] The system cannot find the path specified: ''
> ```
> 
> When I add a path, I get this error instead:
> 
> ```
> Traceback (most recent call last):
>   File "predict.py", line 132, in <module>
>     device=device)
>   File "predict.py", line 44, in predict_img
>     transforms.Resize(full_img.shape[1]),
> AttributeError: 'JpegImageFile' object has no attribute 'shape'
> ```

I have come to similar problem like this:
```
Traceback (most recent call last):
  File "predict.py", line 131, in <module>
    device=device)
  File "predict.py", line 43, in predict_img
    transforms.Resize(full_img.shape[2]),
AttributeError: 'PngImageFile' object has no attribute 'shape'
```
 It seems like png picture cannot use '.shape[2]'.... I change it into '.width' and finally succesfully run the project~

**Comment by milesial** [comment]
@Janene-Li make sure you are using the latest version of Pillow
