### ISSUE TITLE
Problem with starting train

### ISSUE THREAD

**Issue by cmlyldz** [milesial/Pytorch-UNet#96]
![image](https://user-images.githubusercontent.com/31888490/70404992-0a37a400-1a3c-11ea-9ee2-a325104ccdd3.png)

as shown in the image training is not starts. What can I do?

**Comment by milesial** [comment]
Training on cpu might be very slow, have you tried waiting ?

**Comment by cmlyldz** [comment]
Yes I did, I take ss after 2 hours. Also I have 1050ti but I cannot use gpu, dont know why.

**Comment by milesial** [comment]
Try with gpu and set `num_workers=0` in train.py

**Comment by cmlyldz** [comment]
Thank you very much. It worked.
