### ISSUE TITLE
TypeError: 'int' object is not iterable when running code predict,py

### ISSUE THREAD

**Issue by BianChang** [milesial/Pytorch-UNet#98]
Hi milesial, soorry to disturb you again, a little problem when running the code predict.py, I changed the n_classes to 3 so the predict.py can fit my data but encountered this error:
Traceback (most recent call last):
  File "predict.py", line 132, in <module>
    device=device)
  File "predict.py", line 25, in predict_img
    img = torch.from_numpy(BasicDataset.preprocess(full_img, scale_factor))
  File "/home/du/bc/AIimm/PycharmProject/u-net/utils/dataset.py", line 27, in preprocess
    w, h = pil_img.size
TypeError: 'int' object is not iterable

How should I adjust my code please? Thank you

**Comment by milesial** [comment]
Make sure you loaded your full_img as a Pillow image.
What does the .size return ?

**Comment by BianChang** [comment]
Thanks for your reply~ I changed
 'w, h = pil_img.size' 
to 
'w = pil_img.shape[0]
 h = pil_img.shape[1]'
in dataset.py and it can work just fine~

**Comment by milesial** [comment]
mmh, that should work anyway, are you on python3.7 ?

**Comment by BianChang** [comment]
I work on python3.6.9, and PIL is 6.2.1, if use '.size' then it will return the total pixel numbers rather than the image height and width

**Comment by milesial** [comment]
that's strange, the doc says 
![image](https://user-images.githubusercontent.com/30204471/70849080-0d86c180-1e7a-11ea-88e7-0c0320cd0a0f.png)

https://pillow.readthedocs.io/en/stable/reference/Image.html#attributes

Did you install the old PIL library or [Pillow](https://pillow.readthedocs.io/en/stable/index.html) ?

**Comment by BianChang** [comment]
I think that is because the '.size' in the code is from numpy rather than PIL

**Comment by milesial** [comment]
oh ok, but the object should be a Pillow image not a numpy array. Anyway, closing this
